### ISSUE TITLE
Incorrect Error Message Given When a Preferred Phone / Email is Selected that Doesn't Exist, and No Phone/Emails are Filled in

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/EDA#1000]
* **Do you want to request a *feature* or report a *bug*?** : 
BUG

* **What is the current behavior?**
When user selects a "Preferred Phone" or "Preferred Email" that doesn't have a matching field, and leaves all the email fields blanks, the Error message says, "The email selected for Preferred Phone [Email] can't be blank."

* **What is the expected behavior?**

The expected error message would be: "We can't find the email specified in Preferred Email. Make sure that you're entering the field label of an existing custom email field."

* **What is the motivation / use case for changing the behavior?**
Clarity of what the actual issue is and how to resolve it.

Steps to Reproduce:
1. Setup > Contact > Fields & Relationships> Preferred Phone > Values > New > PhoneNoMatchingField > Save
2. Setup > Contact > Fields & Relationships> Preferred Email > Values > New > EmailNoMatchingField > Save
3. Contact > New > [Fill in First Name & Last Name] > Preferred Email = "PhoneNoMatchingField" > Save
--> Actual Result : The email selected for Preferred Email can't be blank."
--> Expected Result : "We can't find the email specified in Preferred Email. Make sure that you're entering the field label of an existing custom email field."
4. Contact > New > [Fill in First Name & Last Name] > Preferred Phone = "PhoneNoMatchingField" > Save
--> Actual Result : "The phone selected for Preferred Phone can't be blank."
--> Expected Result : "We can't find the Phone specified in Preferred Phone. Make sure that you're entering the field label of an existing custom Phone field."

Additional Notes:
1) We will want to ensure "custom email field" and "custom Phone field" both follow the same capitalization conventions. I believe that "Phone" should be lowercased, because we are not talking about the specific "Phone" field but one of many "phone" fields.
2) We will want to ensure this solution is also implemented for translations.

**Comment by dgamboni** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HoxEQAS" target="_blank">W-037660</a>

**Comment by MatthewBlanski** [comment]
Performing cleanup. This was closed some time ago.
