### ISSUE TITLE
Auto Populate Affiliation Lookup Field on Student Course Connection

### ISSUE THREAD

**Issue by kdy618** [SalesforceFoundation/EDA#1009]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Bug 

* **What is the current behavior?**
When a user creates a Student Course Connection and a Program Enrollment is associated to that new Student Course Connection, the Affiliation lookup field on Student Course Connection is not auto populated even if an Affiliation record exist on the Program Enrollment. 

* **What is the expected behavior?**
When a user creates a Student Course Connection and a Program Enrollment is associated to that new Student Course Connection, the Affiliation lookup field on Student Course Connection should be auto populated if an Affiliation record exist on the Program Enrollment and the Program Enrollment is associated to the new Student Course Connection. 

* **What is the motivation / use case for changing the behavior?**
We want to mimic the behavior for new Faculty Course Connection where Affiliation is auto populated if an Affiliation exists on Program Enrollment and Program Enrollment is associated to the new Faculty Course Connection.

**Comment by kdy618** [comment]
**lurch : attach W-037612

**Comment by robertbwatson** [comment]
@kdy618 Hmm I'm not sure that worked - I think you might not need a space between lurch and :

**Comment by kdy618** [comment]
> @kdy618 Hmm I'm not sure that worked - I think you might not need a space between lurch and :

ty for that catch!

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hor6QAC" target="_blank">W-037612</a>

**Comment by kporray1** [comment]
This issue was delivered in May 2020.
