### ISSUE TITLE
[Area of Product] - Short and simple descriptive name describing the issue

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#1026]
*Summary*
A high-level, non-technical explanation of what was encountered. Should be no longer than a 2 sentences, if possible.

*Is there a workaround?*
An explanation, including visuals if necessary, identifying the workaround.

*Is there any Pre-Configuration required?*
A list of prerequisites that must be met in order to reproduce what has been identified (supports the section: What are the Steps to Reproduce?)

* If there are any custom settings that need to be enabled or any other prerequisites describe them here.  
* If this is only an issue in a certain browser, include that here.
* If there are certain Accessibility tools or setup needed (like only using your keyboard or a screen-reader, etc.), include them here.
* If N/A, just type N/A or remove this section.

*What are the Steps to Reproduce?*
A list of sequential steps that outline the process of reproducing what has been identified

*What is the expected behavior?*
A description of what was expected.

*What is the actual behavior?*
A description of what was actually encountered.  (including visuals are helpful here) 

*What is the motivation / use case for changing the behavior?*
A brief summary identifying why you want to see the expected behavior.

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HpvoQAC" target="_blank">W-038205</a>

**Comment by jacebryan** [comment]
This was a Test issue. Closing the Issue now. WI has been deleted.
