### ISSUE TITLE
dmlWrapper is unable to process multiple primary affiliation updates per Contact

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#1040]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

=========

**Background**: Issue was [first reported](https://powerofus.force.com/s/question/0D51E000059FuZTSA0/primary-affilations-are-not-updating-in-bulk) in the Hub on 12/19/2020. Follow up post on 12/31 confirmed another customer org was experiencing the same behavior.

=========

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
In EDA, if the same Contact has multiple Affiliations updated to Primary at the same time, the dmlWrapper can only handle one of the updates. 

**Example/Steps to Reproduce**

First: I used data loader to insert 145 affiliations for 29 Contacts (5 Primary Affiliations a piece: Academic Program, Business Organization, Educational Institution, Sports Organization and University Department) and all Affiliations were created. It took about 5 minutes before all Primary fields on Contact were updated to reflect that insert.

Second: I went ahead and inserted another 145 non-primary affiliations for those same 29 contacts. They now have 5 non-primary affiliations and 5 primary affiliations. 

Third: I then updated the non-primary affiliations to primary. When running the New Affiliations with Contact Report (grouping by Contact ID) it shows that all 10 affiliations are now marked as Primary. The Primary fields on Contact still show the original Primary Affiliations.

* **What is the expected behavior?**
If the same Contact has multiple Affiliations updated to Primary at the same time, the dmlWrapper is able to handle all of the updates.

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HqGwQAK" target="_blank">W-038401</a>

**Comment by jofsky** [comment]
Included in production release 1.91
