### ISSUE TITLE
[EDA] Prevent Deletion of Course Connection If It Has Related Child Records 

### ISSUE THREAD

**Issue by kdy618** [SalesforceFoundation/EDA#1046]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature 
* **What is the current behavior?**
When users delete a Course Connection with child records, the system will allow users to delete the Course Connection and it will not delete child records. 
* **What is the expected behavior?**
We want to provide customers the ability to prevent deletion of Course Connection if it has related child records by allowing them to toggle a checkbox in the Hierarchy Setttings. 
* **What is the motivation / use case for changing the behavior?**
By giving customers the ability to control whether a Course Connection with child records should be deleted or not, it will help them with maintaining a clean system. 
* **Acceptance Criteria**

  - **Given**: If Prevent_Course_Connection_Deletion__c checkbox is enabled in Hierarchy Settings
  - **When**: I try to delete a Course Connection record with child records
  - **Then**: I should not be able to delete the Course Connection record.

**Comment by kdy618** [comment]
**lurch: add W-037957

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HqZoQAK" target="_blank">W-038549</a>

**Comment by kdy618** [comment]
**lurch: detach

**Comment by LurchTheButler** [comment]
Detached <a href="https://foundation.my.salesforce.com/a2x1E000001HqZoQAK" target="_blank">W-038549</a>

**Comment by kdy618** [comment]
**lurch: attach W-037595

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HoogQAC" target="_blank">W-037595</a>

**Comment by jofsky** [comment]
Included in production release 1.91
