### ISSUE TITLE
[EDA] Multiple contacts marked as deceased in the same bulk operation are not properly handled

### ISSUE THREAD

**Issue by kdy618** [SalesforceFoundation/EDA#1050]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Bug
* **What is the current behavior?**
If multiple Contacts from different Accounts are updated and the fields updated in the Contact records are different (this includes some that are either marked deceased or Excluded_from_HouseholdNaming__c), all the Account names are not updated properly. 
* **What is the expected behavior?**
If multiple Contacts from different Accounts are updated and the fields updated in the Contact records are different (this includes some that are either marked deceased or Excluded_from_HouseholdNaming__c), all the Account names should be updated properly. 
* **What is the motivation / use case for changing the behavior?**
Existing functionality should support different bulk operations. 
* **Acceptance Criteria**

  - **Given**: If Automatic HH Naming is enabled in EDA Settings. 
  - **When**: I updated 2 Contacts from different Accounts where the 1st Contact is marked Deceased and the 2nd Contact's firstName was updated
  - **Then**: The Account names for the 2 Accounts should be updated appropriately.

**Comment by kdy618** [comment]
**lurch: attach W-038515

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HqW1QAK" target="_blank">W-038515</a>
