### ISSUE TITLE
[EDA] - HH & Admin Account Naming Format is Incorrect If Prefix is Not Inside Braces

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/EDA#1053]
* **Do you want to request a *feature* or report a *bug*?** : BUG

* **What is the current behavior?** : 
When the running User's language is in Spanish or in French, the "Administrative Account Name Format" and "Household Account Name Format" is duplicating some words.

* **What is the expected behavior?** : 
The Name Formats follow the convention (and do not duplicate words.)

* **What is the motivation / use case for changing the behavior?** : 
User experience

Steps to Reproduce : 
1. Change running user language to French (Setup > Users > Edit > Change Language > Save.)
2. Go to Parameters EDA > Systeme > Modifier > [This should change the drop-downs at the bottom to **Compte administratif {!LastName}**] > Enregistrer
3. Create a Contact "Fox Mulder"
4. Look at the Account Name

  Expected Result : Compte administratif Mulder 
  Actual Result : Compte administratif Compte administratif Mulder

5. Go to Parameters EDA > Systeme > Modifier > Change to HH Account Model & Change Naming Format to **Foyer {!{!FirstName}} {!LastName}**

  Expected Result : Foyer Dana Scully
  Actual Result : Foyer Foyer Dana Scully

Note that this also happens in Spanish. It does not happen in English.

**Comment by dgamboni** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HqgfQAC" target="_blank">W-038618</a>
