### ISSUE TITLE
NullPointerException in Household Account Naming

### ISSUE THREAD

**Issue by zeugin18** [SalesforceFoundation/EDA#1073]
* **Do you want to request a *feature* or report a *bug*?**
Bug
* **What is the current behavior?**
By creating a contact, the process fails to create your household account. 
The problem is related to the configuration of the family name format: 
In the EDA settings, I have selected "Other" for the name format and have informed a new name format.
_The key of the error is in the language of the organization._ If a contact is created in the language the format was set up in, it doesn't give an error. If the language is changed, the configuration is lost and the process fails (format is null).

* **What is the expected behavior?**

1. Set up another family name format.
2. Change org language.
3. Create a contact with its household account without errors.

* **What is the motivation / use case for changing the behavior?**
This error is blocking the process.

**Comment by lifewithryan** [comment]
@jacebryan can we get this popped over to the hub? I'd also like to know what pattern @zeugin18 is using in the "other" format. We've recently made some changes (and are addressing an issue in the next release) and knowing the pattern will help us determine if the changes we are making address this issue.

**Comment by jacebryan** [comment]
Hi @zeugin18 - please post what you've encountered in the [EDA Power of US Hub group](https://powerofus.force.com/s/group/0F980000000D6ujCAC/education-data-architecture) so our team can engage with you further and be able to determine next steps. When posting about this issue in the group please be sure to identify the pattern you used for the "other" format along with the language of the organization. That will help us attempt to reproduce what you are encountering. I'll be closing this issue now. Thank you!
