### ISSUE TITLE
If the API/Developer Name of the Administrative Account is not 'Administrative' Account Naming does not work properly

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/EDA#1076]
_Reference Investigation W-7174330 ([GUS](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000079YSoIAM/view))_

### Summary
Account Naming in EDA Settings does not work for any Account Record Type other than one with the API Name of `Administrative__c` regardless of values set in EDA Settings and will default to a `{!LastName} Account` format.

### Steps to Repeat
Replicated in scratch org with EDA 1.91 installed via `install_prod` flow.

1. In EDA Settings, change **Administrative Account Naming Format** from default of `{!LastName} Administrative Account` to `{!{!FirstName}} {!LastName} Administrative Account` in the picklist. Save.
2. Create a test Contact with **First Name:** `TestFirst1` **Last Name:** `TestLast1`. 
3. Confirm that **Account Name** on created Contact is `TestFirst1 TestLast1 Administrative Account`
4. Now in Setup, edit the Administrative Record Type to change the Developer Name to `Administrative_Test` (any value other than `Administrative`). Don't make any changes in EDA Settings except to confirm values are the same as before.
![image](https://user-images.githubusercontent.com/4614343/73600011-b7004000-4518-11ea-956c-770d9740efbe.png)
5. Create a second test Contact with **First Name:** `TestFirst2` **Last Name:** `TestLast2`

### Expected Behavior

**Account Name** on created contact should be `TestFirst2 TestLast2 Administrative Account`

### Actual Behavior

**Account Name** on created contact is `TestLast2 Account`

![image](https://user-images.githubusercontent.com/4614343/73600072-735a0600-4519-11ea-8c15-de8397e7aa0c.png)

### Other Testing

If a new Account Record Type is created and EDA Settings updated to use the new record type, the naming still malfunctions as noted above. If there is a Record Type with the API Name of `Administrative__c` it will be used as the Administrative Account record type regardless of selection in EDA Settings.

### Workaround

Ensure that an Account Record Type has the API name of `Administrative__c` and it's selected as the Administrative Account Record Type. 

### Possible Culprit

@kschaefges reviewed the code and suspects the problem is in _UTIL_Decscribe_ [here](https://github.com/SalesforceFoundation/EDA/blob/master/src/classes/UTIL_Describe.cls#L666)

` String recTypeId = getRecTypesMapByDevName('Account').get('Administrative');`

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HreyQAC" target="_blank">W-039108</a>

**Comment by MatthewBlanski** [comment]
Closed by #1283
