### ISSUE TITLE
[EDA] - Moving the Last Active Contact in a Household Creates an Account called "Household"

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/EDA#1077]
**Issue : ** Potential Bug with Household Account Renaming when last Active or Existing Contacts are Moved or Merged to another Account.

**Current Behavior / Steps to Reproduce**
**Prerequisites :** 
- Default Account = Household
- Automatic Household Naming is Enabled
- "Inactive Contact" means the contact is marked as Deceased and/or Exclude from Household Naming

**Use Case #1 : Merge Last Active Contact to a Different Existing Account**

- Household Account has 2 Inactive Contacts and 1 Active Contact
- Move the Active Contact to a different existing Account
- Result : Account is renamed to "Household" & has 2 inactive contacts
(existing account to which the Contact is moved gets updated correctly)
 
**Use Case #2 : Move Last Active Contact to a New Account**

- Household Account has 2 Inactive Contacts and 1 Active Contact
- Move the Active Contact to a New HH Account
- Result : Contact's Account is renamed to "Household" & has 2 inactive contacts
- Add'l Result : (new account with Contact name is created)

**Use Case #3 : Move Only Contact to a Different Existing Account**
- Household Account has 1 Contact
- Move the Contact to a different Account 
- Result : Contact's Account is renamed to "Household" and has 0 related contacts 
- Add'l Result (existing account to which the Contact is moved gets updated correctly)
 
**What is the expected behavior?**
- No Accounts only called "Household" exist
- No Accounts with 0 related contacts exist

**What is the motivation / use case for changing the behavior?**
- Data consistency

**Acceptance Criteria**
TBD (potentially prevent or warn users from getting their data into this state.)

**Add'l Info**
Note that https://github.com/SalesforceFoundation/EDA/pull/989 changed functionality so that if the last contact or the last active contact is deleted or made inactive, the Account name will keep the name of the last existing account. That solution doesn't necessarily make sense here, because the Contact has been reparented to another account and could cause confusion to have 2 accounts with the same name yet one has no contacts in it, etc. See demo video : https://drive.google.com/open?id=1LqHA5ZLx63pgl6wpKfBmB_hsqp2FyQCy

**Comment by dgamboni** [comment]
**Lurch: Add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hrf3QAC" target="_blank">W-039109</a>

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.  (W-7931278)
