### ISSUE TITLE
EDA Settings: Null error displayed due to lack of translation of Household Account Naming Format

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#1078]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Bug

**Issue first reported in the Hub on 2/3/2020**
https://powerofus.force.com/s/question/0D51E00005CQenVSAT/issue-with-household-account-naming

**Steps to reproduce**

1. Log in and select a running user who’s default language value is set to Espanol. If you don't have a running user with this language then please change the language for the user you are logged into.

2. Navigate to EDA Settings --> System and set the following:
-- Modelo de cuenta predeterminado (i.e. Default Account Model) = Household Account
-- Formato de nombre de cuenta doméstica (i.e. Household Account Name Format) = Otros (i.e. Other)
-- Populate **Family {!LastName}** as the format used for naming Household Accounts
-- Click "Guardar" (i.e. Save)

![image](https://user-images.githubusercontent.com/25934611/73676611-48d38e80-467a-11ea-9c0f-de99852b06ed.png)

3. Change the running users default language to English and go back to the EDA Settings → Systems page. Notice that the values for Administrative and Household Account Name Formats still read in Espanol.

![image](https://user-images.githubusercontent.com/25934611/73676737-846e5880-467a-11ea-93eb-609d6e922b79.png)

4. Attempt to create a Contact and you should receive the following error message: hed.TDTM_Contact: execution of AfterInsert caused by: **System.NullPointerException: Script-thrown exception (System Code)**

![image](https://user-images.githubusercontent.com/25934611/73676811-a2d45400-467a-11ea-87d5-991ac6582fe6.png)

5. Navigate back to EDA Settings --> Systems and click "Edit".  
-- Notice the following: the values for Administrative and Household Account Name Formats now read in English however, the value for Household Account Name Format has been defaulted back to the 1st value in the picklist.

![image](https://user-images.githubusercontent.com/25934611/73676938-e333d200-467a-11ea-9439-2eb87d88e8d1.png)

6. Select "Other" for Household Account Name Format. Verify that you see Family {!LastName}. Click "Save".

![image](https://user-images.githubusercontent.com/25934611/73677040-15453400-467b-11ea-9292-3f5dfd1efc1b.png)

7. Attempt to create a Contact. You are able to create a Contact w/out error.

**What is the current behavior?**

I am unable to create a Contact if the language of my user is not the same language as the user who set the default values for the Administrative Account and/or Household Account Naming Format.

**Potential Cause**

In this specific example I believe this is happening because the values that were previously set for Household Account Naming Format are only being translated upon Edit. Once I click Edit on the EDA Settings → Systems tab and save I am able to create w/out the null error.

The same error would happen to a user who’s language was Espanol if the changes were made by a running user who’s language was English.

**Workaround** 

Modify and Save the settings.

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HrgQQAS" target="_blank">W-039124</a>

**Comment by MatthewBlanski** [comment]
Tracking [W-7931279](https://gus.lightning.force.com/a07B0000008WuerIAC)

**Comment by JasonFitzy** [comment]
We have decided to not pursue this bug at this time. There is a way to avoid the issue that is outlined above by going to settings and selecting "Other" for Household Account Name Format, see steps 5-7. Issues such as this will be considered for any future naming features within Education Cloud.
