### ISSUE TITLE
Fix HH Account Naming when Org model is set to Administrative

### ISSUE THREAD

**Issue by lifewithryan** [SalesforceFoundation/EDA#1083]
* **Do you want to request a *feature* or report a *bug*?**
- Bug
* **What is the current behavior?**
- When manually creating a Household Account while the EDA settings has the Administrative Account model specified as the default and being opted into automatic household naming, we currently get a SOQL Exception, or in some cases the HH Account name gets updated using the Administrative account pattern.
* **What is the expected behavior?**
- The HH account should be named using the HH account pattern regardless of what the default model setting is in settings.

* **What is the motivation / use case for changing the behavior?**
- It is broken
* **Acceptance Criteria**

  - **Given**: I am opted into Automatic HH Naming and my orgs default Account model is set to Administrative
  - **When**: I add a contact to, or modify an existing contact of an HH Account
  - **Then**: The HH Account Name should match the HH Account Naming pattern specified

**Comment by lifewithryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HrouQAC" target="_blank">W-039208</a>
