### ISSUE TITLE
Prevent Deletion of Terms if there is a related Course Offering or Application Records

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/EDA#1086]
Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in The Power of Us Hub.
For feature requests, please use the Ideas tab in The Power of Us Hub.

Do you want to request a feature or report a bug?
Feature

What is the current behavior?
When users delete a TERM with  TERM GRADES as child records, the system will allow users to delete the TERM and it will not delete child records if Prevent_Term_Deletion__c is not enabled.

What is the expected behavior?
We want to provide customers the ability to prevent deletion of TERMs if it has Application or Course Offering child records by allowing them to toggle a checkbox in the Hierarchy Settings.

What is the motivation / use case for changing the behavior?
By giving customers the ability to control whether a TERM with child records should be deleted or not, it will help them with maintaining a clean system.

Acceptance Criteria

Given: If Prevent_Term_Deletion__c checkbox is enabled in Hierarchy Settings
When: I try to delete a Term record with child records
Then: I should not be able to delete the Term record.

**Comment by skosgi1** [comment]
**lurch: attach W-038393

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HqGIQA0" target="_blank">W-038393</a>
