### ISSUE TITLE
Failing EDA Unit Tests that fail only when installed and run from a K12 org.

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/EDA#1088]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
there are 4 failing EDA Unit Tests that fail only when installed and run from a K12 org.
The unit tests are all in the AFFL_AccRecordType_TEST.cls (addRecordTypeToAcc, checkNPE, fillInPrimaryFieldForContacts and updateAdminAccRecordTypeBulk).

* **What is the expected behavior?**
All the unit tests should pass when run from both EDA and K-12

* **What is the motivation / use case for changing the behavior?**
Ensure functionality works

* **Acceptance Criteria**

  - **Given**: I have k12 installed
  - **When**: I run all unit tests
  - **Then**: All unit tests should pass

**Comment by skosgi1** [comment]
**lurch: attach W-039123

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HrgLQAS" target="_blank">W-039123</a>
