### ISSUE TITLE
[EDA/CCI] - Add Ability to Change Running User Language to regression_org Flow

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/EDA#1089]
**Description** : For the dev and dev_namespaced org shapes with the qa_org, dev_org, and dev_org_namespaced flows, the user is able to change the language of the org's running user. However, for the release org shape with regression_org flow, the user does not have permission/privileges to change the language. 

**Request** : Add the ability to change the running user's language to the release org shape with  regression_org flow

**Rationale** : This is needed to perform comprehensive regression of new and existing features. 

**Steps to Reproduce** : 

1. From the Terminal, create a "Release/Regression" scratch org with the following steps:
`cci org scratch release DsRelOrg --days 7 --default`
`cci flow run regression_org`

2. Open the Org 
`cci org browser`

3. Attempt to change the language
* Click Astro icon in top right corner (to open the User menu) 
* Click "Settings" (to open the Personal Information menu)
* Click "Language and Time Zone"

**Expected Result** : User can change the Language
**Actual Result** : Error message, _"Insufficient Privileges -- You do not have the level of access necessary to perform the operation you requested. Please contact the owner of the record or your administrator if access is necessary. For more information, see Insufficient Privileges Errors. 
Click here to return to the previous page."_

**Comment by dgamboni** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hs0bQAC" target="_blank">W-039292</a>

**Comment by MatthewBlanski** [comment]
The user can change them now.
