### ISSUE TITLE
[EDA] - Contact has Multiple Primary Affiliations to the Same Record Type  

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/EDA#1097]
Feature or Bug? 
- Bug

What is the current / expected behavior?
- Current Issue : We can create a situation where a contact has multiple primary affiliations for the same record type 
- Expected Behavior : For each Contact, only ONE Affiliation can be marked Primary per Account Record Type

Steps to Reproduce:
1. Create a Contact, "Marge Simpson"
2. Create 2 Business Accounts & 2 Educational Institutions (Moe's Bar, Kwik-E-Mart; Springfield Elementary; West Springfield High)
3. From Marge's "Affiliated Account" related list, create a PRIMARY Affiliation to Moe's Bar and to Springfield Elementary
--> Confirm Marges Contact Details page that the "Primary Bus Org" & "Primary Ed Inst" fields are populated with Moe's Bar & Springfield Elementary 
4. Click on the "" to see all Marge's Affiliations
--> Confirm there are 2, each marked "Primary"
5. Click on "AF-00000" to open the Moe's Bar affiliation
6. Click the "Edit" pencil next to Organization and change that from Moe's Bar to "West Springfield High" & Click "Save"
7. Click on "Marge Simpson" 
--> Verify that the Affl Acct related list has 2 Affil accounts for Ed Inst.
8. Click on Contact Details. 
--> Verify that the Primary Ed Inst has been updated to West Springfield High
9. Go back to the Affl Acct related list and click on "View All"
ACUTAL RESULT : Both Ed Inst. Affiliations are marked primary
EXPECTED RESULT : Only the "West Springfield High" Aff'l is marked Primary

Given a Contact
When I look at their list of All Affiliations 
I see only one record marked as primary for each record type

**Comment by dgamboni** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HsP1QAK" target="_blank">W-039533</a>
