### ISSUE TITLE
Salesforce Contact Merge Conflict with CON_CannotDelete_TDTM

### ISSUE THREAD

**Issue by kschaefges** [SalesforceFoundation/EDA#1101]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
In EDA 1.92, with the custom setting - Prevent Contact Deletion - set to TRUE and the Trigger Handler Record for CON_CannotDelete_TDTM active, customers are not able to complete a contact merge using the Salesforce Standard Contact Merge functionality (available in Classic).

To Reproduce:
1. Set the Prevent Contact Deletion custom setting to TRUE
2. Ensure the CON_CannotDelete_TDTM trigger handler is active
3. Create a HH Account
4. Create a Contact within that HH Account
5. Create a Contact Language for that Contact
6. Repeat Steps 4 & 5
7. Switch to Classic
8. Navigate to the HH account
9. Scroll to the Contact related List and click Merge Contacts
10. Select and necessary fields to retain between the 2 contacts
11. Click Merge & OK
12. You will get an error message stating: "This record can't be deleted because it has one or more related records associated with it. Delete the associated records first, then delete this record. To determine which records should be deleted first, click the Related tab. If you don't see related records, or if you're unable to delete them, contact your System Administrator for assistance."

* **What is the expected behavior?**
Since the Salesforce Standard Contact Merge reparents the children of the non-master record, the contact should be allowed to be deleted.

* **Workaround**
Disable the CON_CannotDelete_TDTM feature by going into Setup --> Custom Settings --> Manage: Hierarchy Settings and unchecking the "Prevent Contact Deletion" checkbox.

[This Hub post](https://powerofus.force.com/s/question/0D51E00005Ezx1FSAR/why-does-eda-block-deletion-of-contacts-accounts-with-related-records) includes a message for the workaround.

**Comment by kschaefges** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HsjfQAC" target="_blank">W-039706</a>

**Comment by kporray1** [comment]
This issue has been delivered and documented - see [Migrate Data in EDA](https://powerofus.force.com/s/article/EDA-Migrate-Data).
