### ISSUE TITLE
[EDA] Prevent Deletion of a Behavior Involvement Record when there is a Related Behavior Response Record

### ISSUE THREAD

**Issue by kdy618** [SalesforceFoundation/EDA#1102]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature
* **What is the current behavior?**
When users delete a Behavior Involvement with child records, the system will allow users to delete the Behavior Involvement and it will not delete child records.
* **What is the expected behavior?**
We want to provide customers the ability to prevent deletion of Behavior Involvement if it has related child records by allowing them to toggle a checkbox in the Hierarchy Setttings.
* **What is the motivation / use case for changing the behavior?**
By giving customers the ability to control whether a  Behavior Involvement with child records should be deleted or not, it will help them with maintaining a clean system.
* **Acceptance Criteria**

  - **Given**: If Prevent_Course_Offering_Deletion__c checkbox is enabled in Hierarchy Settings
  - **When**: I try to delete a Course Connection record with child records
  - **Then**: I should not be able to delete the Course Connection record.

**Comment by kdy618** [comment]
**lurch: attach W-035912

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAX3QAO" target="_blank">W-035912</a>
