### ISSUE TITLE
[EDA] Field Encryption Is Failing on ACCT_IndividualsAccount_TEST

### ISSUE THREAD

**Issue by kdy618** [SalesforceFoundation/EDA#1105]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Bug
* **What is the current behavior?**
Customers who have Contact Name encrypted have not been able to get push upgrade to 1.92.
* **What is the expected behavior?**
Customers who have Contact Name encrypted should be able to get push upgrade to 1.92. 
* **What is the motivation / use case for changing the behavior?**
Customers need to be able to receive the newest feature and bug updates from 1.92. 
* **Acceptance Criteria**

  - **Given**: A customer has enabled encryption on Contact "Name" field
  - **When**: When Salesforce tries to upgrade customer org to 1.92
  - **Then**: the customer org should be eligible to the upgrade without issues

**Comment by kdy618** [comment]
**lurch: attach W-039825

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hsx1QAC" target="_blank">W-039825</a>
