### ISSUE TITLE
Update to Description and Help Text on Application Type field on Application object 

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/EDA#1111]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Currently the 'Application Type' field on the Applicaiton object has the following help text and description 'The type of program or track the applicant is applying to. For example, Undergraduate, Graduate, or Transfer.'

* **What is the expected behavior?**
We'd like to change the help text to more generic 'The type of program or track the applicant is applying to. '

* **What is the motivation / use case for changing the behavior?**
TO make it more generic

* **Acceptance Criteria**

  - **Given**: I open the application record 
  - **When**: When I hover on the application type help text
  - **Then**: I should see the new help text. Also, new description on the field definition.

**Comment by skosgi1** [comment]
**lurch: attach W-039731

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HslgQAC" target="_blank">W-039731</a>
