### ISSUE TITLE
Updates to PPlan_CannotDelete_TDTM.cls to utilize Prevent_Program_Plan_Deletion__c hierarchy settings

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/EDA#1120]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
When a user tries to delete a Program Plan that has child records, the system prevents it from deleting. The feature is working fine, however, it doesn't take into consideration the 'Prevent_Program_Plan_Deletion__c' flag when preventing the delete.

* **What is the expected behavior?**
Take into consideration the value of 'Prevent_Program_Plan_Deletion__c' when trying to delete the Program Plan record with associated child records. This checkbox should be turned on for new and existing Customers by default. 

* **What is the motivation / use case for changing the behavior?**
Consistency with other CannotDeleted TDTMs

* **Acceptance Criteria**

  - **Given**: There are Program Plans with child record association and 'Prevent_Program_Plan_Deletion__c' hierarchy custom setting is enabled.
  - **When**: When the delete button is clicked 
  - **Then**: The Program Plan record should not be deleted.

  - **Given**: There are Program Plans with child record association and 'Prevent_Program_Plan_Deletion__c' hierarchy custom setting is not enabled.
  - **When**: When the delete button is clicked 
  - **Then**: The Program Plan record should be deleted.

**Comment by skosgi1** [comment]
**lurch: attach W-039900

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Ht76QAC" target="_blank">W-039900</a>
