### ISSUE TITLE
[EDA] Prevent Deletion of Account Record  if There are Associated Child Records

### ISSUE THREAD

**Issue by kdy618** [SalesforceFoundation/EDA#1121]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature
* **What is the current behavior?**
If an Account has related child records, the Account record is deleted. 
* **What is the expected behavior?**
If an Account has related child records, the Account record should not be deleted. 
* **What is the motivation / use case for changing the behavior?**
data integrity

**Comment by kdy618** [comment]
**lurch: attach W-039899

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Ht71QAC" target="_blank">W-039899</a>
