### ISSUE TITLE
[EDA] Prevent Deletion of Plan Requirement Record  if There are Associated Child Records

### ISSUE THREAD

**Issue by kdy618** [SalesforceFoundation/EDA#1125]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature
* **What is the current behavior?**
When a parent Plan Requirement with a child related Plan Requirement is deleted, the user is unable to delete the Plan Requirement unless the user disables PReq_CannotDelete_TDTM via trigger handler record. 
* **What is the expected behavior?**
A user should be able to control whether they are able to delete a parent Plan Requirement with a child related Plan Requirement is deleted, by enabling/disabling this feature via EDA settings/hierarchy custom settings instead of disabling PReq_CannotDelete_TDTM trigger handler record. 
* **What is the motivation / use case for changing the behavior?**
data integrity

**Comment by kdy618** [comment]
**lurch: attach W-039898

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Ht6wQAC" target="_blank">W-039898</a>
