### ISSUE TITLE
[EDA] Updating Name and Ownership In the Same Context Causes Duplicate Id Error in ACCT_IndividualAccounts_TDTM

### ISSUE THREAD

**Issue by aligeez** [SalesforceFoundation/EDA#1129]
**Current Behavior:** 
When a Contact record's Name and Ownership is updated in the same time/context, a duplicate ID error pops up. 

**Expected Behavior:**
When a Contact record's Name and Ownership is updated in the same time/context, it should not throw an error. 

**Steps to Reproduce:** 
1. Created a Contact record 
2. Result: Account was created for the Contact record
3. Update the existing Contact's record Name & Ownership via data upload/execute anonymous/integration tools/etc. 
4. Result: The error below pops up below and the Contact record is not updated. 

"Line: 9, Column: 1
System.DmlException: Update failed. First exception on row 0 with id 0033i00000F1S6EAAV; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, hed.TDTM_Contact: execution of AfterUpdate caused by: System.ListException: Duplicate id in list: 0013i00000G7SQLAA3 Class.hed.TDTM_TriggerHandler.processDML: line 184, column 1 Class.hed.ACCT_IndividualAccounts_TDTM.handleUpdateProcessing: line 467, column 1 Class.hed.ACCT_IndividualAccounts_TDTM.handlesAfterInsertUpdate: line 277, column 1 Class.hed.ACCT_IndividualAccounts_TDTM.run: line 111, column 1 Class.hed.TDTM_TriggerHandler.runClass: line 145, column 1 Class.hed.TDTM_TriggerHandler.run: line 75, column 1 Class.hed.TDTM_Global_API.run: line 61, column 1 Trigger.hed.TDTM_Contact: line 33, column 1: []"

**Details and Steps to Reproduce**
**Current Behavior:** 
When a Contact record's Name and Ownership is updated in the same time/context, a duplicate ID error pops up. 

**Expected Behavior:**
When a Contact record's Name and Ownership is updated in the same time/context, it should not throw an error. 

**Steps to Reproduce:** 
1. Created a Contact record 
2. Result: Account was created for the Contact record
3. Update the existing Contact's record Name & Ownership via data upload/execute anonymous/integration tools/etc. 
4. Result: The error below pops up below and the Contact record is not updated. 

"Line: 9, Column: 1
System.DmlException: Update failed. First exception on row 0 with id 0033i00000F1S6EAAV; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, hed.TDTM_Contact: execution of AfterUpdate caused by: System.ListException: Duplicate id in list: 0013i00000G7SQLAA3 Class.hed.TDTM_TriggerHandler.processDML: line 184, column 1 Class.hed.ACCT_IndividualAccounts_TDTM.handleUpdateProcessing: line 467, column 1 Class.hed.ACCT_IndividualAccounts_TDTM.handlesAfterInsertUpdate: line 277, column 1 Class.hed.ACCT_IndividualAccounts_TDTM.run: line 111, column 1 Class.hed.TDTM_TriggerHandler.runClass: line 145, column 1 Class.hed.TDTM_TriggerHandler.run: line 75, column 1 Class.hed.TDTM_Global_API.run: line 61, column 1 Trigger.hed.TDTM_Contact: line 33, column 1: []"

**Comment by aligeez** [comment]
**lurch: attach W-040020

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HtKUQA0" target="_blank">W-040020</a>
