### ISSUE TITLE
 Adding new picklist value to hed__Application_Status__c field on Application object

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/EDA#1136]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
There is no 'Admit with Conditions' value in the picklist 'Application Status' on Application Object.
 
* **What is the expected behavior?**
There should be 'Admit with Conditions' value in the picklist 'Application Status' Application Object.

* **What is the motivation / use case for changing the behavior?**
Need to track a new status

* **Acceptance Criteria**

  - **Given**: I am on Application's page layout
  - **When**: I click Application Status field
  - **Then**: I should be able to see 'Admit with Conditions' value

**Comment by skosgi1** [comment]
**lurch: attach W-040241

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HtkzQAC" target="_blank">W-040241</a>
