### ISSUE TITLE
Duplicate Contacts created when Lightning Sync is enabled

### ISSUE THREAD

**Issue by kschaefges** [SalesforceFoundation/EDA#1139]
* **Do you want to request a *feature* or report a *bug*?**
There's possibly a bug between the behavior of Lightning Sync for Outlook and the EDA Contact triggers. Customers are reporting duplicate contacts and accounts being created.

* **What is the current behavior?**
Duplicate Contacts and accounts are being created.

* **What is the expected behavior?**
The Lightning Sync should create contacts in Salesforce without duplication.

**Comment by xinnanlisf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HuY1QAK" target="_blank">W-040709</a>

**Comment by xinnanlisf** [comment]
@aligeez fyi

**Comment by aligeez** [comment]
This was determined to be a bug with Lightning Sync, not EDA. Closing.
