### ISSUE TITLE
Eda hed__Work_Address__c and hed__Relationship_Explanation__c deploy failure

### ISSUE THREAD

**Issue by SajithaDeivasikamani00** [SalesforceFoundation/EDA#1140]
While creating scratch or, the deployment is failing due to these two fields hed__Work_Address__c and hed__Relationship_Explanation__c.

Got the below error:
Contact.hed__Work_Address__c:
  Cannot modify managed object: entity=CustomFieldDefinition, component=00N2O000001BWbL, field=CalculatedFormula, state=installed: newValue='ENCODED:[treatNullAsNull]if( ISPICKVAL({!ID:00N2O000001BWbA},"Work"), if(ISBLANK({!ID:MailingStreet}) , "" , {!ID:MailingStreet} & ", ") & if(ISBLANK({!ID:MailingCity}) , "" , {!ID:MailingCity} & ", ") & if(ISBLANK({!ID:MailingState}) , "" , {!ID:MailingState} & " ") & if(ISBLANK({!ID:MailingPostalCode}) , "" , {!ID:MailingPostalCode}) & If(ISBLANK({!ID:MailingCountry} ) , "" , ", " & {!ID:MailingCountry}) , if(ISPICKVAL({!ID:00N2O000001BWbG},"Work"), if(ISBLANK({!ID:OtherStreet}) , "" , {!ID:OtherStreet} & ", ") & if(ISBLANK({!ID:OtherCity}) , "" , {!ID:Other

hed__Relationship__c.hed__Relationship_Explanation__c:
Cannot modify managed object: entity=CustomFieldDefinition, component=00N2O000001BWdp, field=CalculatedFormula, state=installed: newValue='ENCODED:TEXT({!ID:00N2O000001BWdo.Salutation}) + " " + {!ID:00N2O000001BWdo.FirstName} + " " + {!ID:00N2O000001BWdo.LastName} + " " + {!ID:$Label.hed__relationship_explanation_connector} + " " + TEXT({!ID:00N2O000001BWdk.Salutation}) + " " + {!ID:00N2O000001BWdk.FirstName} + " " + {!ID:00N2O000001BWdk.LastName} + "'s " + TEXT({!ID:00N2O000001BWds})', oldValue='ENCODED:TEXT({!ID:00N2O000001BWdo.Salutation}) + " " + {!ID:00N2O000001BWdo.FirstName} + " " + {!ID:00N2O000001BWdo.LastName} + " " + {!ID:$Label.hed__relationship_explanation_connector} + " " + TEXT({!ID:00N2O000001BWdk.Salutation}) + " " +

While deploying, the formula field has the same value which is there in the sandbox.

<img width="769" alt="heda_Error" src="https://user-images.githubusercontent.com/62692068/77625214-320a3380-6f69-11ea-8e6e-fcb4d17df1dc.PNG">

**Comment by jacebryan** [comment]
Hi @SajithaDeivasikamani00! Please post about this issue in the [Power of US Hub EDA Group](https://powerofus.force.com/s/group/0F980000000D6ujCAC/education-data-architecture) for transparency purposes. A member of our team can assist you there. I'll be closing this Issue now.
