### ISSUE TITLE
EDA Settings: When Enable Record Type Validation is true an error is thrown on Contact and Affiliation

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/EDA#1153]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
After Enable Record Type Validation is set to True in EDA Settings, I attempt to create a Contact/Affiliation and receive the following error message:

A validation rule is preventing the record from being processed. This could be from this record, or a related record being updated. VALIDATION MESSAGE: We can't save this record because of an Account record type error in Affiliation Mappings. Ask your administrator to verify that Account Record Types are correctly mapped to Contact Primary Affiliations.

* **What is the expected behavior?**
User should be able to create Contacts and Affiliaiton records even after enabling the record type validation.

**Comment by skosgi1** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HuXmQAK" target="_blank">W-040706</a>
