### ISSUE TITLE
EDA Settings available via Permission Set

### ISSUE THREAD

**Issue by kschaefges** [SalesforceFoundation/EDA#1158]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Admins for EDA are unable to access "EDA Settings" if they have the "Customize Application" permission enabled on a permission set. If this setting is enabled on a profile then they are able to access EDA. A customer expects that access can be granted using either a profile or a permission set.

* **What is the expected behavior?**
Even if the customize application permission is set via permission set, the user should be able to successfully access the EDA Settings.

In the class STG_Base_CTRL- lines 44-46, only the profile is checked for the customize application permission.
public STG_Base_CTRL() {
User user = [SELECT Profile.PermissionsCustomizeApplication FROM User where Id = :UserInfo.getUserId()]; 
this.hasPerm = user.Profile.PermissionsCustomizeApplication;
}

If we edit lines 45 & 46 to read:
PermissionSetAssignment psa = [SELECT Assignee.Id, Assignee.Name, PermissionSet.Id, PermissionSet.PermissionsCustomizeApplication, PermissionSet.isOwnedByProfile, PermissionSet.Profile.Name, PermissionSet.Label
FROM PermissionSetAssignment
WHERE Assignee.Id = :UserInfo.getUserId()];       
this.hasPerm = psa.PermissionSet.PermissionsCustomizeApplication;

The code will pull in the customize application permission regardless if it is on the profile or an assigned permission set.

**Comment by kschaefges** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HvA4QAK" target="_blank">W-040934</a>

**Comment by MatthewBlanski** [comment]
Tracking [W-7931280](https://gus.lightning.force.com/a07B0000008WuesIAC)

**Comment by kporray1** [comment]
This issue has been resolved.  (W-7931280)
