### ISSUE TITLE
hed.TDTM_Contact: data changed by trigger for field Email: invalid email address

### ISSUE THREAD

**Issue by EdwinFdoGarcia** [SalesforceFoundation/EDA#1162]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Bug
* **What is the current behavior?**

We have installed K-12 Architecture Kit from the Github repository.
the error appears when creating a new contact ** (Studen, Facultaty / Staff, Guardian) **
```
Review the errors on this page.
hed.TDTM_Contact: data changed by trigger for field Email: invalid email address: (value has been hidden)

```

<img width="1918" alt="Captura de Pantalla 2020-04-24 a la(s) 12 43 39 p  m" src="https://user-images.githubusercontent.com/35706123/80243467-e496ea00-862c-11ea-8ec8-3aa8a9db7705.png">

I have found a solution that fixes the error.
in EDA SETTINGS / Accounts and Contacts / disable: Disable Preferred Email enforcement
then Run Cleanup.
When creating a new contact the error stops appearing and creates the contact for me.

<img width="961" alt="Captura de Pantalla 2020-04-24 a la(s) 1 11 23 p  m" src="https://user-images.githubusercontent.com/35706123/80243617-2b84df80-862d-11ea-9b98-2118f3143c3a.png">

<img width="957" alt="Captura de Pantalla 2020-04-24 a la(s) 1 11 37 p  m" src="https://user-images.githubusercontent.com/35706123/80243621-2de73980-862d-11ea-8972-a30351879597.png">

**Comment by aligeez** [comment]
@jacebryan - Do we want to get this on the Hub first? Or do you want us to lurch it and queue up for investigation?

**Comment by EdwinFdoGarcia** [comment]
> @jacebryan - Do we want to get this on the Hub first? Or do you want us to lurch it and queue up for investigation?
hi @jacebryan I don't know how to answer these questions.
but if it is being presented at a general level, the decision must benefit the majority.
Thanks for being tempted to issus

**Comment by judisohn** [comment]
Hi @aligeez @EdwinFdoGarcia - @jacebryan was on PTO last week. For now, let's keep the conversation [on the Hub](https://powerofus.force.com/s/question/0D51E00005I942mSAB/k12-architecture-kit-hedtdtmcontact-data-changed-by-trigger-for-field-email-invalid-email-address) and re-open this should a bug be determined. On the surface, this appears to be "as designed" behavior for a contact imported without using the Preferred Email functionality.
