### ISSUE TITLE
[EDA] Prevent Deletion of Address Record if There are Associated Child Records

### ISSUE THREAD

**Issue by m-kinkade** [SalesforceFoundation/EDA#1163]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
When a user attempts to delete an Address record that is associated with child records, the system deletes the address record, leaving the child Contact and/or Account records intact with the Current Address field cleared.

* **What is the expected behavior?**
When a user attempts to delete an Address record that is associated with child records, the system will utilize a new custom setting field (Prevent Address Deletion) to determine whether to allow the deletion.  If selected, attempts to delete an Address record with associated child records will be blocked and an error message displayed to the user.  If unchecked, the functionality will remain the same as outlined in the current behavior section.

* **What is the motivation / use case for changing the behavior?**
From previous github requests and investigations of deletion of parent records with child records, it was determined that we need to implement the functionality to allow users the ability to control if an Address record with related child record can be deleted. 

* **Acceptance Criteria**

  - **Given**: The “Prevent Address Deletion” checkbox in Hierarchy Settings (Custom Setting) is unchecked.
  - **When**: A user clicks “Delete” button on an Address record that has child related records.
  - **Then**: The Address record is successfully deleted, no error message is displayed to the user and the child records are not deleted.

  - **Given**: The “Prevent Address Deletion” checkbox in Hierarchy Settings (Custom Setting) is checked.
  - **When**: A user clicks “Delete” button on an Address record that has child related records.
  - **Then**: An error message is displayed to the user and the user is unable to delete the Address record.

**Comment by m-kinkade** [comment]
**lurch: attach W-040721

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HuYzQAK" target="_blank">W-040721</a>
