### ISSUE TITLE
[EDA] Prevent Deletion of Course Record  if There are Associated Course Records

### ISSUE THREAD

**Issue by kdy618** [SalesforceFoundation/EDA#1164]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature
* **What is the current behavior?**
When a user attempts to delete a Course record that is associated with child records, the system deletes the Course record, leaving the child Course Offering or Plan Requirements orphaned.
* **What is the expected behavior?**
When a user attempts to delete a Course record that is associated with child records, the system will utilize a new custom setting field (Prevent Course Deletion) to determine whether to allow the deletion. If selected, attempts to delete a Course record with associated child records will be blocked and an error message displayed to the user. If unchecked, the functionality will remain the same as outlined in the current behavior section.
* **What is the motivation / use case for changing the behavior?**
Data integrity
* **Acceptance Criteria**

As a user, 
I need the ability to block or allow deletion of a Course record that has child related records. 

Given: The “Prevent Course Deletion” checkbox in Hierarchy Settings (Custom Setting) is unchecked.
When: A user clicks “Delete” button on a Course record that has child related records,
Then: the Course record is successfully deleted, no error message is displayed to the user and the child records are not deleted.

Given: The “Prevent Course Deletion” checkbox in Hierarchy Settings (Custom Setting) is checked.
When: A user clicks “Delete” button on a Course record that has child related records,
Then: an error message is displayed to the user and the user is unable to delete the Course record.

**Comment by kdy618** [comment]
**lurch: attach W-040727

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HuZTQA0" target="_blank">W-040727</a>
