### ISSUE TITLE
[EDA] Prevent Deletion of Test Record  if There are Associated Test Score Records

### ISSUE THREAD

**Issue by m-kinkade** [SalesforceFoundation/EDA#1170]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
When a user attempts to delete a Test record that is associated with child records (Test Score), the system deletes the Test record, leaving the child Test Score records intact with the Test field cleared.

* **What is the expected behavior?**
When a user attempts to delete a Test record that is associated with child records, the system will utilize a new custom setting field (Prevent Test Deletion) to determine whether to allow the deletion. If selected, attempts to delete a Test record with associated child records will be blocked and an error message displayed to the user. If unchecked, the functionality will remain the same as outlined in the current behavior section.

* **What is the motivation / use case for changing the behavior?**
From previous github requests and investigations of deletion of parent records with child records, it was determined that we need to implement the functionality to allow users the ability to control if a Test record with related child record can be deleted. 

* **Acceptance Criteria**

  - **Given**: The “Prevent Test Deletion” checkbox in Hierarchy Settings (Custom Setting) is unchecked.
  - **When**: A user clicks “Delete” button on a Test record that has child related records.
  - **Then**: The Test record is successfully deleted, no error message is displayed to the user and the child records are not deleted.

  - **Given**: The “Prevent Test Deletion” checkbox in Hierarchy Settings (Custom Setting) is checked.
  - **When**: A user clicks “Delete” button on a Test record that has child related records.
  - **Then**: An error message is displayed to the user and the user is unable to delete the Test record.

**Comment by m-kinkade** [comment]
**lurch: attach W-040732

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HuZsQAK" target="_blank">W-040732</a>
