### ISSUE TITLE
Remove K12 Attribute picklist values from EDA

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/EDA#1175]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
bug
* **What is the current behavior?**
Some Attribute picklist values in EDA are supposed to be added to K12 Kit.
* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
To ensure new EDA customers won't get K12 Attribute picklist values

**Comment by xinnanlisf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hZrpQAE" target="_blank">W-041222</a>

**Comment by MatthewBlanski** [comment]
EDA accepts K-12 picklist values since dropping the 'Higher' from its name.
