### ISSUE TITLE
Error when attempting to move the last contact out of a non-household or administrative account into a household account.

### ISSUE THREAD

**Issue by kschaefges** [SalesforceFoundation/EDA#1178]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Customers who have automatic HH renaming enabled in settings are experiencing errors when attempting to move the last contact out of a non-household or administrative account into a household account.

* **What is the expected behavior?**
The contact should be moved without error

**Steps to reproduce:**
Enable HH renaming in EDA settings
Create a Business Organization Account
Add a contact to that account
Edit the contact you just created to a new HH account
Click Save
You'll receive the following error: "Review the errors on this page. A required field is not set. This field could be from this record or a related record."

This is because the UTIL_Acct_Naming class is attempting to rename the Business Organization account and it has no additional contacts. Both account IDs are fed into the trigger and are therefore returned in the queryContacts method in lines 146-174. The dynamicSoql built in this method doesn't filter for whether or not the account record types match the household or administrative account record types.

In my scratch org example,
I created a Business Organization Account "Test Org" with an ID of "001P000001eXKTBIA4"
I added a contact "Jane Jones" to that "Test Org" account.
I created a new HH account "Jones HH" with an ID of "001P000001eXKUiIAO"
When I attempt to move Jane out of the "Test Org" account and into the "Jones HH" account, I get the error.

In the debug logs you can see that it has both account IDs included in the accIdsToRename
```
|VARIABLE_SCOPE_BEGIN|[127]|accIdsToRename|Set<Id>|true|false
|VARIABLE_ASSIGNMENT|[127]|accIdsToRename|["001P000001eXKUiIAO","001P000001eXKTBIA4"]
```
And we see that in line 172, both IDs are still returned for renaming processing.
```
|SOQL_EXECUTE_BEGIN|[172]|Aggregations:1|SELECT Id, RecordTypeId, (SELECT Id, AccountId,Account.RecordTypeID, Account.Primary_Contact__c, Account.Name,firstname, lastname, OwnerId, Salutation,MailingStreet, MailingCity, MailingState, MailingPostalCode, MailingCountry, MailingLatitude, MailingLongitude, OtherStreet, OtherCity, OtherState, OtherPostalCode, OtherCountry, OtherLatitude, OtherLongitude, Phone, Fax FROM Contacts WHERE Exclude_from_Household_Name__c != true AND Deceased__c != true) FROM Account WHERE Id IN :accIdsToRename
|SOQL_EXECUTE_END|[172]|Rows:2
|HEAP_ALLOCATE|[172]|Bytes:12
|HEAP_ALLOCATE|[172]|Bytes:350
|HEAP_ALLOCATE|[172]|Bytes:12
|VARIABLE_ASSIGNMENT|[172]|returnedContacts|[{"Id":"001P000001eXKTBIA4","RecordTypeId":"012P00000011f85IAA"},{"Id":"001P000001eXKUiIAO","RecordTypeId":"012P00000011f87IAA","Contacts":[{"AccountId":"001P000001eXKUiIAO","Id":"003P000001Mu2rgIAB","FirstName":"Jane","LastName":"Jones","OwnerId":"005P0000004d5OBIAY","Account":{"Id":"001P000001eXKUiIAO","RecordTypeId":"012P00000011f87IAA","Name":"Jones HH"}}]}]
```
Eventually, when the update DML runs, the following error occurs
`|EXCEPTION_THROWN|[139]|System.DmlException: Update failed. First exception on row 0 with id 001P000001eXKTBIA4; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [Name]: [Name]
`
Account ID "001P000001eXKTBIA4" shouldn't be renamed at all and should be eliminated from running through the process.

I tested this by editing line 169 to read "dynamicSoql += ' FROM Account WHERE Id IN :accIdsToRename AND (RecordTypeID = :hhAccountRecordTypeId OR RecordTypeID = :adminAccountRecordTypeId)';" and I was able to successfully save the changes to the record in the steps to reproduce listed above.

When re-running my test in my scratch org I see the following:

Both IDs are submitted to accIdsToRename
```
|VARIABLE_SCOPE_BEGIN|[127]|accIdsToRename|Set<Id>|true|false
|VARIABLE_ASSIGNMENT|[127]|accIdsToRename|["001P000001eXKUiIAO","001P000001eXKTBIA4"]|0x3274cd88
```
But only the HH record account is submitted for further processing in line 172.
```
|STATEMENT_EXECUTE|[172]
06:38:25.492 (2496713449)|HEAP_ALLOCATE|[172]|Bytes:584
06:38:25.492 (2497942409)|SOQL_EXECUTE_BEGIN|[172]|Aggregations:1|SELECT Id, RecordTypeId, (SELECT Id, AccountId,Account.RecordTypeID, Account.Primary_Contact__c, Account.Name,firstname, lastname, OwnerId, Salutation,MailingStreet, MailingCity, MailingState, MailingPostalCode, MailingCountry, MailingLatitude, MailingLongitude, OtherStreet, OtherCity, OtherState, OtherPostalCode, OtherCountry, OtherLatitude, OtherLongitude, Phone, Fax FROM Contacts WHERE Exclude_from_Household_Name__c != true AND Deceased__c != true) FROM Account WHERE Id IN :accIdsToRename AND (RecordTypeID = :hhAccountRecordTypeId OR RecordTypeID = :adminAccountRecordTypeId)
|SOQL_EXECUTE_END|[172]|Rows:1
|HEAP_ALLOCATE|[172]|Bytes:8
|HEAP_ALLOCATE|[172]|Bytes:287
|HEAP_ALLOCATE|[172]|Bytes:8
|VARIABLE_ASSIGNMENT|[172]|returnedContacts|[{"Id":"001P000001eXKUiIAO","RecordTypeId":"012P00000011f87IAA","Contacts":[{"Acco
```

**Comment by kschaefges** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hZw1QAE" target="_blank">W-041266</a>

**Comment by MatthewBlanski** [comment]
Tracking [W-7537627](https://gus.lightning.force.com/a07B0000007ofsqIAA)

**Comment by kporray1** [comment]
This issues is no longer being considered by the product team.  (W-7537627)
