### ISSUE TITLE
[EDA] : Add county fields to address

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/EDA#1188]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
feature
* **What is the current behavior?**
No field to store County data
* **What is the expected behavior?**
There should be fields in EDA to store County to addresses
* **What is the motivation / use case for changing the behavior?**

* **Acceptance Criteria**

  - **Given**: I am entering address
  - **When**: I try to enter the county information
  - **Then**: I should be able to add the data to the fields

**Comment by skosgi1** [comment]
**lurch: attach W-041323

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007ha1GQAQ" target="_blank">W-041323</a>
