### ISSUE TITLE
new field to store Language Details on Contact Language

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/EDA#1190]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
feature

* **What is the current behavior?**
no field to capture more details

* **What is the expected behavior?**
Need a new field to store 'Contact Details' on Contact Language object

* **What is the motivation / use case for changing the behavior?**
Capture data

* **Acceptance Criteria**

  - **Given**: I am on object manager page
  - **When**: I select 'Contact Language' 
  - **Then**: I should be able to see a new field 'Language Details'

**Comment by skosgi1** [comment]
**lurch: attach W-041325

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007ha1QQAQ" target="_blank">W-041325</a>

**Comment by dgamboni** [comment]
Note: Closed by PR #1189 1189
