### ISSUE TITLE
UTIL_ACCT_Naming is unable to determine Record Type ID when record creator does not have access to record types

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#1213]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**

When a LiveAgent chat is accepted within the Service Console, the system attempts to create the new Contact and Account. The new Contact creation fires the Trigger Handler ACCT_IndividualAccounts_TDTM. That Trigger Handler calls the UTIL_ACCT_Naming.cls to determine the AA and HH Account Record Type IDs. In this particular case, it is unable to determine the appropriate Record Type ID.

CCE believes the cause of this is due to the fact that the creator of the Contact/Account is “Automated Processor” who does not have access to the record types.

We tested this theory by:

- Changing the code on line 50 of UTIL_ACCT_Naming.cls from **private static ID adminAccountRecordTypeId = UTIL_Describe.getAdminAccRecTypeID();** to **private static ID adminAccountRecordTypeId = UTIL_CustomSettingsFacade.getSettings().Administrative_Account_Record_Type__c;**

- Changing the code on line 45 of UTIL_ACCT_Naming.cls from **private static ID hhAccountRecordTypeId = UTIL_Describe.getHhAccRecTypeID();** to **private static ID hhAccountRecordTypeId = UTIL_CustomSettingsFacade.getSettings().Household_Addresses_RecType__c;**

Upon accepting the LiveAgent chat within the Service Console both the AA Record Type ID and HH Record Type ID was determined and the correct Account Naming Format was set.

* **What is the expected behavior?**
When a LiveAgent chat is accepted within the Service Console, the system is able to create the new Contact and Account and have the correct Account Naming Format set.

* **What is the motivation / use case for changing the behavior?**
Making this change will respect the selection of record types customers enter into EDA Settings whether that be through LiveAgent chat or other solutions.

* **Is there a workaround?**
Customers can use the *Refresh All Administrative Names* feature in EDA Settings → System. Clicking this button renames ALL existing Administrative Account records to the format specified in Administrative Account Name Format. There are considerations (https://powerofus.force.com/s/article/EDA-Customize-Admin-and-HH-Acct-Names#ariaid-title6) around this feature that should be understood before proceeding forward.

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hasCQAQ" target="_blank">W-041735</a>

**Comment by xinnanlisf** [comment]
To check with the team and see if this has been covered by another GI

**Comment by MatthewBlanski** [comment]
Tracking [W-7629964](https://gus.lightning.force.com/a07B0000008PJHrIAO)

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.  (W-7629964)
