### ISSUE TITLE
[EDA] CA: Handle County Fields to Address Code (logic)

### ISSUE THREAD

**Issue by kdy618** [SalesforceFoundation/EDA#1217]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature
* **What is the current behavior?**
County is not supported in our current Address logic. 
* **What is the expected behavior?**
County should be supported in our current Address logic.

**Comment by xinnanlisf** [comment]
Closing this since it was merged to parent branch and not closed by github
