### ISSUE TITLE
[EDA] - Changing Contact on an Affiliation to a Contact having affiliation of same type causes multiple primary Affiliations of same type 

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/EDA#1219]
Appears to duplicate #556 

Feature or Bug? 
- Bug

What is the current / expected behavior?
- Current Issue : When Contact on an Affiliation is changed to a Contact having affiliation of same type or same account, then there are 2 Primary affiliations of same type.
- Expected Behavior : For each Contact, only ONE Affiliation can be marked Primary per Account Record Type

Steps to Reproduce:
Scenario 1:

1. Create 2 Educational Institution accounts ‘MIT’ and ‘Harvard’
2. Create 2 contacts ‘Chad’ and ‘Brad’
3. From ‘Chad’ create a primary affiliation to ‘MIT’ account
4. Confirm an affiliation is created between ‘MIT’ And ‘Chad’
5. Confirm ‘Primary Educational Institution’  on ‘Chad’ is populated with ‘MIT’ 
6. From ‘Brad’ create a primary affiliation to ‘Harvard’ account
7. Confirm an affiliation is created between ‘Account 2’ And ‘Brad’
8. Confirm ‘Primary Educational Institution’  on ‘Brad’ is populated with ‘Harvard’ 
9. Change the Contact on the affiliation created on Step 6 from ‘Brad’ to ‘Chad’
10. Confirm affiliation record is removed from Brad
11. Confirm ‘Primary Educational Institution’  on ‘Chad’ is populated with ‘Harvard’ 
12. Confirm the affiliation record is created on ‘Chad’
13. *Bug*: There are 2 primary affiliation records with same Affiliation type on ‘Chad’
14. Expected: Only one primary affiliation of same type should exist

Scenario 2:

1. Create 1 Educational Institution account ‘MIT’ 
2. Create 2 contacts ‘Chad’ and ‘Brad’
3. From ‘Chad’ create a primary affiliation to ‘MIT’ account
4. Confirm an affiliation is created between ‘Account 1’ And ‘Chad’
5. Confirm ‘Primary Educational Institution’  on ‘Chad’ is populated with ‘MIT’ 
6. From ‘Brad’ create a primary affiliation to ‘MIT’ account
7. Confirm an affiliation is created between ‘MIT’ And ‘Brad’
8. Confirm ‘Primary Educational Institution’  on ‘Brad’ is populated with ‘MIT’ 
9. Change the Contact on the affiliation created on Step 6 from ‘Brad’ to ‘Chad’
10. Confirm affiliation record is removed from Brad
11. Confirm ‘Primary Educational Institution’  on ‘Chad’ is still  ‘MIT’ 
12. Confirm the affiliation record is created on ‘Chad’
13. *Bug*: There are 2 primary affiliation records with same Affiliation type on ‘Chad’
14. Expected: Only one primary affiliation of same type should exist

Given a Contact
When I look at their list of All Affiliations 
I see only one record marked as primary for each record type

**Comment by skosgi1** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hbU0QAI" target="_blank">W-042054</a>

**Comment by MatthewBlanski** [comment]
Tracking [W-7931284](https://gus.lightning.force.com/a07B0000008WuewIAC)

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.  (W-7931284)
