### ISSUE TITLE
[EDA] - Primary Affiliation's lookup field API name is not found on AFFL_AccChange_TDTM, AFFL_ContactChange_TDTM & AFFL_MultiRecordType_TDTM when  'Account Record Type' &  'Contact Primary Affl Field' are both API names

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/EDA#1224]
Feature or Bug? 
- Bug

What is the current / expected behavior?
- Current Issue : When 'Contact Primary Affl Field' in EDA settings utilizes API name AFFL_AccChange_TDTM & AFFL_ContactChange_TDTM are unable to retrieve Primary Affiliation's lookup field API names in AFFL_AccChange_TDTM & AFFL_ContactChange_TDTM when  'Account Record Type' &  'Contact Primary Affl Field' as a result related Primary Affiliation fields are not updated in when an Affiliation's Account or Contact is changed.

- Expected Behavior : When utilizing API names in 'Contact Primary Affl Field' in EDA settings , updates to Account and Contact records on Affiliation record should reflect on Primary Affiliation fields on Contact.

Steps to Reproduce:
Scenario 1 (change of Account on Affiliation):

1. Create 2 education institution business accounts ‘Harvard’ and ‘MIT’
2. Create a contact 'student contact'
3. From ‘student contact’ related list create a primary affiliation to ‘Harvard’ account
4. Confirm an affiliation is created between ‘Harvard’ And ‘student contact’
5. Confirm ‘Primary Educational Institution’  on ‘student contact’ is populated with ‘Harvard’ 
6. Goto EDA settings -> Change ' Educational Institution' to '
hed__Primary_Educational_Institution__c' on 'Contact Primary Affl Field' column if you are using namespaced org. If not change it to 'Primary_Educational_Institution__c' . Save.
7 .Goto the affiliation created on  step 3 and change the account to 'MIT'. 
8. Confirm account is changed on Affiliation (as expected)
9. Bug: The 'Primary Educational Institution’  on ‘student contact’ is still ‘Harvard’ 
10. Expected: The 'Primary Educational Institution’  on ‘student contact’ should be updated with 'MIT'.

Scenario 2 (change of Contact on Affiliation):

1. Create 2 education institution business account ‘Harvard’ and ‘MIT’
2. Create 2 contacts ‘Chad’ and ‘Brad’
3. From ‘Chad’ create a primary affiliation to ‘Harvard’ account
4. Confirm an affiliation is created between ‘Harvard’ And ‘Chad’
5. Confirm ‘Primary Educational institution’  on ‘Chad’ is populated with ‘Harvard'
6. From ‘Brad’ create a primary affiliation to ‘MIT’ account
7. Confirm an affiliation is created between ‘MIT’ And ‘Brad’
8. Confirm ‘Primary Educational institution’  on ‘Brad’ is populated with ‘MIT'
9. Goto EDA settings -> Change ' Educational Institution' to '
hed__Primary_Educational_Institution__c' on 'Contact Primary Affl Field' column if you are using namespaced org. If not change it to 'Primary_Educational_Institution__c' . Save.
10. Now, go the primary affiliation  created on step3 and change the Contact from 'Chad' to 'Brad'
11. Confirm Contact on the Affilaiton is changed to 'Brad'.
12. Expected: ‘Primary Educational institution’ on 'Chad' should be cleared.
13. Bug: ‘Primary Educational institution’ on 'Chad' is still 'Harvard'
14. Bug: ‘Primary Educational institution’ on 'Brad' should be 'Harvard' but is still 'MIT'

Scenario 3 (Delete the Affiliation):

1. Create an education institution business account ‘Harvard’ 
2. Create a Contact ‘Chad’
3. From ‘Chad’ create a primary affiliation to ‘Harvard’ account
4. Confirm an affiliation is created between ‘Harvard’ And ‘Chad’
5. Confirm ‘Primary Educational institution’ on ‘Chad’ is populated with ‘Harvard’
6. Delete the primary affiliation created on  step 3
7. Expected: ‘Primary Educational institution’ on 'Chad' should be cleared.
8. Bug: ‘Primary Educational institution’ on 'Chad' is still 'Harvard'

Given a Contact
When I look at their list of All Primary Affiliations for a given Contact,  the primary Affiliation field on Contact should match the Accounts on the primary Affiliations.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hbePQAQ" target="_blank">W-042129</a>
