### ISSUE TITLE
[EDA] - CA Add Application related fields to Contact

### ISSUE THREAD

**Issue by m-kinkade** [SalesforceFoundation/EDA#1229]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Former Names, Citizenship Status and Date Deceased fields are currently unavailable on the Contact object.

* **What is the expected behavior?**
Former Names, Citizenship Status and Date Deceased fields are enabled for the Contact object.

* **What is the motivation / use case for changing the behavior?**
These fields on the Contact object will help shape a more complete 360 view of the individual and are characteristics that stay with the Contact for the duration of their education journey.

* **Acceptance Criteria**

  - **Given**: As a Salesforce admin at my educational institution 
  - **When**: I want to see every aspect of a Contact, informing a full 360 view of said Contact
  - **Then**: So that I can see what their former first name (first/middle/last) was, perhaps prior to marriage, so I can match transcripts or historical data. 

  - **Given**: As a Salesforce admin at my educational institution 
  - **When**: I want to see the citizenship status of my Contacts
  - **Then**: So that I can report to SEVIS (homeland security) per federal law, as well as manage any VISA sponsorship for my faculty and staff. 

  - **Given**: As a Salesforce admin at my educational institution 
  - **When**: I want to know the deceased date of any Contacts 
  - **Then**: So that I can avoid embarrassing marketing or communication mistakes addressing a deceased person, or so I can understand upcoming memorial dates and events.

**Comment by m-kinkade** [comment]
**lurch: attach W-042082

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hbYWQAY" target="_blank">W-042082</a>
