### ISSUE TITLE
COFF_Affiliation_TDTM.cls: a System.ListException: List index out of bounds error is thrown when updating primary faculty on 2 course offerings in the same transaction

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#1235]
**Issue Description**

Issue identified in a CCE case escalation on 6/26/2020

When you update primary faculty on two Course Offerings in the same transaction you receive a **System.ListException: List index out of bounds** error.

**What are the Steps to Reproduce?**

1. Create 3 Contacts (Contact 1, Contact 2 and Contact 3)
2. Create Course Offering A and set Primary Faculty to Contact 1
3. Create Course Offering B and set Primary Faculty to Contact 1

![image](https://user-images.githubusercontent.com/25934611/85881749-bb691600-b7a3-11ea-8c27-b2b982857f2d.png)

4. Update Course Offering B and set Primary Faculty too Contact 2
5. Verify Course Offering B has two Course Connections (Contact 2: Primary and Contact 1: Not Primary)

![image](https://user-images.githubusercontent.com/25934611/85881898-fff4b180-b7a3-11ea-849f-1ac991109702.png)

6. Create a list view on Course Offering that shows both Course Offering records and includes the Primary Faculty column

![image](https://user-images.githubusercontent.com/25934611/85882123-57931d00-b7a4-11ea-96c8-bc5986d9e239.png)

7. Edit both course offering records in the list view at the same time
8. Update Course Offering A and change Primary Faculty from Contact 1 to Contact 2
9. Update Course Offering B and change Primary Faculty from Contact 2 to Contact 3

![image](https://user-images.githubusercontent.com/25934611/85882697-5f9f8c80-b7a5-11ea-97c5-3125c851738f.png)

10. You should get an error

![image](https://user-images.githubusercontent.com/25934611/85882762-7b0a9780-b7a5-11ea-97cc-fd8c132d4961.png)

![image](https://user-images.githubusercontent.com/25934611/85882838-9b3a5680-b7a5-11ea-8b13-aed2987d0f11.png)

**What is the expected behavior?**
When you update primary faculty on two Course Offerings in the same transaction you don't receive an error.

**What is the actual behavior?**
When you update primary faculty on two Course Offerings in the same transaction you receive a System.ListException: List index out of bounds error.

**Cause (if known)**
The issue is happening in COFF_Affiliation_TDTM.cls. The code on line 380 is building a single set of affected Contact Ids and using that to query Course Connections across multiple Course Offerings....resulting in too many Course Connection records coming back. Update primary faculty on either Course Offering record individually and things work fine, but update primary on two Course Offerings in the same transaction and it hits the error. 

**Potential Solution (if known)**

NA

**Workarounds (in there are any)**

There are no known workarounds at this time.

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hc0LQAQ" target="_blank">W-042338</a>

**Comment by MatthewBlanski** [comment]
Tracking [W-7751204](https://gus.lightning.force.com/a07B0000008E2QUIA0)

**Comment by acrosman** [comment]
Is there a status update you all can give on this one? We're running into it with a client having trouble with a data import job.

**Comment by RobertReidBrownell** [comment]
Is there any status update that we have for this issue? We are currently running into this and are trying to assess if we should invest resources into a temporary fix on our end or if a fix might be coming down the pipeline. Thank you.

**Comment by jacebryan** [comment]
Hello @acrosman and @RobertReidBrownell - EDA is looking to have a fix for this issue in the Summer 22 release.

**Comment by kporray1** [comment]
This issue was fixed in the Summer '22 release.

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dl9WQAQ&title=list-index-out-of-bounds-error-is-thrown-when-updating-primary-faculty-on-2-course-offerings-in-the-same-transaction) in the Trailblazer Community for updates.
