### ISSUE TITLE
Add escape single quotes to a dynamic soql on tdtm_runnable

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/EDA#1243]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
feature
* **What is the current behavior?**
Currently TDTM_Filter.cls and TDTM_Runnable.cls class execute dynamic SOQL query on a String that doesn't escape single quotes. 

* **What is the expected behavior?**
Add escapeSingleQuotes() to the dynamic queries to protect against any potential SOQL injections.

* **What is the motivation / use case for changing the behavior?**
This makes our classes more secure to any possible security threats.

**Comment by skosgi1** [comment]
**lurch: attach W-042098

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hbawQAA" target="_blank">W-042098</a>
