### ISSUE TITLE
AFFL_AccRecordType_TDTM not behaving as described in EDA Class Data Dictionary

### ISSUE THREAD

**Issue by spinkelman** [SalesforceFoundation/EDA#1258]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Currently, the [AFFL_AccRecordType_TDTM](https://github.com/SalesforceFoundation/EDA/blob/master/src/classes/AFFL_AccRecordType_TDTM.cls) class is described in the EDA Data Dictionary as:
_When you change the record type of an Account, and it is a Primary Affiliation for a Contact, this class updates the Primary Affiliation to match the new record type. For example, if you change the Account's record type from Academic Program to Sports Organization, this class updates the Contact's Primary Sports Organization field. The class also creates a new Affiliation record for the Account designated as Primary. The previous Affiliation record remains, but Primary is deselected._

The class is not creating a new Affiliation record when the related Account type is changed. It is updating the existing Primary Affiliation record to reflect the new Account Type. 

* **What is the expected behavior?**
I'm expecting when a user changes the record type of an account, and it is listed as a Primary Affiliation for a Contact, the class creates a **new** Primary Affiliation record related to the Contact to reflect the new Primary Account Type and **updates** the existing record to have Primary deselected.

* **What is the motivation / use case for changing the behavior?**
It's not working as currently described in the Data Dictionary. 

* **Acceptance Criteria**

  - **Given**: An Account is listed as a Primary Affiliation for a Contact
  - **When**: I change the Account Record Type on the Account Record
  - **Then**: A new Affiliation record for the related Account and Contact for the Account designated as Primary and the previous Affiliation record remains and is updated with Primary being deselected.

How to Recreate:
[Demo Video](https://drive.google.com/file/d/1QznXQc6jxFlkC1DhzZw67DciyYZFnOr0/view?usp=sharing)

Setup:
Create Account Record: Name = Northeast Volleyball; Account Record Type = Sports Org.
Create Contact: Name = Suzie Student

1. Create a Primary Affiliation: Organization = Northeast Volleyball; Contact = Suzie Student; Primary = Checked
2. Verify that Primary Affiliation record is created and listed in Contact's related list and is marked as primary.
3. Update Account "Northeast Volleyball" to Business Organization Record Type.
4. View Contact "Suzie Student" Affiliations. 
   a. Verify that only one Affiliation record is present and it's updated to Account Record Type "Business Organization" and that the record is still marked as "Primary"
   b. Verify that no new Affiliation record is created.

**Comment by spinkelman** [comment]
**lurch: add

**Comment by dgamboni** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hdAHQAY" target="_blank">W-042844</a>

**Comment by kporray1** [comment]
A documentation update to [EDA Apex Class Descriptions](https://powerofus.force.com/s/article/EDA-Apex-Class-Descriptions) in August 2020 resolved this issue.
