### ISSUE TITLE
[EDA] Add Translation support for Primary Household on Contact to avoid error when Enable Record Type Validation is enabled

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#1262]
Issue was uncovered as part of responding to a [Hub post](https://powerofus.force.com/s/question/0D51E00005N8XVxSAN/anyone-having-a-bug-with-eda-in-french-or-any-other-language-than-english) on 7/28/2020.

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
I am not seeing the option to Translate Primary Household on Contact. Also - if I have Enable Record Type Validation enabled in EDA Settings I will receive the following error message due to this: We cannot save this record due to an Account record type error in Affiliate Mappings. Ask your administrator to verify that the account record types are correctly mapped to the Contact Primary Affiliations. (hed): [] (hed). If I disable this setting then I can create w/out error.

If I disable Enable Record Type Validation I am able to create a Contact.

That being said, I do see that Primary Household is part of Contact Translations (https://github.com/SalesforceFoundation/EDA/blob/master/src/objectTranslations/Contact-fr.objectTranslation) however in my Partner Enterprise Org (prod and SB) I am not seeing the option to Translate.

* **What is the expected behavior?**
I am able to add Field Label Translations on Contact for Primary Household
I am able to create a Contact with Enable Record Type Validation enabled

* **What is the motivation / use case for changing the behavior?**
EDA provides Field Label Translation on Contact for all EDA specific Primary fields except Primary Household. Also, customers will be able to utilize the Enable Record Type Validation feature in EDA settings.

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hd6ZQAQ" target="_blank">W-042825</a>

**Comment by jacebryan** [comment]
Closing this issue. 

Translation Support is provided for Primary Household. This can be found under Translation Workbench --> Override.

Also - PR #1252 will address the issue with Enable Record Type Validation.
