### ISSUE TITLE
Create new Education History Object

### ISSUE THREAD

**Issue by m-kinkade** [SalesforceFoundation/EDA#1266]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
The Education History object is new and therefore, there is no current functionality.

* **What is the expected behavior?**
Addition of this object will allow an Institution to follow a learner throughout their student journey and will play a key role in providing a 360 degree view of the learner. 

* **What is the motivation / use case for changing the behavior?**
The University application process relies heavily on thoroughly understanding an applicant’s education history; tracking every detail from post-secondary to other colleges as well as the education history of the applicant’s parents. Understanding the path that led an applicant to show interest in an educational institution as well as which paths most commonly resulted in an offer letter (and acceptance) are key data points in understanding and analyzing an educational institution’s recruitment funnel. 

    Education History, however, is also important beyond the recruiting and admission process. Once the applicant accepts admission to an educational institution and becomes a student, their education history up to that point is valuable for future conversations with their adviser. Once the student graduates and becomes alumni, knowing the entire education history of each individual can be important for targeted donation drives or mentorship programs. 

* **Acceptance Criteria**

  - **Given**: Visibility and access to any/all Education history records
  - **When**: A Contact in my EDA org has an Education History 
  - **Then**:  I can see a list of the student’s Education History showing me all the schools they attended, the start and end dates. Accessible in related lists and customizable page layouts. 

  - **Given**: Visibility and Access to any/all Education History Records
  - **When**: I go to a Contact’s Education History Related List
  - **Then**:  I can see a a learner's entrance and exit dates to the Institution, and the total time (duration) the Contact spent at the Institution.

  - **Given**: Visibility and Access to any/all Education History Records
  - **When**: Accessing the Contact’s Education History Record(s)
  - **Then**:  I can see the Contact's Class Rank, GPA Scale Reporting, Decile/Quintile/Quartile ranking method, Rank Weighted, Cumulative GPA, GPA Scale, and GPA Weighted for each institution listed.

  - **Given**: An Education History record on a Contact, I can go to the Account Lookup for the educational institution
  - **When**: It is available off Education History
  - **Then**:  Peruse the Account/account details like any other educational institution account in my org.

**Comment by m-kinkade** [comment]
**lurch: attach W-042078

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hbYCQAY" target="_blank">W-042078</a>
