### ISSUE TITLE
[EDA] Add Application Created Date field on Application Object

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/EDA#1268]
* **Do you want to request a *feature* or report a *bug*?**
feature

* **What is the expected behavior?**
A new field in EDA to capture "Application Created Date"

* **Acceptance Criteria**

  - **Given**: I am on a Application Object
  - **When**: I click a Fields
  - **Then**: I should be able to see "Application Created Date"

**Comment by skosgi1** [comment]
**lurch: attach W-042818

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hd4JQAQ" target="_blank">W-042818</a>
