### ISSUE TITLE
[EDA] - Add the field "School Code" to Account

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/EDA#1270]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
feature

* **What is the current behavior?**

* **What is the expected behavior?**
Need a field to capture "School Code"

* **What is the motivation / use case for changing the behavior?**

* **Acceptance Criteria**

  - **Given**: I am on Account Object
  - **When**: I click a Fields
  - **Then**: I should see a text field "School Code"

**Comment by skosgi1** [comment]
**lurch: attach W-042567

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hcOmQAI" target="_blank">W-042567</a>
