### ISSUE TITLE
[EDA] Remove Naming Exclusions Functionality

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/EDA#1273]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Changing whether or not a contact is Deceased will change the naming exclusions field.

* **What is the expected behavior?**
* When I create a contact that is marked as deceased, the contact should have no changes on the naming exclusions field.
* When I update a contact that to change whether or not it is deceased, the contact should have no changes on the naming exclusions field.

* **What is the motivation / use case for changing the behavior?**
Anyone wanting to use the same functionality should use the following fields: Exclude From Household Name, Exclude From Household Formal Greeting and Exclude From Household Informal Greeting.

* **Acceptance Criteria**

* When I create a contact that is marked as deceased, the contact should have no changes on the naming exclusions field.
* When I update a contact that to change whether or not it is deceased, the contact should have no changes on the naming exclusions field.

**Comment by skosgi1** [comment]
**lurch: attach W-042225

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hboAQAQ" target="_blank">W-042225</a>
