### ISSUE TITLE
CON_Email_TEST contains tests iterating over _all_ contacts in org: blocking changeset deployment as tests are long running

### ISSUE THREAD

**Issue by omairkhawaja** [SalesforceFoundation/EDA#1326]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

*Bug*

* **What is the current behavior?**
A changeset deployment to a Salesforce production org with > 110K contacts, fails validation due to the following tests in CON_Email_TEST identified as long running:
* testSingleEmailSmartSet
* testPrefferedEmailInsertNoStd
* testPrefferedEmailDeleting
* testLeadConversion
* testContactEmailBatch

Based on a very quick reading of the unit tests it appears that at least one or more of them are iterating over _all_ the contacts in the org, which is potentially the cause of the long execution time.

![image](https://user-images.githubusercontent.com/3627923/92843826-2beefe80-f3b3-11ea-9e9c-1e08a12151f3.png)

* **What is the expected behavior?**
The unit tests listed above should run to completion quickly (subsecond?) regardless of the number of contacts in the Salesforce org

* **What is the motivation / use case for changing the behavior?**
Allow changeset deployment

**Comment by jamesbsfdc** [comment]
Hi Omair

Thanks for raising this but we don't reply to issues on Github. If you have access to the Power of Us Hub could you login and post the issue there? Please use the EDA Chatter group in The Power of Us Hub.

Thanks

**Comment by omairkhawaja** [comment]
No worries @jamesbsfdc .  

There were two active Chatter groups in Powerofus:  EDA Release Announcements and EDA Compatibility Group .. and neither looked like the right place for the question so I posted a question https://powerofus.force.com/s/question/0D51E00005Q3UZPSA3
