### ISSUE TITLE
I cannot edit accounts, contacts or create affiliations when I change my user's language to Spanish

### ISSUE THREAD

**Issue by luisigualada** [SalesforceFoundation/EDA#1349]
I am using EDA in Spanish and have done some translations on EDA fields to fit my client's nomenclature.

I have created an Academic Program type account and it lets me create it correctly, but then when I go to edit it it always shows me the following error
![image](https://user-images.githubusercontent.com/4295350/94919091-223d5000-04b4-11eb-9b87-7cb1486910c2.png)

I have also created 3 record types on contact.
It allows me to create the contact without problems, but when I then go to the related lists and try to create a new affiliation and check the main affiliation check, it shows me the same error again, without allowing me to create the affiliation with the previously created account.
![image](https://user-images.githubusercontent.com/4295350/94919294-911aa900-04b4-11eb-91bc-074c0089ebb8.png)

This is how I have configured my affiliation assignments. I have copied in the main contact affiliation field the api name of the fields as you comment, but it still doesn't work.
![image](https://user-images.githubusercontent.com/4295350/94919558-f4a4d680-04b4-11eb-82ce-298eca082180.png)

Finally, I also have problems when I try to edit a contact that has already been created. It tells me that we cannot find the phone specified in Preferred Phone. Make sure you are entering the field label of an existing Custom Phone field.
I have all of the phone fields filled in and select from the picklist which is the preferred phone field and still get the error skipped.

I have noticed that when I change my user's language to English, all these problems I am talking about mysteriously disappear.
Can someone explain to me if all this is due to an EDA Bug or what I am configuring wrong?

![image](https://user-images.githubusercontent.com/4295350/94919785-52392300-04b5-11eb-84d4-922d13203b46.png)

I've already spent enough hours researching what the problem might be without any success.

Thanks in advance.

**Comment by jamesbsfdc** [comment]
Hi Luis

Sorry to hear you are encountering issues. Unfortunately we don't provide support via GitHub. Please could you create a new post for this on the EDA group in the Power of Us Hub: https://powerofus.force.com/s/group/0F980000000D6ujCAC/education-data-architecture

I'm closing this issue.

Thanks

**Comment by dgamboni** [comment]
FYI @jacebryan
