### ISSUE TITLE
Military in the description of "Military Background" (API Name hed__Military_Background__c) is spelled wrong

### ISSUE THREAD

**Issue by JasonFitzy** [SalesforceFoundation/EDA#1358]
* **What is the current behavior?**
There is a field called "Military Background" (API Name hed__Military_Background__c) that has a description: "Describe this person's miltary service, for example, the branch of the military, length of time in the miltary, date of discharge, etc."

* **What is the expected behavior?**
The phrase "miltary service" in the description is missing an 'i' for military. 

* **What is the motivation / use case for changing the behavior?**
It is a typo

**Comment by kporray1** [comment]
(W-8215945)

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dl9RQAQ&title=military-in-the-description-of-military-background-api-name-hed__military_background__c-is-spelled-wrong) in the Trailblazer Community for updates.
