### ISSUE TITLE
[EDA ] New Error Messages for  invalidContactFieldInAffiliationMapping and  invalidRecordTypeInAffiliationMapping

### ISSUE THREAD

**Issue by m-kinkade** [SalesforceFoundation/EDA#1405]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature
* **What is the current behavior?**
When affiliation mappings with invalid primary affiliation fields or record types exist and a user creates or updates a Contact invalid mapped fields populated, affiliations for the invalid mappings will not be generated, but the user will not be notified of the issue.

* **What is the expected behavior?**
When affiliation mappings with invalid primary affiliation fields or record types exist, affiliations will not be created and users will be notified of the mapping responsible for the error when attempting to create or update Contacts with invalid affiliation mappings.

* **What is the motivation / use case for changing the behavior?**
To improve the current user experience.

* **Acceptance Criteria**

  - **Given**: I have an affiliation mapping with an invalid mapped Contact Primary Affiliation field on Contact that is not an Account Lookup Field (such as a checkbox)
  - **When**: I try to create a contact with the mapped field populated
  - **Then**: I receive an error telling me which mapping is invalid.

  - **Given**: I have an affiliation mapping with an invalid mapped Account Record Type
  - **When**: I try to create a contact with the mapped field populated
  - **Then**: I receive an error telling me which mapping is invalid.

**Comment by m-kinkade** [comment]
[W-8449077](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008jE4eIAE/view)

**Comment by kporray1** [comment]
This issue was delivered in Summer '21 / SFDO Release 232
