### ISSUE TITLE
Broken link: EDA ApexDoc code documentation In README.md

### ISSUE THREAD

**Issue by mingworld** [SalesforceFoundation/EDA#1421]
Broken link in README.md
In Resources section there is a broken link: EDA ApexDoc code documentation (http://developer.salesforce.org/EDA/ApexDocumentation/). It redirects to https://engineering.salesforce.com/

Please fix. Thanks

**Comment by jacebryan** [comment]
Hi @mingworld! 

We don't openly accept Issues by the community. That being said, we do accept them in the [EDA Group located in the Power of US Hub](https://powerofus.force.com/s/group/0F980000000D6ujCAC/education-data-architecture). Please post your findings there for transparency and visibility within the EDA community. I will be closing this Issue now. 

Thank you!
