### ISSUE TITLE
hed.TDTM_Contact exception thrown when customizing the Administrative Account Name Format to include values outside of Id, FirstName, LastName, Salutation, AccountId

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#1542]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

[Issue identified in the Hub on 1/29/2021](https://powerofus.force.com/s/question/0D51E00004kViq1SAC/administrative-account-naming-format)

**Issue Description**

When customizing the Administrative Account Name Format to include values outside of Id, FirstName, LastName, Salutation, AccountId a hed.TDTM_Contact exception is throw.

**What are the Steps to Reproduce?**

Ensure the default Account Model = Administrative

1. In EDA Settings --> System change the Administrative Account Name Format to Other and assign the following format: {!LastName} {!{!FirstName}} {!MailingCity} Administrative Account
1. Click Save
1. Create a New Contact (First Name, Last Name, and add an Address that includes Mailing City)
1. Upon Contact creation notice that the Mailing City is not included in the Account Name
1.Edit the Contact you just created and change the Last Name to something else.
1. Click Save
1. You will see the following error message:

![AccountNamingFormatError](https://user-images.githubusercontent.com/25934611/106328009-b17d2900-6244-11eb-894f-e904ebc6a3b1.png)

**What is the expected behavior?**

No error appears when attempting to save an edited record that includes values outside of Id, FirstName, LastName, Salutation, AccountId

**What is the actual behavior?**

An error appears when attempting to save an edited record that includes values outside of Id, FirstName, LastName, Salutation, AccountId

**Per Matthew Blanksi on 1/29/2021:**

Upon Insert we support the entire list for Administrative Account: Id, FirstName, LastName, Salutation, AccountId, Account.RecordTypeID, Account.Primary_Contact__c, Account.Name, firstname, lastname, OwnerId, Salutation, MailingStreet, MailingCity, MailingState, MailingPostalCode, MailingCountry, MailingLatitude, MailingLongitude, OtherStreet, OtherCity, OtherState, OtherPostalCode, OtherCountry, OtherLatitude, OtherLongitude, Phone, Fax)
Upon update for Administrative Accounts we only support: Id, FirstName, LastName, Salutation, AccountId.

**Workarounds (in there are any)**

Do not reference any other fields other than FirstName, LastName, Salutation.

**Comment by jacebryan** [comment]
Please see GUS W-8828132

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.  (W-8828132)

**Comment by mcozzi2904** [comment]
Hi [kporray1], I have the same issue as jacebryan. How can I see your solution?
Thanks in advance,
