### ISSUE TITLE
Empty Auto-Create values in EDA Settings causes a System.NullPointerException:error when attempting to create a Contact or convert a Lead.

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#1757]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

Issue Description
Empty Auto-Create values causes a System.NullPointerException:error when attempting to create a Contact or convert a Lead.

Error when creating a new Contact: hed.TDTM_Contact: execution of AfterInsert caused by: System.NullPointerException: Attempt to de-reference a null object (hed)

Error when converting a Lead to Contact: There was an error converting the lead. Please resolve the following error and try again: hed.TDTM_Contact: execution of AfterInsert caused by: System.NullPointerException: Attempt to de-reference a null object Class.hed.UTIL_CustomSettingsFacade.getAutoCreateSettingsForContact: line 72, column 1 Class.hed.RelAutoCreateSettingsMapper.getContactMappingModelsFromSettings: line 79, column 1 Class.hed.REL_Relationships_Con_TDTM.handleAfterInsert: line 179, column 1 Class.hed.REL_Relationships_Con_TDTM.run: line 62, column 1 Class.hed.TDTM_TriggerHandler.runClass: line 145, column 1 Class.hed.TDTM_TriggerHandler.run: line 75, column 1 Class.hed.TDTM_Global_API.run: line 61, column 1 Trigger.hed.TDTM_Contact: line 33, column 1

What are the Steps to Reproduce?

- Log into EDA
- Click on EDA Settings
- Click on Relationships --> Autocreation
- Add a new Autocreation (use 'Test' for all values entered) and click Add Setting
- Click Edit and remove all values (don't use the trash can!) and then Save. 
- While it may look like there is nothing there, in actuality, if you click Edit again you will see the Auto-Create boxes with empty values.
- Attempt to create a Contact and you will see the following error: hed.TDTM_Contact: execution of AfterInsert caused by: System.NullPointerException: Attempt to de-reference a null object (hed)
- Attempt to convert a Lead and you will see the following error: There was an error converting the lead. Please resolve the following error and try again: hed.TDTM_Contact: execution of AfterInsert caused by: System.NullPointerException: Attempt to de-reference a null object Class.hed.UTIL_CustomSettingsFacade.getAutoCreateSettingsForContact: line 72, column 1 Class.hed.RelAutoCreateSettingsMapper.getContactMappingModelsFromSettings: line 79, column 1 Class.hed.REL_Relationships_Con_TDTM.handleAfterInsert: line 179, column 1 Class.hed.REL_Relationships_Con_TDTM.run: line 62, column 1 Class.hed.TDTM_TriggerHandler.runClass: line 145, column 1 Class.hed.TDTM_TriggerHandler.run: line 75, column 1 Class.hed.TDTM_Global_API.run: line 61, column 1 Trigger.hed.TDTM_Contact: line 33, column 1

Note: When performing a data import of a single Contact (First Name, Last Name) even after I removed the empty auto-create I ran into the following error:

hed.TDTM_Contact: execution of AfterInsertcaused by: System.NullPointerException: Attempt to de-reference a null objectClass.hed.UTIL_CustomSettingsFacade.getAutoCreateSettingsForContact: line 72, column 1Class.hed.RelAutoCreateSettingsMapper.getContactMappingModelsFromSettings: line 79, column 1Class.hed.REL_Relationships_Con_TDTM.handleAfterInsert: line 179, column 1Class.hed.REL_Relationships_Con_TDTM.run: line 62, column 1Class.hed.TDTM_TriggerHandler.runClass: line 145, column 1Class.hed.TDTM_TriggerHandler.run: line 75, column 1Class.hed.TDTM_Global_API.run: line 61, column 1Trigger.hed.TDTM_Contact: line 33, column 1"

I do not have any issue manually creating a Contact. It seems as if the issue is persisting for data imports.

What is the expected behavior?
I am unable to save an empty auto-create setting

What is the actual behavior?
I am able to save an empty auto-create setting

Workarounds (in there are any)
- If you are running into these types of errors you will need to go into your Recycle Bin and clear out any records with the Type 'Relationship Auto-Create'.

**Comment by jacebryan** [comment]
Tracking W-9287386

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.  (W-9287386)
