### ISSUE TITLE
Incomplete Auto-Create records in Custom Settings causes a System.NullPointerException:error when attempting to create/edit a Contact.

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#1762]
Issue Description
Incomplete Auto-Create records in Custom Settings causes a System.NullPointerException:error when attempting to create a Contact.

What are the Steps to Reproduce?

- Log into EDA
- Click on EDA Settings
- Click on Relationships --> Autocreation
- Add a new Autocreation (use 'Test' for all values entered) and click Add Setting
- Confirm you are able to Create a Contact
- Go to Setup --> Custom Settings --> and click on Manager next to Relationship Auto-Create
- Click edit next to the Relationship Auto-Create record
- Remove values from all fields except for the Name field and click Save
- Attempt to Create a new Contact and you should see the following error:

hed.TDTM_Contact: execution of AfterInsert caused by: System.NullPointerException: Attempt to de-reference a null object (hed)

- Go to EDA Settings --> Relationships -> Autocreation
- Notice the Auto-Create setting record you created earlier is now gone
- Click Edit and you will see that the record still exists except all values are empty
- Go to Setup --> Custom Settings --> and click on Manager next to Relationship Auto-Create
- Notice the Relationship Auto-Create record still exists because the Name field still has a value

Please also see Github Issue: https://github.com/SalesforceFoundation/EDA/issues/1757

What is the expected behavior?
Auto-Create records in Custom Settings should include a mapping of the Name value back to EDA Settings.

What is the actual behavior?
Auto-Create records in Custom Settings do not include a mapping of the Name value back to EDA Settings.

Workarounds (in there are any)
Option 1:
- Go to EDA Settings --> Relationships -> Autocreation
- Click Edit
- Click the Trash can next to any values that appear as empty. Doing so will remove the record from Custom Settings.

**Comment by jacebryan** [comment]
Tracking W-9298654

**Comment by ceiroa** [comment]
Never-ing.
