### ISSUE TITLE
TDTM does not respect namespacing on objects & fields

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#1857]
**Feature or bug?**
Bug

**What is the current behavior?**
If a user has an object and EDA introduces TDTM for its own object with the same name as the end users object it will cause an error. Users are forced to turn off EDA's TDTM record or migrate to EDA's object

**What is the expected behavior?**
TDTM should be able to recognize that Object_Name_c is different from hed_Object_Name_c and when EDA introduces

**What is the motivation / use case for changing the behavior?**
TDTM should be able to respect namespacing on objects & fields

**Steps to reproduce:**

- Create a Custom Object that EDA already provides (ex: Application_Custom_Object__c)
- Create a Custom Trigger for the Custom Object (ex: TDTM_Application_Custom_Object_Trigger)
- Interact with the Custom Object to fire the Custom Trigger
- Notice that EDA's TDTM specific Trigger for that object (ex: TDTM_Application) is unable to differentiate between the HED TDTM framework and the custom Trigger.

**Work Around (using the example above):**
Users will need to turn off EDA's TDTM record or Migrate to EDA's object

**Comment by jacebryan** [comment]
Tracking W-9667534

**Comment by ceiroa** [comment]
Never-ing. This is how the platform works. I believe we've documented it.
