### ISSUE TITLE
Error Notifier: No LIMIT on Error SOQL Query Can Result In 50,000 Row Limit or Heap Size Errors

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/EDA#1881]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Customers with large volume of Error records are at risk of heap size errors or the 50,000 row limit error when the EDA Error Notifier runs.

StackTrace from Heap Size Error:
```Developer script exception from {Customer} : 'hed.ERR_Notifier' for job id '707xxxxxxxxxxxx' : Apex heap size too large: 13498444
ExtendedMessage: Apex script unhandled exception by user/organization: 005xxxxxxxxxxxx/00Dxxxxxxxxxxxx
Failed to invoke future method 'private static void sendErrorQueueEmailNotificationFuture(List<String>)' on class 'hed.ERR_Notifier' for job id '707xxxxxxxxxxxx'
caused by: System.LimitException: Apex heap size too large: 13498444
External entry point
Class.hed.ERR_Notifier.sendErrorQueueEmailNotification: line 130, column 1
Class.hed.ERR_Notifier.sendErrorQueueEmailNotificationFuture: line 115, column 1
```

### Root Cause

When ERR_Notifier's sendErrorQueueEmailNotification() method is called, we run a SOQL query to gather all Error__c records where Email_Sent__c = false. If this is > 50,000 records, an error is thrown (again) and the notification isn't actually sent. Likewise, if a customer has thousands of Error records not yet sent and their Full_Message__c field is lengthy, this can result in heap size errors.

### Steps to Repeat in a Scratch Org:

- Ensure Education Cloud Settings are set to email All Sys Admins.
- Create 50,001 Error__c records in an EDA org.
- Verify that when the Error Notifier runs, there is a 50K row error for the job in Setup --> Apex Jobs.

### Workaround

Typically, we would suggest that the customer fixes the issue(s) that caused all of the Error records to be created in the first place. And then start either deleting some of the older Error records or mark Email_Sent__c to TRUE so that they are excluded from the query going forward.

### Product Recommendations
Place a limit on records being pulled into ERR_Notifier (total records and/or time-based).

**Comment by jesslopez-sf** [comment]
W-10003846

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dl9MQAQ&title=error-notifier-no-limit-on-error-soql-query-can-result-in-50-000-row-limit-or-heap-size-errors) in the Trailblazer Community for updates.
