### ISSUE TITLE
Standard Email field is not excluded from the translation of Preferred Email

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#1897]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Unless a customer clears out all email fields AND sets the Preferred Email value to the translated version of 'None' then the Standard Email field label is set as the Preferred Email picklist value in non-english language orgs.

* **What is the expected behavior?**
The Standard email field is excluded from translations associated to Preferred Email.

* **What is the motivation / use case for changing the behavior?**
This localization issue impacts customers working in non-english language orgs and can cause them to encounter errors as well as confusion working in EDA.

* **Steps to reproduce:**

Using Spanish language as an example:

1.  Verify Translation Workbench is enabled and that the Spanish language is active.
1. Verify Preferred Email is enabled in EDA Settings
1. In Translation Workbench select Translate and verify that the picklist values for Preferred Email have been translated.
1. Create a Contact and enter a value into the University Email field.
1. Notice that the Preferred Email is now set to 'University Email' AND that the standard email field is populated with the University Email email address.
1. Click on View Profile --> Settings --> Language & Time Zone and change Language from English to Espanol. Click Save.
1. Navigate back to the Contact record you created and confirm that you see the translated picklist value for Preferred Email
ex: Correo electrónico de la universidad
1. Edit the Preferred Email field and select the value of '--Ninguno--' and click Save.
1. You will encounter a translation error that basically indicates: Select a value for E-mail preference.
1. Clear out the value of the University Email field and click Save
1. Notice that the translated value for the Standard Email field is now the value set for Preferred Email. (i.e. 'Correo electrónico')
1. Clear out the value for the Standard Email field and set the Preferred Email field to the value of '--Ninguno--' and click Save.
1. The Preferred Email field value clears out and works as expected

* **Workaround:**
1. Keep Preferred Email enabled AND clear out the values of all email fields, then set the Preferred Email value to '--Ninguno--' and click Save. Doing so will clear out the value of Preferred Email.
1. Disable Preferred Email (least recommended approach).

**Comment by jacebryan** [comment]
See W-10150836

**Comment by kporray1** [comment]
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dl9HQAQ&title=standard-email-field-is-not-excluded-from-the-translation-of-preferred-email) in the Trailblazer Community for updates.
