### ISSUE TITLE
Bug:  All unit test DML is forced to run with 4 dozen "EDA default" hed__Trigger_Handler__c records existing.

### ISSUE THREAD

**Issue by kkgthb** [SalesforceFoundation/EDA#1954]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**

    Bug

* **What is the current behavior?**

    All DML in all unit tests run in any org with EDA installed is executed with EDA's 4 dozen "default records" inserted into the `hed__Trigger_Handler__c` table, rather than 0 as would be expected of any data table found during a unit test that did not explicitly flag itself `SeeAllData=true`.

    See [https://github.com/kkgthb/EDA-Unit-Test-Bug](https://github.com/kkgthb/EDA-Unit-Test-Bug) for a CumulusCI-deployable codebase that can be used to reproduce this bug.

* **What is the expected behavior?**

    There should be no data in any object during a unit test unless the Apex code of the unit test explicitly requests it to be present.

    Unit tests are supposed to be blank slates, data-wise.  That's what every Salesforce developer training ever has said to write code with an expectation of.

* **What is the motivation / use case for changing the behavior?**

    It's a bug, and makes it impossible to write unit tests that reflect the actual business logic of an educational institution's specifically configured installation of EDA _(such as only having certain trigger handlers that shipped with EDA -- or even none of them -- enabled)_.

    Worse yet, it completely grinds development work to a halt when the educational institution needs to develop Apex with their org configured _(for institution-specific business reasons)_ in a way that makes any **active** EDA-delivered trigger handlers error out.

* **Acceptance Criteria**

  - **Given**: I am a developer
  - **When**: I write a unit test without `SeeAllData=true` in it, like:
    ```java
    @isTest
    public class A_Unit_Test {
        static testMethod void runTest() {
            Contact c1 = new Contact(LastName='C1');
            Contact c2 = new Contact(LastName='C2');
            INSERT new List<Contact>{c1, c2};
        }
    }
    ```
  - **Then**: The `hed__Trigger_Handler__c` table should be empty when my unit test executes DML, exactly like every other table in the org should be empty.

Thanks all for an otherwise smooth and great product, and happy new year!

**Comment by judisohn** [comment]
@kkgthb Thanks for reporting. However, we would prefer that you create a [support case](https://powerofus.force.com/s/article/SFDO-CS-Create-a-Tech-Support-Case) instead of posting here. That way, teams can ask questions and get access to environments where this was replicated. Thanks.
