### ISSUE TITLE
Create Lightning Component that displays all Affiliations and Relationships of a student

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#215]
Ideally configurable, so it displays only relationships, or only affiliations, or both. Small widget that can be put in the home page, or in a sidebar, etc.

**Comment by ceiroa** [comment]
**lurch: attach W-009676

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003Ovr3AAC" target="_blank">W-009676</a>

**Comment by MatthewBlanski** [comment]
Performing repo cleanup. This is no longer in our backlog.
