### ISSUE TITLE
Use setting to determine if Account owner should be changed

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#221]
Method "updateOwners" in ACCT_IndividualAccounts_TDTM updates the Account owner if it's a Household or Administrative Account. It should be reading from a setting instead why types of Accounts need this.

**Comment by ceiroa** [comment]
**lurch: attach W-009780

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003Qep4AAC" target="_blank">W-009780</a>

**Comment by kporray1** [comment]
This issue was resolved in December 2019.
