### ISSUE TITLE
Running tests after installation failures

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#252]
Original Chatter thread: https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000007BBkM&tab=sfdc.ProfilePlatformFeed&fId=0D58000002iNuAZ&s1oid=00D00000000hWLM
## Comments from Dan Vega:
1. The individual accounts test failures occur when the default record type is selected to be one of the HEDA types. Although the instructions (https://powerofus.force.com/articles/Resource/Install-and-Configure-the-Higher-Education-Data-Architecture-HEDA) call for selecting "Adminsistrative" as default, this caused test failures. To work around, I created a new record type (non HEDA) and selected that as the default Account record type for the SysAdmin profile. Suggested code fix: set the account record type to a type which is known to have the behavior testing for. Suggested documentation fix: recommend non-HEDA default record type for profile.
2. The Addresses tests failed due to a naming collision between the name of the batch/scheduled job process in the test and the one on the org. When the test ran, it queries the jobs and checks "how many times run". On initial install, this is 0 (test passes this step). Later this test fails as seasonal address update job has been running. The workaround: delete the scheduled job running on the org for seasonal address update. Suggested code fix: query for the exact job in the test.
3. The "List has no rows" error was caused by the tests which queried for the 'COO' role on the org. Since my org doesn't have this role, it would return no records and the test would throw an exception. There is an assumption that this role will be present in the org. The workaround: Add the role 'COO' to the org. Suggested code fix: don't assume the 'COO' role is present in the org.
4. Although I didn't show the duplicate errors that I had earlier, for completeness, I suggest de-activating duplicate rules for test passing success.

I was able to successfully deploy/undeploy the HEDA unmanaged package to do this debugging and I'm thankful that it was as easy as it was.

With all of the tests now passing this will move along in our development process.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003oKpTAAU" target="_blank">W-010485</a>

**Comment by vegad** [comment]
Heppy to help.  Just let me know.

**Comment by ceiroa** [comment]
1 --> Shouldn't happen; the tests set their own default record type. Whatever value is stored in the settings shouldn't affect them. @vegad, if you are interested in digging a bit more into this please let us know. It'd be of great help. Otherwise I can take a look at it.

2 -->  Makes sense. We should look into it. Again @vegad, it you are interested in looking into this as well (and maybe even sending a pull request!), we'd be more than happy to help you getting the change in.

3 --> Role is a required field when creating a new user. Since COO is a role that is present by default in all orgs, it seems like a reasonable assumption to continue using it.

4 --> We were also tracking this in #190. It seems like platform is going ahead with having these enabled by default. We should add information about this in the installation notes (https://powerofus.force.com/articles/Resource/Install-and-Configure-the-Higher-Education-Data-Architecture-HEDA). @daveperry / @jvarese

**Comment by ceiroa** [comment]
Actually, regarding item 4, it seems like a better idea to implement the change @tet3 suggests in #190. What do you think, @kbromer?

**Comment by ceiroa** [comment]
Replacement code for 3: https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/UTIL_UnitTestData_TEST.cls#L269

**Comment by kbromer** [comment]
For the purposes of tests only, yeah, I think @tet3's idea is a good one

**Comment by ceiroa** [comment]
I have created issues for each separate item. Closing this one.

**Comment by aligeez** [comment]
Reopening issue for further investigation. @ceiroa

**Comment by MatthewBlanski** [comment]
Performing repo cleanup. Test failures have been cleaned up for a significant period of time.
