### ISSUE TITLE
Replace JS confirm dialogs with Lightning component

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#258]
When running Lightning CLI (https://developer.salesforce.com/docs/atlas.en-us.202.0.lightning.meta/lightning/cli_intro.htm) against HEDA we get error notifications regarding the confirm dialogs. However at of right now there isn't a Lightning component available to replace it with.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003oxy6AAA" target="_blank">W-010548</a>

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.
