### ISSUE TITLE
Have settings page check the profile permissions on save

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#270]
So only sysadmins can save changes to the settings page. Non sysadmins shouldn't even have access to the tab, but we should double-check that the user's profile has the permissions, just in case sysadmin forgot to hide tab from all users.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003qFMdAAM" target="_blank">W-010654</a>

**Comment by kporray1** [comment]
This issue was fixed in Jan 2017 and will be closed.
