### ISSUE TITLE
Object field in New Auto-Create Settings should be a drop-down

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#278]
If the only valid values are Contact and CampaignMember, this should be a drop-down. (If that's not the case, and any other objects can be used, then the text needs to be updated.)

If Object is a dropdown, then Field should also be a dropdown (that shows only applicable fields of the selected object).

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003vnRAAAY" target="_blank">W-010731</a>

**Comment by MatthewBlanski** [comment]
Fixed with separate lists and modals in the new EDA settings in our Summer release.
