### ISSUE TITLE
Build.xml should assigned unpackaged Account record types to profile

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#309]
This would avoid browser tests hitting https://github.com/SalesforceFoundation/HEDAP/issues/280.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by ceiroa** [comment]
fyi, @chrismcmahon

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003uV6oAAE" target="_blank">W-011213</a>

**Comment by chrismcmahon** [comment]
I'm not sure this addresses the error when attempting to Save of 

Something has gone wrong. Action failed: hed$CMP_RecTypes_Dropdown$controller$saveSetting [TypeError: recTypes is null] Failing descriptor: {hed$CMP_RecTypes_Dropdown$controller$saveSetting}. Please try again. 

Save does not work after getting this error.

**Comment by ceiroa** [comment]
@chrismcmahon Take a look at the referenced ticket.

**Comment by robertbwatson** [comment]
Closing because the associated WI was closed.
