### ISSUE TITLE
Import UTIL_RecordTypes from NPSP

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#310]
Class https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/UTIL_RecordTypes.cls would be very useful in HEDA, specially as functionality to expose to packages built on top of HEDA.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003uV6tAAE" target="_blank">W-011214</a>

**Comment by MatthewBlanski** [comment]
This class no longer exists.
