### ISSUE TITLE
Course Connection allows duplicate records

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/EDA#313]
Suggest that Course Connection allow only one record of each type Student and Faculty per Contact per Course Offering. 

Having the same Student or the same Faculty in the same Course Offering more than once could create problems for users. 

I am not certain if we should allow the same Contact to be both Faculty and Student for a single Course Offering.

**Comment by ceiroa** [comment]
Sounds reasonable. I'll add it to AA and ask Jason Belland about it.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003uV8pAAE" target="_blank">W-011236</a>

**Comment by kporray1** [comment]
Please post this on the [Idea Exchange](https://ideas.salesforce.com/s/post) to raise visibility and get it prioritized.
