### ISSUE TITLE
Contacts Merge

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#318]
Ideally, we would provide similar functionality for merging contacts in NPSP. However, that's very complex. We should identify the root of the issue. Does it have to do with not having cascade delete from Contacts to their children? Would providing optional cascade deletes for certain objects meet the basic requirements?

**Comment by ceiroa** [comment]
**lurch: attach W-011359

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000002w26vAAA" target="_blank">W-011359</a>

**Comment by daveperry** [comment]
We should review the doc from UM for more info and review the objects we are concerned with. I don't expect the complexity of a HEDA merge to be that of the NPSP merge.

**Comment by ceiroa** [comment]
We have agreed NOT to provide HEDA-specific merge functionality. Details at https://docs.google.com/document/d/1ZwaLBulfbaDknlWmqvIrFADueZdxS7yFfe9APrM6TfU/.

**Comment by jacebryan** [comment]
@davidjray - please reopen this Issue per our discussion today.

**Comment by jacebryan** [comment]
Power of US Idea Owner: [Christine Gorman](https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000006szkEAAQ&tab=sfdc.ProfilePlatformOverview)
[Power of US Idea](https://powerofus.force.com/hub-ideas/1036)

**Enhancement Request**: With each Contact in its own Administrative Account, the familiar "Merge Contact" button is a pain to use, requiring the following steps:

1. Merge the Accounts
2. Merge the Contact

Can we have a tab like the NPSP "Merge Contact" tab to do this more easily? Or is there a simpler method I am missing? Here is a link to the NPSP "Merge Contact" documentation: https://powerofus.force.com/articles/Resource/NPSP-Merging-Contacts

**Requirements:** 

- Ability to Merge Contacts in HEDA via a tab
- Ability to search duplicate contacts by name
- Ability to select up to 3 contacts for merging
- Ability to select a Master Record which determines the Account record the Contact will be associated with after the merge
- Ability to select fields from up to 3 contact records that will be included in the final merge
- Merging would relate child records for all of the merged Contacts to the master Contact

**Comment by kporray1** [comment]
This GitHub Issue will be closed; follow this [Idea in the Trailblazer Community ](https://ideas.salesforce.com/s/idea/a0B8W00000Gdk20UAB/merging-contacts-tab) for updates.
