### ISSUE TITLE
Investigate using Custom Metadata Types for the Relationship Types and Reciprocal Relationship Settings

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#324]
A user in the HUB thought that by editing the Reciprocal Relationship Settings list he was manipulating the Relationship Types picklist, which is a reasonable assumption to make: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000D6uj&fId=0D580000030EaCr

Maybe using CMTs we could keep the picklist and the reciprocal settings somehow tied together.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004FvVSAA0" target="_blank">W-017053</a>

**Comment by kporray1** [comment]
See Manage Relationships Settings [https://powerofus.force.com/s/article/NPSP-Manage-Relationships-Settings](url) for instructions on how to update the Reciprocal Relationships Settings.  This issue will be closed.
