### ISSUE TITLE
Add generic cascade deletion trigger handler?

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#350]
Like it's been recently added to NPSP: https://github.com/SalesforceFoundation/Cumulus/pull/2400/files

This could potentially help with items like [W-009453](https://foundation--agf.na6.visual.force.com/apex/adm_userstorydetail?id=a2x800000002BYHAA2&sfdc.override=1), and other similar ones.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004Ii6NAAS" target="_blank">W-017217</a>

**Comment by kporray1** [comment]
This Issue is now tracked by GUS W-7930543.  It is no longer being considered by the product team and will be closed.
