### ISSUE TITLE
Resetting Primary Contacts for Account should only be done for Households

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#358]
Method updateParentAcc (https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/ACCT_IndividualAccounts_TDTM.cls#L229) probably needs to be called only with Accounts of Household type. However, in https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/ACCT_IndividualAccounts_TDTM.cls#L173 is called with any Account type.

Related to https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000D6uj&fId=0D580000037MkKH&s1oid=00D00000000hWLM&OpenCommentForEdit=1&emkind=chatterCommentNotification&s1nid=0DB800000004Fa7&emtm=1481832540044&s1uid=00580000005vESn&s1ext=0.

**Comment by ceiroa** [comment]
lurch: add

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004RBYDAA4" target="_blank">W-017361</a>

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.
