### ISSUE TITLE
Add support for "Other Names Used" to HEDA

### ISSUE THREAD

**Issue by wongmike** [SalesforceFoundation/EDA#379]
Add support for a text field called "Other Names Used" in the Contact Record.
-This field should be searchable by both global search and be used to create custom list views
-names should be separated by commas
-the help bubble should say "Please list other names used (aliases, maiden, legal, nicknames)" - let's get doc's help getting the right verbiage.
-Let's select a reasonable character limit for the field (255?)
-support for this field for creating reports and saving dates of the names are considered out of scope

**Comment by wongmike** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004bGrRAAU" target="_blank">W-017565</a>

**Comment by wongmike** [comment]
@davidjray per our discussion, let's get a write-up on how this can be created by end users. Thanks.
