### ISSUE TITLE
Implement Accessibility Requirements in HEDA Settings

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#384]

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004kda3AAA" target="_blank">W-017606</a>

**Comment by ceiroa** [comment]
Should this be tackled together with a HEDA Settings rewrite? (To make it look more like SAL Settings.)

**Comment by kporray1** [comment]
The introduction of [Education Cloud Settings](https://powerofus.force.com/s/article/EDA-Education-Cloud-Settings) in Summer '21 resolved this issue.  It will be closed.
