### ISSUE TITLE
Ability to link multiple courses to multiple programs and multiple programs to multiple courses (include Prerequisite)

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#401]
Power of US Idea Owner: [Adeline Moore](https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=0058000000A53LhAAJ&tab=sfdc.ProfilePlatformOverview)
[Power of US Idea](https://powerofus.force.com/hub-ideas/1140)

**Enhancement Request**: We would love to see the courses linked to Academic Programs as prerequisites for the Program. Also we need to link multiple courses to programs. Right now I do not see a way of doing this.

**Requirements:** 

- Ability to associate 1 or more Courses to 1 or more Academic Programs
- Ability to associate 1 or more Academic Programs to 1 or more Courses
- All Courses linked to an Academic Program are marked as a prerequisites for the Academic Program
- Reporting should include the ability to:
- Search on an Course and see all associated Academic Programs
- Search on an Academic Program and see all Associated Courses

**Update & Summary:**
This is the ability to link multiple courses to multiple programs or vice versa to achieve the degree associated with an Academic Program (Account).  If a particular course (course offering) is required for two separate Academic Programs (e.g. BIO 101 for both BS in Biology and BS in Biomedical Engineering) it can be linked to both. On the other end, if you get to a point in the Academic Program where you have to take a language course (for example), you have multiple courses to draw from that fulfill that plan requirement. 

This work will result in 2 new objects, "Program Plan" and "Plan Requirement", that will sit between Academic Program (Account), Program Enrollment, and Course. There will also be a new field on the existing Program Enrollment" to reference "Plan" (aka list or sequence of courses a student is following).

- **Originally from a PUB Idea**: https://powerofus.force.com/hub-ideas/1140
- **Blog Post on the topic**: https://salesforcelady.wordpress.com/2017/01/04/how-to-link-courses-and-academic-programs-in-heda/#more-1146

**Comment by jacebryan** [comment]
**lurch: add

**Comment by davidjray** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005QCo0AAG" target="_blank">W-018117</a>

**Comment by kevinswiggum** [comment]
We’ve had a lot of discussion recently around the ability to link Courses to Academic Programs: what courses need to be completed to satisfy the requirements of a program? Originally we considered a fairly straight forward solution where courses could be linked to the Academic Program with a new custom object. However, after a great discussion during the London Higher Ed OSS Sprint, the group came up with a more robust design. The challenge was how to handle how a program’s course list will change over time.

So, after more input from HEDA customers and partners, we have a new draft design. We’ve some great initial feedback but we want more! The draft is attached and we’d love to keep the discussion rolling in the [Power of Us Hub](https://powerofus.force.com/hub-ideas/1140). Let us know what you think!

[Academic Plan Preliminary Design.pdf](https://github.com/SalesforceFoundation/HEDAP/files/1491775/Academic.Plan.Preliminary.Design.pdf)

@jacebryan

**Comment by dorisviv** [comment]
Here at UNT we use program, plan, and subplan. That's an additional one-to many before courses.

**Comment by jacebryan** [comment]
@dorisviv - Thank you for this response! I'd love to keep all the comments tied to this [HEDA Idea](https://powerofus.force.com/hub-ideas/1140) in the Power of US hub. We are receiving a lot of community feedback there and I want to be sure you are kept in the loop of those discussions!

Do you have access to the Salesforce.org Power of US Hub? 

It's easy to join. Just go to powerofus.salesforce.org and enter your Salesforce username and password. It uses Salesforce single sign-on functionality, so you won't be asked to create a new account.

**Comment by jacebryan** [comment]
Update!

We are asking that community input surrounding this post (https://powerofus.force.com/hub-ideas/1140) be received by 12/31/2017.

Next Steps:

@kevinswiggum will generate the new Academic Plan Diagram (based on the input received) and post a new version of the diagram back to this Issue.

I want to thank everyone for all the valuable feedback we've received on this. KEEP IT COMING! :)

**Comment by jacebryan** [comment]
Hello all - as promised here is the [Program Plan Design](https://salesforce.quip.com/fFlEAUX3aoiT) we are moving forward with.

Thank you for your contributions and patience!

If you have questions please direct them back to the original [HEDA Idea](https://powerofus.force.com/hub-ideas/1140).

**Comment by kporray1** [comment]
This issue was delivered in May 2018 and will be closed.
