### ISSUE TITLE
 Analyze HEDA codebase for issues with static flags and large batches

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#403]
turns out that in batch apex, each batch does not run in its own transaction if the batch size is greater than 200. we need to: 

1. fully understand the rules when using Bulk API vs Apex Batch vs data import tools 
2. review HEDA codebase to find all uses of static flags in triggers & batches 
3. decide on appropriate solution (potentially just changing code to reset flags when trigger complete?)

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005fH65AAE" target="_blank">W-018180</a>

**Comment by ceiroa** [comment]
NPSP team is investigating or has already investigated this. @davidhabib or @force2b, could you point me to the work item in your repo? I wasn't able to find it. Thanks.

**Comment by force2b** [comment]
We're still analyzing the impact and identifying solutions across our product lines.

**Comment by ceiroa** [comment]
Thank you, @force2b. Please keep me posted whenever a WI gets created, just so I link them together. Thanks!

**Comment by robertbwatson** [comment]
I'm going to close this now as the WI tied to this was already completed and closed.
