### ISSUE TITLE
Add HEDA logo

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#420]
I just realized (better late than never, I guess!) that I never added a logo to HEDA. We should probably add one. It looks a lot nicer when you select the app if there's a logo. We added the default Salesforce.org one to SAL for now. I wonder if we should use that one for HEDA or get marketing to create a custom one for us...

![screen shot 2017-05-05 at 10 09 52 am](https://cloud.githubusercontent.com/assets/1894238/25751624/511316ae-317b-11e7-84d3-a07b49fa66d2.png)

**Comment by jacebryan** [comment]
@ceiroa - I'd love to see a custom logo for HEDA. The HEDANIST brand logo seems to be taking off for Stanford so perhaps we can piggy back on that and throw a cloud around it :)

**Comment by robertbwatson** [comment]
@jacebryan @ceiroa Should we lurch this really old idea/issue? 🤔

**Comment by jacebryan** [comment]
@robertbwatson - Unless @ceiroa disagrees I'd say: Yes. Lurch it and then see if there is another, more recent WI, and ***lurch: add* it to this Issue. If there is not another WI to ***lurch: add* then go ahead and close the WI and Issue. I suggest this for historical purposes.

**Comment by ceiroa** [comment]
Looks like you already did @jacebryan but having the actual format in the comment :-) (Fyi, if a AA item already existing the command to use would be "attach".)

**Comment by jacebryan** [comment]
Thank you @ceiroa! I've updated my comment to reflect the correct command ;)

**Comment by MatthewBlanski** [comment]
Logos are no longer the standard. Closing.
