### ISSUE TITLE
Analyze HEDA codebase for issues with try-catch without explicit rollback

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#430]
Catching an exception must always do a rollback to prevent partial commits to the database. Even if you re-throw the exception, everything up to the point where it was caught won't be rolled back. Are we doing this anywhere in the codebase?

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006PLdLAAW" target="_blank">W-018706</a>

**Comment by robertbwatson** [comment]
Closing this as the work in the WI was done.
