### ISSUE TITLE
Analyze removal of Asynchronous flag in Trigger_Handler__c

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#432]
Classes need to be built to be run asynchronously. Not every class in HEDA can be run as such. If we are not going to spend the time to analyze which ones can and can't be run like this, we should probably deprecate the field.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006PLdfAAG" target="_blank">W-018710</a>
