### ISSUE TITLE
Investigate creating User trigger

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#433]
SAL needs a trigger on User, so it can run classes on User. We need to investigate the alternatives, because just adding a User trigger can have unintended consequences:

- What if someone else already has a user trigger plugged into the TDTM framework? All user code would be run twice if their classes didn't have a static re-entry flag.
- This ties into issue #403

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006PLedAAG" target="_blank">W-018716</a>

**Comment by robertbwatson** [comment]
The corresponding work item was closed, so I'm going to go ahead and close this as well.
