### ISSUE TITLE
Investigate Lead conversion scenarios for email handling

### ISSUE THREAD

**Issue by davidjray** [SalesforceFoundation/EDA#435]
We should perform a proper investigation around the interaction of lead conversion and how the email handling features impact Lead conversion.

**Comment by davidjray** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006V7OBAA0" target="_blank">W-018742</a>

**Comment by kporray1** [comment]
This effort was included in the Lead Conversion Update epic delivered in Summer '21 and will be closed.
