### ISSUE TITLE
Ensure all classes have proper ApexDocs

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#438]
HEDA ApexDocs are getting some publicity (https://partners.salesforce.com/s/education/general/Role_Salesforce.org_Higher_Education). We need to ensure all recent changes to public/global classes and methods contain proper ApexDocs.

ApexDocs example: https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/ADDR_Account_TDTM.cls#L62-L69

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006hiJJAAY" target="_blank">W-018891</a>

**Comment by robertbwatson** [comment]
As part of this work (or maybe a separate work item?), we might want to consider making sure the ApexDocs for HEDA are aligned properly - for example:

- There are some groups with/without spaces (CourseEnrollments vs Plan Requirement)
- There is a group for ProgramPlan, as well as a separate group for Program Plan
