### ISSUE TITLE
Provide transactional and user account way to disable all HEDA Triggers

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#439]
Already implemented in NPSP: https://github.com/SalesforceFoundation/Cumulus/issues/2525

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006nVCtAAM" target="_blank">W-018936</a>

**Comment by davidjray** [comment]
@ceiroa did you mean disable all HEDA triggers?

**Comment by ceiroa** [comment]
Sorry, yes. Copy+paste and all. ;-)

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.
