### ISSUE TITLE
Add reentrancy flag to any TDTM class that doesn't have it

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#440]
To prevent the class from being run twice, in case that other package built on top of HEDA adds a trigger for an Object that HEDA already has a trigger for, or the case where two packages built on top of HEDA both add triggers for the same Object.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006oWlDAAU" target="_blank">W-018960</a>

**Comment by robertbwatson** [comment]
The corresponding work item for this was closed - we created separate issues & work items for each class, so I'll close this now.
