### ISSUE TITLE
Add lookup filters to those lookup fields that refer to Account so they allow only specific record types

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#441]
For example, when creating a new Program Enrollment record for a student, the Account selected should be only of Academic Program record type. Ideally the lookup would only display Academic Programs. But since that isn't possible, at least we could add a filter to avoid the record being saved with "invalid" data.

![screen shot 2017-06-07 at 4 12 51 pm](https://user-images.githubusercontent.com/1894238/26901680-4c537434-4b9c-11e7-8292-1e11c5db7a11.png)

![screen shot 2017-06-07 at 4 13 33 pm](https://user-images.githubusercontent.com/1894238/26901686-4f77359c-4b9c-11e7-821f-30cf06c8df3c.png)

The caveat is that we would need to package whatever record types we reference. We will have to weight this against just letting the users create their own filters (and just documenting how - @lianeyee ).

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006oX8dAAE" target="_blank">W-018984</a>

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.
