### ISSUE TITLE
Increase test coverage for classes with coverage under 60%

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#445]
The following classes have very test coverage. We should increase it, to make sure regressions don't go in undetected.

![screen shot 2017-06-16 at 1 27 04 pm](https://user-images.githubusercontent.com/1894238/27239783-f3928ab2-5297-11e7-8b2e-01161d5ecd22.png)

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006uUa1AAE" target="_blank">W-019116</a>

**Comment by MatthewBlanski** [comment]
This is not a specific work item and has been slowly addressed over time. Work remains but is not a bug to be exposed in the issues section.
