### ISSUE TITLE
Investigate whether we can check "Allow Activities" in all objects

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#462]
This would facilitate activity management (tasks and events) in SAL. We want to do this, but we have to see if the packaging org will let us do that. This old idea seems to indicate this is not possible: https://success.salesforce.com/ideaView?id=08730000000BqB7AAK. We need to test it.

Also, if it does let us do it, what happens if someone has it uncheck and we check it in the package?

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007IEbrAAG" target="_blank">W-019458</a>

**Comment by kporray1** [comment]
This effort is included in GUS W-7931287.  It is no longer being considered by the product team, and will be closed.
