### ISSUE TITLE
Null pointer exception when updating primary faculty of course offering

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/EDA#464]
Related to issue #450 

Per David,

I am getting a null pointer exception consistently, and I think it is related to this work after looking at the code.

Steps to reproduce:

1. Create two Course Offerings with the same faculty member.
2. Edit one of the Course Offerings and change the primary faculty to a new primary faculty member.
3. Switch to the second Course Offering and change the primary faculty to same new primary faculty member from step 2.

This is the error I see:
![28222404-39ceaa2a-687c-11e7-8b7f-84d2fc40d5c0](https://user-images.githubusercontent.com/28262573/28228621-41993d48-68ad-11e7-84df-8f9e6d1e07ba.png)

**Comment by xinnanlisf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007IGOmAAO" target="_blank">W-019547</a>

**Comment by robertbwatson** [comment]
The corresponding work item(s) have been closed, so resolving and closing this now.
