### ISSUE TITLE
As an admin, I would like to be able to configure the department a Contact belongs to

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#469]
Given HEDA's flexibility, some Contacts (professors, advisors,...) will be created directly as children of a Department Account, while others will be linked to a Department through the Primary Department (unmanaged) or some other field. We would like to allow the admin to configure this.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007a06MAAQ" target="_blank">W-019828</a>

**Comment by kporray1** [comment]
This has been delivered through Affiliations functionality, and will be closed.
