### ISSUE TITLE
Please add the ability to assign Primary to Academic Program when creating a Program Enrollment

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#475]
Found by: Jace Bryan
Testing in HEDA dev org - Version 1.38
Possible Issue: UX bug

When creating an Academic Program Affiliation from the Affiliated Accounts related list on the Contact record I am able to set the Primary value. The same experience if I create the Affiliation from the Affiliations tab. However, if I create the Academic Program Affiliation through the creation of a Program Enrollment then I am not given the Primary option for Academic Program thus requiring me to go back to the newly created Academic Program on the Affiliated Accounts related list on the Contact record and set the Primary value there so it shows up on the Details page of the Contact (i.e. Primary Academic Program). 

**WI DEFINITION**

What would be needed for this WI:

2 new fields added to the Program Enrollment object

1. Primary [checkbox] - same as what is shown when creating/editing an Affiliated Account
2. Role [picklist] - same Role picklist values from Affiliated Account

Neither fields are required to create the Program Enrollment

**How it should work:**

1. Primary checkbox works the same as the Primary checkbox when creating an Affiliated Account (i.e. updates the Contact Record's Primary Academic Program field)
2. Role works the same as the Role picklist when creating an Affiliated Account (i.e. just sets a value for the Affiliation)

**Expected Outcome:**

1. When the Primary checkbox is checked at the time the Program Enrollment is created the corresponding Affiliation that is created will set the Primary Academic Program field on the Contact Record
2. When the Role picklist has a value selected at the time the Program Enrollment is created the corresponding Affiliation that is created captures that Role value

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007qMQKAA2" target="_blank">W-020048</a>

**Comment by davidjray** [comment]
I'd like to add a vote to prioritize this feature as well. When it comes to bulk data loading, this enhancement would be beneficial.

**Comment by cdcarter** [comment]
Was just dropping by to say...

**Comment by kporray1** [comment]
Please post this on the [Idea Exchange](https://ideas.salesforce.com/s/post) to raise visibility and get it prioritized.
