### ISSUE TITLE
Typo on TDTM.htm

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/EDA#485]
Community reported a typo on TDTM.htm.

**Comment by xinnanlisf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008F6iWAAS" target="_blank">W-020417</a>

**Comment by davidjray** [comment]
@xinnanlisf, You may need to manually close this, but before you do, I'd recommend editing the note of recently merged PR so this issue is included in the release notes.

**Comment by cpolcyn** [comment]
Included in production release rel/1.41

**Comment by robertbwatson** [comment]
Closing this as it was fixed in a prior EDA release.
