### ISSUE TITLE
Advisee Label Typo in Reciprocal Settings (in HEDA Settings)

### ISSUE THREAD

**Issue by lianeyee** [SalesforceFoundation/EDA#488]
In HEDA Settings, on the Reciprocal Settings tab of the Relationships tab, the Neutral value for the Advisor/Advisee relationship is misspelled "Advisse".

![image](https://user-images.githubusercontent.com/25490811/30553213-56de8092-9c55-11e7-99ae-831ff1293bae.png)

**Comment by xinnanlisf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008LK1kAAG" target="_blank">W-020520</a>

**Comment by robertbwatson** [comment]
Closing this based on discussions in the linked work item that was previously closed.
