### ISSUE TITLE
Implement additional Install Script Unit Test scenarios

### ISSUE THREAD

**Issue by weizsforg** [SalesforceFoundation/EDA#496]
**lurch: attach W-018779

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006V9AuAAK" target="_blank">W-018779</a>

**Comment by robertbwatson** [comment]
Closing this as the corresponding WI was closed and included in a prior EDA release.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006V9AuAAK" target="_blank">W-018779</a>
