### ISSUE TITLE
Add Usernames_to_Exclude__c field to Trigger_Handler__c

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#509]
And its related logic. Same as in NPSP. (The original creation of the field and its related logic is not very easy to find now because the field was renamed: https://github.com/SalesforceFoundation/Cumulus/commit/3c99e7df8856ffd4b2b92fe984e38070b8c4800f).

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008j322AAA" target="_blank">W-021068</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.48 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.48

**Comment by robertbwatson** [comment]
Closing this as it was included in a prior EDA release.
