### ISSUE TITLE
HEDA Health Check feature

### ISSUE THREAD

**Issue by kevinswiggum** [SalesforceFoundation/EDA#513]
HEDA has a lot of configuration settings that significantly impact functionality. It would be really useful to have a Heath Check feature that can look at configuration and data to alert admins to potential issues. I'd envision a pluggable architecture that could run multiple health checks and output results to a UI, email, etc. Ideally each error could include some verbiage on why it's an issue and steps to correct it. Some potential checks could include:

1. Verify the Administrative record type is configured correctly.
2. Query and Administrative account records that are related to more than one (or zero) Contacts
3. Disabled trigger handlers and a discussion of how that affects functionality (or an empty trigger handler table which causes other problems)
4. Query any contacts where the email/phone fields are out of sync with preferred
5. Contacts where Address does not match the primary Address record
6. Missing record types for Course Connection (or course connections setting not turned on)

**Comment by kevinswiggum** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008jFDAAA2" target="_blank">W-021117</a>

**Comment by MatthewBlanski** [comment]
Happily delivered in our Spring major release!
