### ISSUE TITLE
Update help text of hed__Account_Processor for translation accuracy

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/EDA#516]
Per Liane,
Revise help text:
CustomField.hed__Hierarchy_Settings__c.hed__Account_Processor.HelpText	Setting that controls whether each Contact is associated with an Administrative Account or a Household Account.

**Comment by xinnanlisf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000934bJAAQ" target="_blank">W-021502</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.48 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.48

**Comment by robertbwatson** [comment]
Closing this as it was fixed in a prior EDA release.
