### ISSUE TITLE
Add reentrancy flag to any AFFL_AccRecordType_TDTM class

### ISSUE THREAD

**Issue by kevinswiggum** [SalesforceFoundation/EDA#532]
AFFL_AccRecordType_TDTM currently does not implement the TDTM_ProcessControl.getRecursionFlag design for preventing reentrancy into the class. The code watches for Record Type changes on an Account and then updates any related Affiliations and Contacts (related by one of the Primary_x fields). Adding reentrancy flags to this class can avoid repeat actions on the same objects during the same transactions.

Part of the reentrancy design is to perform the DML within the class rather than letting DMLWrapper handle it...this could could affect DML limits...worth investigating and assessing impact.

**Comment by kevinswiggum** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009PSruAAG" target="_blank">W-022398</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.77 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release 1.77
