### ISSUE TITLE
Add reentrancy flags to CCON_Faculty_TDTM

### ISSUE THREAD

**Issue by kevinswiggum** [SalesforceFoundation/EDA#534]
The After Insert/Update events make changes to the related Course Offering (setting primary faculty field) which has the potential to make updates back to the Course Enrollment table. A reentrancy flag that controls access to the "courseOfferingsToUpdate" logic would save some additional processing

**Comment by kevinswiggum** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009PStgAAG" target="_blank">W-022400</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.80 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release 1.80
