### ISSUE TITLE
Add reentrancy flags to TERM_CourseOff_TDTM

### ISSUE THREAD

**Issue by kevinswiggum** [SalesforceFoundation/EDA#536]
It seems unlikely this would experience reentrancy problems since the Term updating the related Course Offerings won't circle back to update the Term again...but this would be a good safeguard in case a customer would put any Triggers on Course Offerings that update the Term (and kick off unnecessary code cycles)

**Comment by kevinswiggum** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009PSuoAAG" target="_blank">W-022402</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.80 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release 1.80
