### ISSUE TITLE
Heda Settings: Courses: There is some random "Run Copy" text in the bottom right

### ISSUE THREAD

**Issue by annejackson** [SalesforceFoundation/EDA#537]
Steps to Reproduce:

If you go into HEDA settings. (I was in the Heda QA sandbox, version 1.47)

Go into Courses tab.

Look at the bottom right- there is text that says "Run Copy"

I expected it to run an action of some type- specifically when I tried to edit settings- but it's not clickable or anything. It stays as "Run copy" and text only for both the read-view and the edit-view.

**lurch : attach W-022351

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009PZdxAAG" target="_blank">W-022423</a>

**Comment by annejackson** [comment]
**lurch:attach W-022351

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009PKc3AAG" target="_blank">W-022351</a>

**Comment by aligeez** [comment]
This issue affected Classic UI only. Not an issue in lightning. Closing.
