### ISSUE TITLE
Support for auto Program Enrollment creation after Affiliation updates

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#542]
**Issue reported by:** [Buyan Thyagarajan](https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000007SCeO&tab=sfdc.ProfilePlatformFeed)
**PUB Thread:** [Preventing program enrollment records creation on inserting a new affiliation record..](https://powerofus.force.com/0D58000003yhbeC)

**Issue as reported:**

We have a usecase where we want to create a record in program enrollment only after a specific status is updated on affiliation. Currently, the default behavior is that a program enrollment record gets created immediately after an affiliation record is created. How do we avoid creation of program enrollment?

**Investigation:**

Jace and @kevinswiggum investigated this issue on 2/7 and we believe that the issue resides in the trigger handler: AFFL_MultiRecordTypeMapper. The Trigger Handler record is configured to fire After Update...but in the code, the Program Enrollment creation feature is only enabled for Inserts.

Auto-creation of the Program Enrollment is configurable in HEDA settings...and along with that you can configure what role and status should be considered when looking at the Affiliation when deciding to create the PE. But here's the kicker...that auto PE creation only happens on an INSERT event on Affiliation. If the affiliation status is UPDATED, that auto-create won't fire.

If we are allowing them to set a status and role, we should be able to support UPDATES by inspecting changes to those two fields.

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009a6vjAAA" target="_blank">W-022687</a>

**Comment by kporray1** [comment]
Please post this on the [Idea Exchange](https://ideas.salesforce.com/s/post) to raise visibility and get it prioritized.
