### ISSUE TITLE
Trigger Handlers: Need new username to exclude field and help bubble translated

### ISSUE THREAD

**Issue by annejackson** [SalesforceFoundation/EDA#546]
Steps to duplicate. In HEDA release 1.48 (on the QA Sandbox)

1. Make sure your user has access to view and edit trigger handler fields. And that you have added the usernames to exclude field in the page layout and in the list view.
2. Change your users settings to Spanish.
3. Go to Heda->Trigger handlers page.
4. You will notice the list view still says "usernames to exclude" for that field instead of the translated value.
5. Open up any trigger.
6. You will notice the usernames to exclude field and help bubble are still in english instead of spanish. This is on the listing page and if you click edit as well.

**Comment by annejackson** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009gIIfAAM" target="_blank">W-022795</a>

**Comment by annejackson** [comment]
![usernames to exclude needs translated2](https://user-images.githubusercontent.com/35311289/36175583-fe6b2174-10dd-11e8-8501-381c91747f04.png)
![usernames to exclude needs translated](https://user-images.githubusercontent.com/35311289/36175584-fe7fac02-10dd-11e8-9f39-61d0774233c9.png)

**Comment by annejackson** [comment]
fyi @xinnanlisf
