### ISSUE TITLE
Heda Settings: System: New auto naming and format settings and help text need translated

### ISSUE THREAD

**Issue by annejackson** [SalesforceFoundation/EDA#550]
Steps to duplicate:
*Assign the User's language to something other than English- I did Spanish.
1. Go to Heda Settings
2. Click the system tab.
3. For both the view and edit view the new settings/help text need translated. 
See below screenshot of what is happening currently. 
![new field and help text translated](https://user-images.githubusercontent.com/35311289/36607649-3a980496-1895-11e8-9219-56a7e7c171ed.png)

**Comment by annejackson** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009lvgHAAQ" target="_blank">W-022926</a>

**Comment by dgamboni** [comment]
This has been fixed. Closing GH Issue.
