### ISSUE TITLE
Primary Business Organization based on role (INVESTIGATION)

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#551]
**HEDA Idea:** [Primary Business Organization based on role](https://powerofus.force.com/hub-ideas/1292
)
**Created by:** [Elena Inurrategui (Proyecto Tribo)](https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000006leZEAAY&tab=sfdc.ProfilePlatformOverview)

**Idea:**

Someone can be related to a School or University as student or employee.

What is happening now:

- A contact works at a School or University (the Account has the Educational Institution Record Type)
- When I add an Affiliation to the University, SF will update the Primary Education Institution in the contact, instead of the Primary Business Organization, because the configuration is looking at the Account Record Type.

I would like something like this:

If I create an affiliation with the role = Employee and select it as primary, it updates the Primary Business Organization, regardless if the Account is a School, a University or a Business. If I create and affiliation with the role = Student, it updates the Primary Education Institution.

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009rBvVAAU" target="_blank">W-022938</a>

**Comment by kporray1** [comment]
This Issue will be closed; follow this [Idea in the Trailblazer Community](https://ideas.salesforce.com/s/idea/a0B8W00000Gdk3YUAR/primary-business-organization-based-on-role) for updates.
