### ISSUE TITLE
Settings: Household naming format: If a field included in format is empty for a contact, an extra "and" appears to the user in the account/household name

### ISSUE THREAD

**Issue by annejackson** [SalesforceFoundation/EDA#553]
Note- this only occurs if there is more than 1 contact in a household. 

Steps to duplicate:
1. I had my Heda Settings->System, Household account naming format as:
{!Salutation} {!{!Firstname}} {!Lastname} Family Format
*I also enabled/checked- Automatic Household Naming
2. I created one contact
Mr. Bud Jackson
3. The Automatically generated account/household name looks correct. It shows:
"Mr. Bud Jackson Family Format"
4. Under the account/household, clicked create new in Related Contacts Section
5. Created another contact
Mrs. Tammy Jackson
6. The automatically updated household/ account name went to:
"Mrs. and Mr. Tammy and Bud Jackson Family Format"
this looks correct except it can be confusing as Mr. is next to Tammy. 
7. Under the account/household, clicked create new in Related Contacts Section
8. Created another contact (this time leave salutation off and equal to "None")
Barry Jackson
9. It updates account/household name to:
Mrs. and Mr. and Tammy and Bud and Barry Jackson Family Format
**There is an Extra "and" that is showing when salutation is empty. 
Ideally it should update the account/household name to be: 
Mrs. and Mr. Tammy and Bud and Barry Jackson Family Format

see screenshot. 
![added extra and for empty salutation string](https://user-images.githubusercontent.com/35311289/36756616-8a2bff44-1bdd-11e8-9c81-2ec0fa25eb07.png)

Another example with non "Other" Formats:
Heda settings for household name with automatic household naming checked/on:
{!{!FirstName}} {!LastName} Family
1. Create a contact- leave firstname blank
I entered for just last name
Perry
2. The household/account name was: 
Perry Family
which is correct.
3. From the account/household page, I Created another contact using the "New" button in the contacts related tab.
I entered for only last name
Perry
4. The household/account name was: 
and Perry Family
which does not look good. 
see screenshot.

![no first name](https://user-images.githubusercontent.com/35311289/36757345-52e46614-1bdf-11e8-8927-027866d7aa6b.png)

**Comment by annejackson** [comment]
**lurch:add

**Comment by annejackson** [comment]
Per @xinnanlisf  we need to better handle empty string and connector. FYI @ceiroa

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009rIsTAAU" target="_blank">W-023018</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.76 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release 1.76
