### ISSUE TITLE
Reparenting Primary Affiliations to a new Contact creates additional primary affiliation

### ISSUE THREAD

**Issue by dougbennett** [SalesforceFoundation/EDA#556]
If I re-parent any primary Affiliation with a new Contact, HEDA will populate the primary lookup field on the Contact, resulting in an additional primary Affiliation being created and the primary flag on the existing one getting set to false. 

I discovered this while resolving duplicate Contacts.

**Comment by dougbennett** [comment]
@ceiroa Adding more information here that would be useful.  Steps to reproduce:

1.Merge 2 Contacts (either through native SF merge, Demand tools or Object Merge) where each Contact has a primary affiliation (use-case was similar Primary Business Affiliation).
2. All Trigger merge handlers were turned on
3. I expected the victim affiliation to be orphaned with no lookup to the master contact.  Instead, a 3rd duplicate affiliation was created as primary.

It would be great if the trigger handler omitted the execution of affiliation creation if a primary affiliation already exists.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by ceiroa** [comment]
Thank you for the details @dougbennett, and for reporting the issue in the first place!

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000ADo9qAAD" target="_blank">W-023530</a>

**Comment by ceiroa** [comment]
Hey @aligeez! Just fyi, this is the item from the item from the mini-sprint at the Summit (see link to AA above).

**Comment by mrbelvedere** [comment]
Included in production release 1.61

**Comment by dougbennett** [comment]
Thank you!!!

**Comment by MatthewBlanski** [comment]
Tracking [W-7931284](https://github.com/SalesforceFoundation/EDA/issues/556)

**Comment by kporray1** [comment]
This Issue was fixed in EDA Release 1.61, in 2018.  It will be closed.
