### ISSUE TITLE
When we remove the Account lookup on a Contact, system should fill in the Account lookup if it can find an Account that Primary Contact = Current Contact

### ISSUE THREAD

**Issue by weizsforg** [SalesforceFoundation/EDA#557]
1. Create a Contact with either Admin or HH account model. System will automatically create an Account for the Contact.  And mark current Contact as the Primary Contact of the new Created Account.
2. Now, try to remove the Account lookup of the Contact and click Save. You will see that now the Account Lookup is empty of the Current Contact. 
3. The behavior is wrong here since every Contact must associate with an Account. 
4. The correct behavior is that system should fill in the Account lookup if it can find an Account that Primary Contact = Current Contact

**Comment by weizsforg** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009rQgvAAE" target="_blank">W-023054</a>

**Comment by ceiroa** [comment]
@weizsforg Why would the user want to clear that field in the first place? Is this really a bug?

**Comment by weizsforg** [comment]
Hi @ceiroa , yes, I think it is an unusual use case. 
Actually, the reason that I create this bug is because HEDA has the existing code to set Primary Contact for this use case. However, the code has a bug so it does not save the Primary Contact field on Account record. Also, NPSP has the same logic and it saved the Primary Contact on Account record.

**Comment by skosgi1** [comment]
**lurch: attach W-035178.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C97dQAC" target="_blank">W-035178</a>
