### ISSUE TITLE
Household Naming: Match NPSP's style of adding commas for when a household has 3 or more contacts

### ISSUE THREAD

**Issue by annejackson** [SalesforceFoundation/EDA#558]
I compared NPSP and HEDA for this one (both on the QA sandboxes). Included the format settings for household as {!{Firstname}} {Lastname} Household for each. (make sure household is default account format).

Talked with Keld and he said to go ahead and make this an enhancement.

Then in NPSP and HEDA I did these steps and got different account/household names as a result:
1. Create a contact with first and last name and with no account name
2. Account is auto-created as a household.
3. go into the household/account.
4. Add two more contacts- both having a first and last name.
5. refresh the page to make sure you see most recent changes.
6. Compare the account names for the household.
**NPSP uses a comma and only has 1 "and" string
**HEDA doesn't use a commas and has multiple "and" strings for number of contacts. 

See screenshot comparisons:
NPSP:
![how npsp does multiple contacts in household](https://user-images.githubusercontent.com/35311289/36919354-f39ca8da-1e2a-11e8-80de-62d6189aa29d.png)

HEDA: 
![how heda does multiple contacts in household](https://user-images.githubusercontent.com/35311289/36919355-f3b6e5ec-1e2a-11e8-90d9-7d6538ee8a09.png)

**Comment by annejackson** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009rXZdAAM" target="_blank">W-023107</a>

**Comment by robertbwatson** [comment]
Closing this issue as the associated WI was also closed. This was delivered in a prior release, though we aren't quite sure when. cc @kdy618
