### ISSUE TITLE
Account: Change the field level name for the Primary_Contact__c field to something that is more user friendly like "Primary Contact" (which would match NPSP)

### ISSUE THREAD

**Issue by annejackson** [SalesforceFoundation/EDA#559]
Steps to see this:
1. Login to an account.
2. Go to setup->object manager
3. For account->click on fields and relationships
The field is "Primary_Contact__c"
Yet the field level name is "_SYSTEM: One2OneContact"
**You can also add the _SYSTEM: One2OneContact to the account layouts and see it on the account details page.

This field level name doesn't make much sense from a user perspective if they add it to their layouts. Ideally something like "Primary Contact" would be great. That way a user doesn't have to change it themselves and it would match NPSP. 
see screenshot. 

![primary contact field label suggestion](https://user-images.githubusercontent.com/35311289/37049811-1b3c24c0-2140-11e8-819e-6f162fc50124.png)

**Comment by annejackson** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009wxiHAAQ" target="_blank">W-023134</a>
