### ISSUE TITLE
Account Naming: Allow administrative contacts changes to first name/salutation to also trigger renaming of the admin account

### ISSUE THREAD

**Issue by annejackson** [SalesforceFoundation/EDA#560]
A customer had this question- see whole thread here:
https://powerofus.force.com/0D580000041in11

Steps to duplicate (*note, you will notice that if you do these steps for a household contact and automatic naming is on, the account/household name will update)
1. Choose administrative default account model
2. In naming format, include firstname and last name.
3. Create a contact
4. The administrative account name shows up (first and last name)
5. Now modify the contact- and do firstname only. save.
6. The administrative account name doesn't get triggered to change. In order to get it to change, you have to modify the last name.  It would also be nice if changes were made only to the salutation, if that would trigger the account name to update as well....
*Note- And the odd thing is if you change _both_ the first and last names, the entire admin account is renamed correctly.

**Comment by annejackson** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009x1HMAAY" target="_blank">W-023159</a>

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.
