### ISSUE TITLE
Primary Contact: Inconsistencies with how this works in HEDA as opposed to NPSP on moving and deleting contacts

### ISSUE THREAD

**Issue by annejackson** [SalesforceFoundation/EDA#563]
There are two examples of this so far that I can think of- on moving and deleting contacts. See below steps. The *** (stared) ones are where it differs in between HEDA and NPSP.

Scenario: Move/Delete the primary contact of a multi-contact household to another household.
1. Create a contact. It will automatically be the primary contact.
2. Create at least 2 more contacts.
(Not sure this step is needed) Un-associate the contact as the primary contact (make it blank). Then re-associate the contact as the primary contact.
****3. Move the primary contact. In NPSP, The second contact becomes the primary contact.  (In HEDA, the last modified contact because the primary- so maybe the most recently added contact). 
4. Move the contact back to the original household. The second contact in step 3 stays primary contact.
***5. Delete the primary contact. In NPSP, The original contact that was primary becomes primary again (1st contact created from step 1). (In HEDa, the primary contact field is blank)

**Comment by annejackson** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009x9fiAAA" target="_blank">W-023189</a>

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.
