### ISSUE TITLE
Household Naming: Match NPSP's style naming order for a household (including primary contacts)

### ISSUE THREAD

**Issue by annejackson** [SalesforceFoundation/EDA#564]
Checked with household automatic Naming enabled in HEDA:

In NPSP- the primary contact field controls the name order displayed in the household/account. 
Created 4 contacts in the order shown below.
So for Bud, Tammy, Barry and Bethany, if Bud is selected as primary contact- it will display his name first and then the order of added with oldest added first to most recent:
"Bud, Tammy, Barry and Bethany JacksonTest Household"
**also if you changed the primary to Bethany it would show and update the order so primary shows first:
"Bethany, Bud Tammy and Barry JacksonTest Household"

For heda now it displays as most recent/modified name first and doesn't take primary field into account naming structure
Created two contacts in one household in order of "Barry Jackson, then "Anne Jackson". It displays
"Anne and Barry Jackson"
instead of 
"Barry and Anne Jackson" (as Barry is primary contact as was entered first).

*Another example in HEDA was I had 3 contacts, created in order:
Jim Mahoney
Joy Mahoney
Josh Mahoney
Jim was the primary and I changed it to Josh Mahoney
Account naming didn't update- it remained in order of creation:
"Jim and Joy and Josh Mahoney Household"

See screenshots. 
![heda primary contact and naming structure different than npsp](https://user-images.githubusercontent.com/35311289/37232504-4c93a942-23bd-11e8-86c2-3e168afeda1f.png)
and
![heda primary contact order](https://user-images.githubusercontent.com/35311289/37232505-4ca5887e-23bd-11e8-8b2d-24ec99a5b52e.png)

**Comment by annejackson** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009x9gKAAQ" target="_blank">W-023190</a>

**Comment by aligeez** [comment]
Per the conversation in W-034159  - we were pursuing alphabetical order, not the way NPSP does it. Closing this Work Item.
