### ISSUE TITLE
Match NPSP's steps when deleting the only contact that is associated with a household (a message should display that gives the user options as to what to do with the empty account)

### ISSUE THREAD

**Issue by annejackson** [SalesforceFoundation/EDA#565]
Have household as default account and can also set automatic naming up.

Steps:
1. Create a couple of contacts in one household.
2. Then start deleting them on the account page->in contacts section one by one.
3. Once get to deleting last contact, compare  the messages:
 
In NPSP it does this:
Warning: David Mahoney is the only Contact in the David Mahoney Household Account. Deleting this Contact would leave an empty Account. Would you like to delete David Mahoney Household, including David Mahoney, instead?

with button options:
Delete Contact and Leave Empty Account
View Contact Record
Delete Account

In HEDA it does this:
Just says that "are you sure you want to delete the contact".
No button options for the account.

**Comment by annejackson** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009x9hrAAA" target="_blank">W-023191</a>

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.
