### ISSUE TITLE
Include Custom fields for Account Naming format

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#573]
**HEDA Idea**: HEDA - [Include Custom fields for Account Naming format](https://powerofus.force.com/hub-ideas/1325)
**Created by**: [Tom Neuburger (Smith College)](https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000006S8suAAC&tab=sfdc.ProfilePlatformOverview)

**Idea**:

HEDA provides an AWESOME ability to follow a naming format for Administrative and Household accounts. You can pass contact fields into the account naming formula, which is very cool. Unfortunately we are limited to only including standard account fields as parameters. I'd love to be able to pass a custom field (such as Class Year) to the naming format.

**Comment by jacebryan** [comment]
**lurch: attach W-022943

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009rCeNAAU" target="_blank">W-022943</a>

**Comment by walt0019** [comment]
Simply commenting to upvote this because it is the Salesforce thing to do.  I would like to add Middle Name to our custom Administrative Account Name format.

**Comment by jacebryan** [comment]
@walt0019 - Be sure to [vote the Idea up](https://trailblazer.salesforce.com/ideaView?id=0874V0000015JseQAE) in the Trailblazer Community! :)

**Comment by walt0019** [comment]
Thanks, @jacebryan, done.

One more question why are there two places to format the Administrative Account Name, EDA Settings and Custom Settings?  I was confused why my changes on the Administrative Account Name within the EDA Settings section did not take.  I wasn't initially aware that it was controlled in a Custom Setting too and that that one controlled the setting if both existed.  Did we adopt EDA early and have both settings or does this cause confusion for a number of users?

While it was create the Custom Setting was referenced in the documentation (https://powerofus.force.com/s/article/EDA-Customize-Admin-and-HH-Acct-Names), I think it could be clearer, or it could be just me.  I wish it referenced the Hierarchy Settings Custom Settings and explained a potential conflict.

**Comment by jacebryan** [comment]
Hey @walt0019 - go ahead and post that question to the EDA group in the Hub.

**Comment by walt0019** [comment]
Thanks, @jacebryan, will do.

**Comment by kporray1** [comment]
This GitHub issue will be closed; follow this [Idea in the Trailblazer Community](https://ideas.salesforce.com/s/idea/a0B8W00000Gdk36UAB/heda-include-custom-fields-for-account-naming-format) for updates.
