### ISSUE TITLE
Add "Description" field on Trigger Handler records

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#577]
**HEDA Idea**: HEDA - [Add "Description" field on Trigger Handler records](https://powerofus.force.com/hub-ideas/1255)
**Created by**: [Jason Jensen (Smith College)](https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=0058000000CX0ZUAA1&tab=sfdc.ProfilePlatformOverview)

**Idea**:

Admins can disable HEDA-specific triggers using Trigger Handler records, but these records only display the name of the relevant class to be run or deactivated. I'd like to see a Description field added to these records with a brief description of what functionality can be managed using Trigger Handlers.

As an admin/developer, I've reviewed HEDA code in GIT to find this information in the past. Now I see that this info is available here: http://developer.salesforce.org/HEDAP/ApexDocumentation/index.html

Examples below are from: http://developer.salesforce.org/HEDAP/ApexDocumentation/Relationships.html

- REL_Relationships_Cm_TDTM - Implements relationships behavior on CampaignMember.
- REL_Relationships_Con_TDTM - Implements relationships behavior on Contact.
- REL_Relationships_TDTM - Implements relationships behavior on Relationship__c.
- REL_Utils - Relationships utilities

These descriptions should be added to their correspondent Trigger Handler records in HEDA.

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000ADnpVAAT" target="_blank">W-023528</a>

**Comment by MatthewBlanski** [comment]
Downgraded this partially since trigger handlers have associated records.

**Comment by kporray1** [comment]
This GitHub Issue will be closed - please follow this [Idea in the Trailblazer Community](https://ideas.salesforce.com/s/idea/a0B8W00000Gdk3CUAR/add-description-field-on-trigger-handler-records) for updates.
