### ISSUE TITLE
HEDA Settings page needs translated

### ISSUE THREAD

**Issue by annejackson** [SalesforceFoundation/EDA#583]
This is using Spanish (after 1.51 release can also use French to check, and possibly Catalan later).
I saw this in both HEDA package 1.50 and HEDA package 1.51

Note- I was in chrome.

Steps:
1. Go to the User Settings page.->Change the language in Language and Time Zone section to "Spanish" (Note- my Locale was still English (United States)). Save.
2. I refreshed the browser a couple of times (I'm in lightning).
3. Other tabs looked translated (contacts, accounts, terms, etc.)
4. Go to Heda Settings Tab. The title was translated. But all the sub tabs and other sections/text were all in English.  See screenshot.

Note- the screenshot was taken with French in 1.51 release (QA Sandbox), however it looks the same in Spanish. Heda settings tab name is translated but not the content of each sub tab.

![french settings_heda settings](https://user-images.githubusercontent.com/35311289/38272759-34c63f2e-3758-11e8-8f77-1447bee67a58.png)

**Comment by annejackson** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AJgm7AAD" target="_blank">W-023681</a>

**Comment by MatthewBlanski** [comment]
This has long-since been resolved.
