### ISSUE TITLE
HEDA Translations: French: Do an analysis of what fields still have to be translated

### ISSUE THREAD

**Issue by annejackson** [SalesforceFoundation/EDA#586]
This is an item to track time/effort on this and to make sure that we don't forget about getting back to French Translations. Items to do:
1. Check in Sandbox/production in language with all the right language settings and evaluate what is not translated. 
2. Either use this ticket to fix anything left, or create new tickets.
***Then, if we use this ticket, next steps would be:
3. Develop/fix/put in translations.
4. Test new translations.

**Comment by annejackson** [comment]
Ticket in AA- W-023773

**Comment by jacebryan** [comment]
Please see [HEDA Idea 1422](https://powerofus.force.com/hub-ideas/1422) which was submitted by [Gauthier Cane (EMD école de management)](https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=0058000000Evb8qAAB&tab=sfdc.ProfilePlatformFeed) surrounding the need for additional updates to the French translation.

**Comment by jacebryan** [comment]
Lurch: attach W-023773

**Comment by jacebryan** [comment]
**lurch: attach W-023773

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AJrHzAAL" target="_blank">W-023773</a>

**Comment by GauthierSeason** [comment]
Hi!
The "Preferred Email" feature only accept perfect match between picklist value translation and email field translation.
Currently out of the box the two don't match and need to be manually modified to use the feature: 
Autre -> E-mail alternatif
Université -> Adresse e-mail de l'université
Professionnel -> Adresse e-mail professionnelle

Thanks.

PS: the best would have been using API name in the code but I know it's difficult to make this type of change when customer are already using the feature.
