### ISSUE TITLE
MCMP: Link Multiple Courses to Multiple Programs

### ISSUE THREAD

**Issue by aligeez** [SalesforceFoundation/EDA#592]
**Description:** 
This is the ability to link multiple courses to multiple programs or vice versa to achieve the degree associated with an Academic Program (Account).  If a particular course (course offering) is required for two separate Academic Programs (e.g. BIO 101 for both BS in Biology and BS in Biomedical Engineering) it can be linked to both. On the other end, if you get to a point in the Academic Program where you have to take a language course (for example), you have multiple courses to draw from that fulfill that plan requirement. 

This work will result in 2 new objects, "Program Plan" and "Plan Requirement", that will sit Academic Program (Account), Program Enrollment, and Course. There will also be a new field on the existing Program Enrollment" to reference "Plan" (aka list or sequence of courses a student is following).

- **Originally from a PUB Idea**: https://powerofus.force.com/hub-ideas/1140
- **Blog Post on the topic**: https://salesforcelady.wordpress.com/2017/01/04/how-to-link-courses-and-academic-programs-in-heda/#more-1146

**Comment by aligeez** [comment]
Original issue: https://github.com/SalesforceFoundation/HEDAP/issues/401

**Comment by robertbwatson** [comment]
@aligeez  If this is a dupe, can it be closed?

**Comment by aligeez** [comment]
Resolved this with the release of Program Plans and Plan Requirements on June 26, 2017.
