### ISSUE TITLE
MCMP Story 8.0: Update the status of Program Plan when new Primary is selected

### ISSUE THREAD

**Issue by aligeez** [SalesforceFoundation/EDA#604]
Currently the status of "Current" does not change on the Program Plan when a new Primary Program Plan is assigned for the same Account, This should update the newly elected Program Plan as "Current" and make the other ones "former".

**User Acceptance Criteria:**
1.0 - Go to an existing Account (Academic Program) and add a Program Plan as primary (if it does not already have one). Save.
1.1 - Observe that the newly elected Program Plan is set as "current" on the Account. 
2.0 - Then go back to the same Account and change the Primary Plan to a different one. 
2.1 - Observe that the status of the newly elected plan is updated to "Current".

**Comment by aligeez** [comment]
@ceiroa - this already exists as WI - W-024568, apologies for creating them out of order, i still don't have Lurch capabilities. Can you please link these?

**Comment by ceiroa** [comment]
**lurch: attach W-024568

**Comment by j-brandolini** [comment]
I have a couple of clarifying questions on this one:

1) I assume if a new/different Program Plan associated with an Account is marked as "Current", then it would uncheck the "Is Primary: indicator on the other Program Plans also associated with that Account [Should only be more than one in merge or prior data scenario].
2) Should it leave the Status set to  "Current" on the records it is removing the "Is Primary" indicator from, or should it also set the Status to "Archived"?
3) Should there only ever be one "Current" Program Plan, and should any others should associated with the same Account always be "Archived"?  In that case, Current also means "Is Primary" right?  If the record's status  is changed to "Archived", should it also uncheck the "Is Primary" indicator?  

If the "Is Primary" indicator is essentially always dependent on the Status, recommend adding "Before" Trigger events to maintain the field values:
- New Records
-- If Status == Current, set "Is Primary" to true (checked)
-- Else set "Is Primary" to false (unchecked)
- Updated Records
-- If (New Status != Old Status) and (Status == Current), set Primary to true (checked)
-- Else If (New Status != Old Status) and (Status != Current) set Primary to false (unchecked)

BeforeInsert/BeforeUpdate trigger to maintain the Primary indicator and set it based on changes to the Status field, and it's current value.  

AfterInsert/AfterUpdate would handle cleaning up the other Program Plan records related to that same Account, setting them to Archived, if that is the desired result.  Should this cleanup only trigger on a Status value change (meaning a save of the Program Plan would cause it to look again if Status = Current), or should it only recheck if the status value actually changes to Current (or is a new record)?

Finally, is a batch/cleanup job needed to cover merged records, and initial data, or is it safer to assume they will clean this up manually?

Thanks for any clarifications you can provide!

**Comment by aligeez** [comment]
Hi @j-brandolini - I will attempt to answer these, but @kevinswiggum , please correct me if I am incorrect at any point. My replies in **bold**:

1. I assume if a new/different Program Plan associated with an Account is marked as "Current", then it would uncheck the "Is Primary: indicator on the other Program Plans also associated with that Account [Should only be more than one in merge or prior data scenario].
- **Correct.** 

2. Should it leave the Status set to "Current" on the records it is removing the "Is Primary" indicator from, or should it also set the Status to "Archived"?
 - **I believe it should simply remove the "Is Primary", but not Archive it. There could be scenarios where a student is a dual major or has a minor and they still need to be affiliated with that Program, it's just not their Primary concentration.** 

3. Should there only ever be one "Current" Program Plan, and should any others should associated with the same Account always be "Archived"? In that case, Current also means "Is Primary" right? If the record's status is changed to "Archived", should it also uncheck the "Is Primary" indicator?
- **I believe the same scenario I described above (Dual major, major + minor) addresses this scenario as well. Let me know if it's still unclear.** 

I defer to @kevinswiggum on the "BeforeInsert/BeforeUpdate trigger" question, but based off my understanding I think you have it right. 

As for the batch cleanup job, I see that as a 'nice to have', not a 'must have'.  We should create a new Work Item for that feature and get it in the backlog.  Thanks!

**Comment by j-brandolini** [comment]
If more than one should be current, but only one should be primary, I think the logic is probably:

* Set Status to Current, if plan now has “Is Primary” checked
* Uncheck “Is Primary” from other plans associated with the same account

This is pretty straightforward.

John

**Comment by j-brandolini** [comment]
Or could two be primary (dual major) in which case, the only requirement is to make it Current if "Is Primary" is checked?

**Comment by aligeez** [comment]
I think in speaking with @kevinswiggum about this in the past, there can only be one primary, even in the scenario with a dual major. Logically, you are correct.

**Comment by robertbwatson** [comment]
@j-brandolini Since the associated work item was marked as Closed/Never, is it okay to close this issue?

**Comment by j-brandolini** [comment]
If you haven’t already, yes.

**Comment by ceiroa** [comment]
@j-brandolini For the future, please keep in mind that "Addresses" is not included in the list of keywords that will automatically close an item when the PR including it gets merged.

The keywords, from https://help.github.com/en/articles/closing-issues-using-keywords, are:
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved

**Comment by j-brandolini** [comment]
This was from my open source contributions before I started...
