### ISSUE TITLE
Broken links in apexdocs

### ISSUE THREAD

**Issue by sam-knox** [SalesforceFoundation/EDA#620]
There's a bug in the buildout of the apexdocs for HEDA. Notice that if you click on the name of the class itself you get a 404.

The URLs look like this:
http://developer.salesforce.org/HEDAP/ApexDocumentation/CON_DoNotContact_TDTM.cls#L37

and should probably look like this:
https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/CON_DoNotContact_TDTM.cls

**Comment by aligeez** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQBKQA2" target="_blank">W-030291</a>
