### ISSUE TITLE
HEDA Idea: Emergency Contacts

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#636]
HEDA Idea: [Emergency Contacts](https://powerofus.force.com/hub-ideas/1354)
Created by: [Stewart Anderson (EMEA SE - Salesforce.org)](https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=0058000000CcVttAAF&tab=sfdc.ProfilePlatformOverview)

**Idea:**

It would be great if we could be able to see "at a glance" who needs to be contacted in an emergency should something happen to a student. It would also be great to not have to figure out who should be contacted in some of our more complex family relationships where one parent or guardian should be contacted before another. So potentially utilize the Relationships within HEDA and add the option to have primary and secondary points of contact and then an Emergency button which shows a model window with the contact details of the primary and secondary contacts with their phone number and email.

**Comment by jacebryan** [comment]
**lurch: add

**Comment by ceiroa** [comment]
We could leverage the existing "Emergency Contact" checkbox field on Relationship: https://github.com/SalesforceFoundation/HEDAP/blob/a94786e57fd710866ff9d877b70cfde9a574227e/src/objects/Relationship__c.object#L96

**Comment by jacebryan** [comment]
Definitely. The only thing that is lacking on the Relationship object is the ability to identify which Emergency Contact is the actual Primary and Secondary Contacts. For example: you could have 4 Relationships tied to a Contact and all 4 be marked as an Emergency Contact. Considering you can set a Type when creating the Relationships maybe we can, as part of the investigation, look at adding a Primary Emergency Contact and Secondary Emergency Contact checkbox to the Relationship Reciprocal Settings in order to identify which contact should be contacted first in an emergency situation.

**Comment by lifewithryan** [comment]
Could you add an emergency contact numeric sort field and have said modal sort by that.

**Comment by jacebryan** [comment]
It is possible to do this as an admin w/out the need for further development in HEDA.

Here is what I did:

- **Create the following custom fields on the Contact Object:**

![image](https://user-images.githubusercontent.com/25934611/44538676-b0d12780-a6c7-11e8-8e58-92f3fd1a5b9e.png)

**Here are the formulas used for 4 of the custom fields:**

Primary Emergency Contact Email: Primary_Emergency_Contact__r.Email
Primary Emergency Contact Phone Number: Primary_Emergency_Contact__r.Phone
Secondary Emergency Contact Email: Secondary_Emergency_Contact__r.Email
Secondary Emergency Contact Phone Number: Secondary_Emergency_Contact__r.Phone

- **Add new custom fields to the HEDA Compact Layout on Contact**

![image](https://user-images.githubusercontent.com/25934611/44538911-51bfe280-a6c8-11e8-88e3-766e47a99042.png)

- **Create a Process Builder that includes the following steps. Then Activate:**

![image](https://user-images.githubusercontent.com/25934611/44539069-d3b00b80-a6c8-11e8-99e5-09c1931b0aa7.png)

![image](https://user-images.githubusercontent.com/25934611/44539089-e296be00-a6c8-11e8-9b60-89249fa4011a.png)

![image](https://user-images.githubusercontent.com/25934611/44539124-f510f780-a6c8-11e8-98ba-53946a3b27a1.png)

![image](https://user-images.githubusercontent.com/25934611/44539144-06f29a80-a6c9-11e8-844d-5444589b9d64.png)

- **Create 2 Relationships on a single Contact where 1 is marked as Primary and the other is marked as Secondary**
Make sure the Emergency Contact Field is checked on both.

- **Results:**

![image](https://user-images.githubusercontent.com/25934611/44539620-4372c600-a6ca-11e8-8d5f-0a16ebe4c383.png)

**The Issue with going down this route**

Obviously most people may not want to use the Compact Layout in this fashion especially since there is a limit to how many fields can be made visible in Lightning: https://success.salesforce.com/ideaView?id=08730000000cETvAAM

**Alternative Route**

Customers create a lightning component to capture this information and add it to the Contact Record page.

**Comment by jacebryan** [comment]
This issue was reviewed by the HEDA team and marked as a solid candidate for a Community Contribution. Please comment with any questions or concerns you may have. Thank you!

**Comment by Julian88Tex** [comment]
Since you asked, @akouayri this looks like a good issue to work on for EDA :-)

CC @jacebryan & @lifewithryan in case things have changed in the last couple of years.

**Comment by akouayri** [comment]
Thanks @Julian88Tex for tagging me on this, But I think things have changed I don't see those emergence fields on contact so I am not sure if this issue still considered

**Comment by kporray1** [comment]
This GitHub Issue will be closed; please follow this[ Idea in the Trailblazer Community](https://ideas.salesforce.com/s/idea/a0B8W00000GdkA3UAJ/emergency-contacts) for updates.
