### ISSUE TITLE
HEDA Idea: Extend HEDA TDTM Handler to allow for the exclusion by Profile (INVESTIGATION)

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#638]
HEDA Idea: [Change HEDA TDTM Handler to exclude based upon Profile.Name instead of Username
](https://powerofus.force.com/hub-ideas/1391)
Created by: [Corey Snow (Harvard Initiative for Learning and Teaching)](https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=0058000000AwHSD&tab=sfdc.ProfilePlatformFeed)

**Idea:** 

Currently, in the TDTM Trigger Handler records, one can specify a list of Users for which the Triggers will not run in Field: hed__Trigger_Handler__c.hed__Usernames_to_Exclude__c
While perhaps somewhat helpful for testing, Usernames are guaranteed to be unique in every Sandbox, which means these values will not survive within the context of normal change management strategies. This is essentially 'hard-coding' of Usernames. Changing to use User Profile (Profile.Name) for this exclusion would cause the logic to persist across Sandboxes in a 'self-healing' way. Exclusions by Profile for all forms of automation constitute a best practice across the core platform (e.g. Validation Rules, WFRs, Process Builder, Flows, Apex, etc)

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fNE7AAM" target="_blank">W-028016</a>

**Comment by lifewithryan** [comment]
**lurch: detach

**Comment by LurchTheButler** [comment]
Detached null

**Comment by lifewithryan** [comment]
**lurch: detach W-037758

**Comment by lifewithryan** [comment]
**lurch: attach W-037758

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hp6zQAC" target="_blank">W-037758</a>

**Comment by LurchTheButler** [comment]
Detached <a href="https://foundation.my.salesforce.com/a2x1E000001Hp6zQAC" target="_blank">W-037758</a>

**Comment by lifewithryan** [comment]
**lurch: attach W-037758

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hp6zQAC" target="_blank">W-037758</a>
