### ISSUE TITLE
CON_Preferred_TDTM needs to ensure Preferred Phone works the same as Preferred Email

### ISSUE THREAD

**Issue by mshalley** [SalesforceFoundation/EDA#640]
CON_Preferred_TDTM needs to be updated to work the same on Preferred Email AND Preferred Phone.

Right now the Email portion work perfect but the Phone piece does not.

IF you chose lets say 'Work Phone' as the preferred value but have no value in it, the trigger rolls it up to 'Phone' as blank. This is no good.

With the Email version of this, if I said 'Work Email' is preferred but the value was blank, I would atleast get a pop up that says 'Error: The email selected for Preferred Email can't be blank.'.

You need to update the trigger to do the same for Preffered Phone when vlaues blank.  
Please do this asap and push the new code :)

Meghan

**Comment by jacebryan** [comment]
Thank you for reporting this @mshalley.

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fNJvAAM" target="_blank">W-028089</a>

**Comment by jacebryan** [comment]
**Steps to reproduce issue:**

1. Create a Contact with the following fields: First Name, Last Name, Preferred Email = to any value other than 'None'. DO NOT set a value for the email selected.
2. Click Save

Note that you did not receive an error similar to what you would receive if you set Preferred Email to any value other than 'None' and did not set a corresponding value for the email selected for Preferred Email (i.e. "The email selected for Preferred Email can't be blank.")

**What needs to happen:**

When a value is set for Preferred Phone and no value has been set for that phone ensure that an error ("The phone selected for Preferred Phone can't be blank.") is displayed and will not allow the record to be created until a value is entered.

Also include similar functionality in HEDA Settings (Accounts and Contacts) that would allow a customer to "Disable Preferred Phone enforcement (Do not require Contacts to have a Preferred Phone)."

**Comment by jacebryan** [comment]
@aligeez - there is a similar request in the Power of Us Hub: https://powerofus.force.com/hub-ideas/1456

**Comment by AndiMcLaughlin** [comment]
I see that this is marked as closed and was able to test this in our sandbox but still do not see this in our prod instance.  Was the prod release delayed or staggered by org or do I need to manually deploy?

**Comment by lifewithryan** [comment]
> I see that this is marked as closed and was able to test this in our sandbox but still do not see this in our prod instance. Was the prod release delayed or staggered by org or do I need to manually deploy?

@AndiMcLaughlin there should be a setting in EDA Settings to turn this on. Is that setting not in your org?
![Screen Shot 2019-09-13 at 10 57 28 AM](https://user-images.githubusercontent.com/334111/64876699-56c63b80-d615-11e9-9b73-9f20e664d002.png)

**Comment by Julian88Tex** [comment]
@AndiMcLaughlin @lifewithryan There is a little bit more needed for setup referenced in the PR https://github.com/SalesforceFoundation/EDA/pull/869:

> Note: Unchecking the "Do not require Contacts to have a Preferred Phone" checkbox in an existing installation, alone, doesn't enforce the requirement to provide a value for Preferred Phone. You must also access the “Trigger Handlers” tab and make sure "CON_PreferredPhone_TDTM" is set to Active."

**Comment by jacebryan** [comment]
Side note: CCE is investigating this issue to determine why the push was not received. Per the Hub thread located here (https://powerofus.force.com/s/feed/0D51E00004c2hnASAQ) the 1.82 code was not delivered to @AndiMcLaughlin's org. Andi has since used the EDA installer to populate her org with 1.82 code.
