### ISSUE TITLE
Occasional unit test failure for Household naming

### ISSUE THREAD

**Issue by kevinswiggum** [SalesforceFoundation/EDA#649]
I'm running unit tests in a HEDA org (managed package) and found several tests that fail assertions in ACCT_IndvidualAccounts_TEST. In each failure, the expected household name in the assertion has the contact names reversed compared to the actual value stored. 

For example: System.AssertException: Assertion Failed: 
Expected: Testerson1538684791288 (_Test and Test2_) Household, 
Actual: Testerson1538684791288 (_Test2 and Test_) Household

The code that queries the contacts within the household (ACCT_IndividualAccounts_TDTM.updateHHAccountsName) does not sort the Contacts by anything (ID, createdDate, etc) so the unit test in this case is returning the contacts in opposite order. It appears that the test works fine in some orgs and fails in others.

For background, the org where it failed for me has Platform Encryption enabled. I'm not sure if that would influence the default order of query results when there isn't a WHERE clause.

**Comment by kevinswiggum** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fOPLAA2" target="_blank">W-028911</a>

**Comment by jacebryan** [comment]
This issue was reviewed by the HEDA team and marked as a solid candidate for a Community Contribution. Please comment with any questions or concerns you may have. Thank you!

**Comment by jacebryan** [comment]
@ceiroa - is this WI something that we plan to work on internally at some point? Just wanted to check as I thought this would be a Community-Ready WI.

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.
