### ISSUE TITLE
HEDA Tech Debt: Refactor process control method calling

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/EDA#663]
We should call TDTM_ProcessControl.getRecursionFlag() and put the value into a static variable for all TDTM classes implementing HEDA process control. This will improve readability and performance by avoiding calling the same method multiple times.

**Comment by xinnanlisf** [comment]
fyi, @lifewithryan @jbrandolinisf @aligeez @jbrandolinisf

**Comment by xinnanlisf** [comment]
**lurch

**Comment by xinnanlisf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fPUCQA2" target="_blank">W-029716</a>

**Comment by MatthewBlanski** [comment]
Removing TDTM overhauls from our backlog. For now.
