### ISSUE TITLE
Account Naming: [SPIKE] Explore potential performance optimization over naming functions

### ISSUE THREAD

**Issue by aligeez** [SalesforceFoundation/EDA#668]
Related to: https://github.com/SalesforceFoundation/HEDAP/issues/667

This SPIKE will explore any performance impact coming out of the Account Naming work we're tackling in work item #667

**Comment by aligeez** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fPy1QAE" target="_blank">W-030130</a>

**Comment by dgamboni** [comment]
This Work Item Spike was closed Oct 2019, and related GH Issue also closed. Will close this Issue.
