### ISSUE TITLE
MCMP Story 7.0: HEDA Cloning

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/EDA#709]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the HEDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature
* **What is the current behavior?**

* **What is the expected behavior?**
* Cloning any object from record page
* Deep Cloning any object from record page
* **What is the motivation / use case for changing the behavior?**

* **Acceptance Criteria**

  - **Given**: I am on a certain page
  - **When**: I click a button
  - **Then**: An action should occur

* **Keyboard Acceptance Criteria**

  - **Given**: I am navigating the site using only my keyboard
  - **When**: I tab to the button
  - **Then**: I should see the button highlighted on focus
  - **And When**: I press enter on a highlighted button
  - **Then**: An action should occur

* **Screenreader Acceptance Criteria**

  - **Given**: I am using a screenreader to navigate the site
  - **When**: I tab to the button
  - **Then**: I should hear the label of the button
  - **And When**: I press enter
  - **Then**: I should hear that an action has occurred

**Comment by robertbwatson** [comment]
@xinnanlisf  Did we agree that we weren't going to do this in EDA? I can't remember what we decided, but I'm wondering if this should be closed. cc @lifewithryan - thoughts?

**Comment by lifewithryan** [comment]
> @xinnanlisf Did we agree that we weren't going to do this in EDA? I can't remember what we decided, but I'm wondering if this should be closed. cc @lifewithryan - thoughts?

I believe we decided that we weren't going to do any extra logic in EDA to perform the cloning and instead if people wanted something more than what SF provides out of the box we'd point them to the App Exchange.
