### ISSUE TITLE
[HEDA] - Improve UX for Program Enrollment Deletions on Settings > Affiliations Page 

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/EDA#711]
**Feature Request** : Improve UX for Affiliations on Settings Page

**Additional Considerations** : 

- Investigate similar behavior on other HEDA Settings pages, in order to provide a consistent user experience across all the HEDA Settings features.
- Include clearer definition of sections across the Affiliations Settings page, i.e. bolding / text size for headers and sub-headers

**Current Behavior** : It appears that mutually exclusive options (Delete & Status) are selected at the same time. The checkbox for "Delete" is selected, and the Status also reads "Former," leading to confusion. The user to need to read a lot of text to decipher what's going on. 

**Expected Behavior** : Only one option can be selected at a time: Either "Delete Related Affiliation When Deleting Program Enrollment" OR "Change Status of Related Affiliation When Deleting Program Enrollment." If "Delete" is selected, the "Status" drop-down is clearly disabled. 

**Motivation for Change** : The current UX is confusing and can lead to users expecting behavior that is incorrect -- ie, that their deleted Program Enrollments will have Affiliations marked "Former" when they're actually deleted.
 
**Acceptance Criteria**: TBD / To be flushed out during UX evaluation of changes.

- Header "Program Enrollment Deletions" will be bold and in a "large" [TBD] text size
- Sub-Headers will be in a "medium" [TBD] text size
- Text will be in a "small" [TBD] text size
- Include help bubbles [text TBD] for additional explanations
- If "Delete" is not chosen, then the "Status" drop-down will be clearly grayed out / disabled
- "Status" drop-down is only enabled when "Change Status" is chosen

**Keyboard Acceptance Criteria** : TBD / Ensure user can navigate and select all elements via Keyboard

**Screenreader Acceptance Criteria** : TBD / Ensure that when user navigates and selects any element, the screen reader accurately reflects the displayed information to the user.

**Comment by dgamboni** [comment]
***lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007x7CVQAY" target="_blank">W-031269</a>

**Comment by MatthewBlanski** [comment]
This is handled in Summer with Education Cloud Settings!
