### ISSUE TITLE
Enhancement: Allow reparenting of other objects/records to parent objects/records

### ISSUE THREAD

**Issue by aligeez** [SalesforceFoundation/EDA#721]
We recently released the ability to reparent a course offering to a course in [HEDA Release 1.70](https://github.com/SalesforceFoundation/HEDAP/releases/tag/rel/1.70). This started as an idea here: https://powerofus.force.com/hub-ideas/1423 and was delivered via work item #644. 

Subsequently, HEDA users would like this reparenting concept to be applicable to all other objects/records where it makes sense, as explained here: https://powerofus.force.com/0D51E00004kTUmt

Other reparenting on other objects is possible - it's really only an issue when the link is a Master-Detail relationship, which is the case with Course Offering to Term and Course, for example

* **What is the current behavior?**
Only allows reparenting an orphaned Course Offering record with a new or different Course that was not it's original parent. 

* **What is the expected behavior?**
The ability to reparent any child term with a parent term (or any object) where it makes sense. 
* We will allow you to reparent the Term on a Course Offering.
* We will allow you to reparent the Account on a Term.

* **What is the motivation / use case for changing the behavior?**
An upcoming HEDA release will apparently allow reparenting of CourseOfferings to new Course objects.  That's great, but in fact when that happens the Term may also need to be changed.  That is, the Term lookup may need to allow reparenting as well.

* **Acceptance Criteria**
  * On an existing Course Offering, you can now change the Term to another record.
  * On an existing Term, you can now change the Account to another record.

**Comment by aligeez** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008Ll6sQAC" target="_blank">W-031507</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.76 (Beta 7)

**Comment by mrbelvedere** [comment]
Included in production release 1.76
