### ISSUE TITLE
Create Attendance Event Object and Fields

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/EDA#723]
**New HEDA Object:** We are creating object and fields to support attendance events.

* **What is the motivation / use case for changing the behavior?**
An *attendance* event records a student’s presence/participation in either an entire school day, or class period. Can represent both absences as well as tardies. *Attendance* can be assumed if no absence is reported. For our MVP we are focusing on storing *attendance* NOT taking *attendance*. 

Note: This work item will focus on schema only. Logic/Automation are slated for farther down the road. 

* **Acceptance Criteria**
TBD

**Comment by xinnanlisf** [comment]
Hi @aligeez @JasonFitzy, mind if taking a quick review on this Github issue before I lurch it? Thank you!

**Comment by aligeez** [comment]
@xinnanlisf - Good to go now. I edited it a bit.

**Comment by xinnanlisf** [comment]
@aligeez thanks, I will go ahead and lurch.

**Comment by xinnanlisf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008Ll9cQAC" target="_blank">W-031541</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.78 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release 1.78
