### ISSUE TITLE
Enhancement: HEDA Refresh All Household Names option

### ISSUE THREAD

**Issue by aligeez** [SalesforceFoundation/EDA#724]
**New Feature Request for HEDA:** It would be great if HEDA has a similar function to the NPSP Refresh All Household Names option where it updates your Administrative Accounts names to be how you set them up, in case some are not consistent.

**Original Idea Post:** https://powerofus.force.com/hub-ideas/1484

Original Reply from @jacebryan  @SFDO 
Thanks for posting this Idea @Eric Kenney (University of Utah- College of Nursing)! 
HEDA already provides the ability to change the naming format for both Households and Administrative Accounts under HEDA Settings --> System. It sounds like the ask here is for HEDA to include a batch job "option" that could be run to update all pre-existing Households/Administrative Accounts to the newly updated naming convention. Is that correct?
For anyone who isn't familiar with NPSPs Automatic Household Renaming feature here is the documentation that discusses it in more detail: https://powerofus.force.com/articles/Resource/NPSP-Customize-Household-Names (see section: Automatic Household Renaming)

**Eric's Reply:** Yes, a batch update. I have my HEDA settings setup with auto naming, but for some reason any contact created with my application package does not adhere to those rules (separate issue I am working with them directly), but I have a few hundred accounts that don't follow the standard naming conventions. An option to mass update all the Account names that are incorrect would be helpful.

*Acceptance Criteria:*
TBD

**Comment by aligeez** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008Ll9XQAS" target="_blank">W-031540</a>
