### ISSUE TITLE
"Class Period" - new object & relevant fields

### ISSUE THREAD

**Issue by aligeez** [SalesforceFoundation/EDA#732]
**New Feature / Object**

This will be the introduction of a new object in the HEDA framework to track "Class Period". This could be a slot of time where a course offering meets, or a method of dividing an academic day into blocks where Course Offerings would fit.  This work item will focus on just the core object and basic fields (schema only). We aim to keep it as open and flexible as possible to fit all use-cases in academia. 

If you have strong use-cases for this, please feel free to comment.

* **Acceptance Criteria**

TBD

**Comment by aligeez** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LlNPQA0" target="_blank">W-031714</a>
