### ISSUE TITLE
New EDA Object: "Attributes" 

### ISSUE THREAD

**Issue by aligeez** [SalesforceFoundation/EDA#737]
**New Object in EDA Framework**: The purpose of this new object is to allow institutions to track credentials awarded to/earned by their faculty and students (i.e. "Contact"). In addition, the management of credentials (or any attribute) is quite similar to the management of general attributes and characteristics for students and faculty. Therefore, rather than approaching this with a dedicated “Attribute” object, we will be implementing a more general “contact attribute” object. 

* **What is the motivation / use case for changing the behavior?**
In our effort to support P-20 lifelong learning/education commitment. 

* **Acceptance Criteria**
- As an admin I can log into my EDA org and see the new object "Attribute" 
- As an admin I can see the necessary fields included in "Attribute" (see quip doc, formerly named "Credential Management")

**Comment by aligeez** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LlSUQA0" target="_blank">W-031777</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.78 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release 1.78
