### ISSUE TITLE
False/Misleading Debug Log Error

### ISSUE THREAD

**Issue by kevinswiggum** [SalesforceFoundation/EDA#743]
**Do you want to request a *feature* or report a *bug*?**
Neither

* **What is the current behavior?**
If I'm looking at a debug log while creating a Contact, I see a message that looks like a failure in TDTM: 
_EXCEPTION_THROWN|[79]|System.InvalidParameterValueException: Invalid sobject provided. The Schema.describeSObject() methods does not support the Advancement_Setting__mdt sobject as a parameter. The sobject provided does not exist._ 

This is happening because of a check in HEDA to see if the GEM (Gift Entry Manager) is installed. It's doing so by looking for the existence of an object only found in GEM. If not found, an error is thrown, but caught by the code and ignored. However, the debug log still shows the error and doesn't report anywhere that it's not actually a problem.

While an error didn't actually occur, as a I'm led to believe something actually went wrong. This will hamper troubleshooting efforts by customers, partners and CSG since they may focus on this error rather than pursue other causes. Cases will get escalated unnecessarily.

* **What is the expected behavior?**
Ideally this check will not reflect any error in the debug log. Minimally we'd want to at least note that the error can be disregarded. That might be difficult due to limited output in managed packages.

* **What is the motivation / use case for changing the behavior?**
Improve clarity for customers and partners

* **Acceptance Criteria**
HEDA can successfully check for the presence of GEM in the org without throwing a false exception

**Comment by aligeez** [comment]
thanks for logging this @kevinswiggum . We'll bring it into the backlog.

**Comment by aligeez** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LlZLQA0" target="_blank">W-031862</a>

**Comment by bdvorachek** [comment]
Hey @kevinswiggum - The GEM team discussed this internally today. Here's the summary:

* We do not rely on that exception being thrown, it is a side-effect of us searching for the correct dev name of the GEM Custom Settings Object which can be any of: `adv1__Advancement_Settings__c, Advancment_Settings__c, gem__GEM_Settings__c, GEM_Settings__c`. I believe this is the order we look for them currently.
** While searching, exceptions are thrown when we try incorrect object names such as looking for GEM_Settings__c in an org with the managed version of GEM installed.
* What kind of org did you see this happen in? Most of the time debug log messages from managed packages are suppressed. Are customers able to see this message?
* The error happens here - https://github.com/SalesforceFoundation/HEDAP/blob/e785195d07a3ac9e395f27829866005dbdcd5bd0/src/classes/Advancement_Info.cls#L80 . When GEM Goes GA we'll be able to drop half of the checks in that block.
** *A possible fix* - After GEM goes GA, we can update this to look for gem__GEM_Settings__c *first*. We'd find it and then continue on without having an exception thrown.

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.
