### ISSUE TITLE
Attendance Event: Triggers and TDTM Enabled

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/EDA#744]
New feature, related to #723 

* **What is the current behavior?**
N/A

* **What is the expected behavior?**
Triggers and TDTM class setup for Attendance Events

* **What is the motivation / use case for changing the behavior?**

* **Acceptance Criteria**
- Triggers are visible from TDTM area/tab in HEDA
- Ability to Enable/Disable Triggers

**Comment by xinnanlisf** [comment]
Hi @aligeez, I just created this item for attendance triggers and tdtm class creation. Could you take a review before I lurch it? Thanks a lot!

**Comment by aligeez** [comment]
@xinnanlisf - I updated it. You may want to update some of the Acceptance Criteria (if applicable) to include basic things you would test for any new triggers. Also, you can always delete the "Internal Only" part of the new issue template above the "New feature or bug" section. Thanks!

**Comment by xinnanlisf** [comment]
**Lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LlmAQAS" target="_blank">W-032020</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.80 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release 1.80
