### ISSUE TITLE
Term Grades: Add Contact Relationship and Course Connection Logic

### ISSUE THREAD

**Issue by JasonFitzy** [SalesforceFoundation/EDA#766]
As a school I would to be able to directly relate a term grade record to a contact and keep the contact and course connection in sync so that you cannot add a course connection to a different contact that the record is already related to or vice versa. 

 **Acceptance Criteria**

1. Contact look up field on Term Grade
2. I cannot add a course connection not related to the contact on the term grade record
3. I cannot add a contact to the term grade record that does not match the contact on the already related course connection

**Comment by robertbwatson** [comment]
@xinnanlisf  @JasonFitzy This is the issue that was mentioned during today's standup - is it ready to be lurched?

**Comment by JasonFitzy** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LmSVQA0" target="_blank">W-032531</a>
