### ISSUE TITLE
Duplicate Affiliation records are created when an Account record type is changed

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/EDA#781]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
If we update an Account record type from a record type that has Affiliation mapping to a record type that also has Affiliation mapping and this Account has an Affiliation record with a Contact, then the system will create a duplicate Affiliation record.

Example: 
1. Create a Contact
2. Create an Account with Education Institution record type
3. Create a Primary Affiliation between Account and Contact
4. Update Account record type to Business Organization.
5. Duplicate Affiliation records now exist - one as the Primary.

* **What is the expected behavior?**
Duplicate Affiliation records should not be created.

* **What is the motivation / use case for changing the behavior?**
This bug can cause storage issues and data issues in an organization, especially if an Account's record type is changed and that Account has an Affiliation to hundreds/thousands of Contact records.

**Comment by robertbwatson** [comment]
**lurch: attach W-021767

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000097R0mAAE" target="_blank">W-021767</a>

**Comment by jacebryan** [comment]
Issue identified is no longer reproducible. Closing Issue.

**Comment by dgamboni** [comment]
Work Item was missing the step to check the "primary" box when creating the affiliation. Work Item has updated steps in Chatter and has been re-opened.

**Comment by mrbelvedere** [comment]
Included in beta release 1.78 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release 1.78
