### ISSUE TITLE
EDA Settings title shows "hed__Settings" instead of "EDA Settings" or the translated value

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/EDA#782]
* **Do you want to request a *feature* or report a *bug*?**
Enhancement

* **What is the current behavior?**
When you navigate to the EDA Settings, the title in the tab/window of the browser shows "hed__Settings" 

* **What is the expected behavior?**
Since we are on the EDA Settings page, something like "EDA Settings" (or the translated value) would be more friendly and make more sense here.

* **What is the motivation / use case for changing the behavior?**
If we are able to display the "EDA Settings" custom label, it will be consistent with the title shown in the UI.

**Comment by robertbwatson** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087uPcQAI" target="_blank">W-032837</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.76 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release 1.76
