### ISSUE TITLE
Add reentrancy flags to PREN_Affiliation_TDTM

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/EDA#785]
As part of our reentrancy work, we should add reentrancy flags to the PREN_Affiliation_TDTM class to prevent recursion into the trigger.

**Comment by robertbwatson** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087uUDQAY" target="_blank">W-032892</a>

**Comment by robertbwatson** [comment]
I created this ticket a few weeks ago because I thought the PREN_Affiliation_TDTM class was missing reentrancy checks. However, due to the nature of the class I don't think they are necessary. Here's why:
- PREN_Affiliation_TDTM only runs on before insert and after delete.
- The class only inserts, updates, and deletes Affiliation records.
- In order for those Affiliation records to cause the PREN_Affiliation_TDTM class to run again, there would need to be an Affiliation TDTM class that inserts new PE records or deletes other PE records. There is no possible way for the PREN_Affiliation_TDTM class to iterate over the same records it just processed - you can't re-insert the same records or re-delete the same records. *There might only be a reentrancy problem if the class ran in an update context, but it doesn't.*
