### ISSUE TITLE
Test lurch T-15920

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/EDA#789]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Acceptance Criteria**

  - **Given**: I am on a certain page
  - **When**: I click a button
  - **Then**: An action should occur

* **Keyboard Acceptance Criteria**

  - **Given**: I am navigating the site using only my keyboard
  - **When**: I tab to the button
  - **Then**: I should see the button highlighted on focus
  - **And When**: I press enter on a highlighted button
  - **Then**: An action should occur

* **Screenreader Acceptance Criteria**

  - **Given**: I am using a screenreader to navigate the site
  - **When**: I tab to the button
  - **Then**: I should hear the label of the button
  - **And When**: I press enter
  - **Then**: I should hear that an action has occurred

**Comment by skosgi1** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087uY0QAI" target="_blank">W-032940</a>

**Comment by robertbwatson** [comment]
@skosgi1 Can this be closed? (Maybe deleted, but not sure if that's possible)

**Comment by skosgi1** [comment]
@robertbwatson Closed it, but looks like I do not have access to delete.
