### ISSUE TITLE
For Relationship Autocreation, Campaign Types should only be required when the Object is CampaignMember

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/EDA#794]
* **Do you want to request a *feature* or report a *bug*?**
Enhancement

* **What is the current behavior?**
When creating a new Relationship Autocreation setting under EDA Settings | Relationships | Autocreation, you are forced to specify a value in the Campaign Types field, even if you are creating a new setting for the Contact.

* **What is the expected behavior?**
Ideally, the Campaign Types field would only be required if the Object is set to CampaignMember.

* **What is the motivation / use case for changing the behavior?**
Not having this required would make setting up autocreation settings more intuitive. Right now, a user has to enter in a fake value.

**Comment by robertbwatson** [comment]
@aligeez  I didn't lurch this yet because I think we were going to start lurching issues only during backlog grooming. Can we review this on Tuesday?

**Comment by aligeez** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vKUQAY" target="_blank">W-033542</a>

**Comment by MatthewBlanski** [comment]
Resolved in Summer with Education Cloud Settings!
