### ISSUE TITLE
Add Start and End Times to Course Offering Schedule

### ISSUE THREAD

**Issue by lifewithryan** [SalesforceFoundation/EDA#796]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature
* **What is the current behavior?**
Currently Time Block and Course Offering Schedule are separate objects in order to be as flexible as possible when tracking the various ways a class schedule can be built. However, in situations where leveraging Time Block seems like unnecessary overhead we would like to add Start and End Time fields directly to Course Offering Schedule and NOT leverage the Time Block object.

* **What is the expected behavior?**
I should be able to add start and end times to Course Offering Schedule if I am not leveraging the Time Block object. In cases where I am using Time Blocks, trigger logic should copy the start and end times from that time block into the Course Offering Schedule fields.

* **What is the motivation / use case for changing the behavior?**
Adding the Start & End Times to EDAs Course Offering Schedule allows customers to track the schedules for a given course offering directly with the schedule object rather than having to have time blocks that represent all of the various times that could exist in higher ed. However, it still allows for the simpler class schedules where day of week doesn't matter and only time of day is needed which saves on record count since a course offering could lookup to the time block directly as well.

* **Acceptance Criteria**

-**Given**: a course offering in an org where I am not leveraging time blocks 
-**When**: I create a Course Offering Schedule
-**Then**: I should be able to specify a start and end time and specific days of the week

-**Given**: a course offering in an org where I leverage time blocks 
-**When**: I create a Course Offering Schedule that looks up to a time block
-**Then**: It should automatically populate the Start and End times of the Course Offering Schedule based on the Start and End times of the related Time Block record.

**Comment by lifewithryan** [comment]
**lurch: add

**Comment by lifewithryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087uuLQAQ" target="_blank">W-033216</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087uuVQAQ" target="_blank">W-033218</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.79 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release 1.79
