### ISSUE TITLE
K12 Kit - [Spike]Investigate how to handle grade levels for K-12

### ISSUE THREAD

**Issue by JasonFitzy** [SalesforceFoundation/EDA#797]
**Background**: Grade Levels are used across K-12 schools for various things. In our org Credential Attribute (K-12 Kit only), Educational Institute Accounts (K-12 Kit only), and Contacts all have a need to capture some grade level information. Credentials and Educational Institute Accounts could have multiple related grade levels. Student Contact is related to 1 grade level and it is possible for faculty contacts to be related to multiple grade levels if an org wants to do that, but not primary use case.

**Comment by JasonFitzy** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087usUQAQ" target="_blank">W-033192</a>

**Comment by robertbwatson** [comment]
@lifewithryan It looks like this was created for the K-12 Kit grade levels spike - I'm going to go ahead and close this out since there's no code related to this at this time (& would likely not be in this repo either)
