### ISSUE TITLE
New Field on Contact "Preferred Name"

### ISSUE THREAD

**Issue by JasonFitzy** [SalesforceFoundation/EDA#807]
As an educational organization I would like the option to use a "Preferred Name" field on Contact so that we can recognize Contacts as they choose, but still maintain records of their legal name.

Acceptance Criteria

1. There is a "Preferred Name" field on Contact
2. The field is not added to a page layout

**Comment by JasonFitzy** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087v2FQAQ" target="_blank">W-033313</a>
