### ISSUE TITLE
New Field on Contact "Gender Identity"

### ISSUE THREAD

**Issue by JasonFitzy** [SalesforceFoundation/EDA#808]
As an educational organization I would like the option to use a "Gender Identity" picklist field on Contact in order to support a Contact's ability to define the way they identify in cases where their gender identity doesn't match their biological sex assigned at birth (Gender), while still maintaining records of their biological (legal) Gender.

Acceptance Criteria

There is a "Gender Identity" picklist field on Contact

Field Definition: A personal sense of one's own gender that is not defined by the gender assigned at birth

EDA Picklist Values:
- Identifies as a Man
- Identifies as a Woman
- Identifies as Non-Binary

K-12 Picklist Values:
- Identifies as a Boy
- Identifies as a Girl
- Identifies as Non-Binary

The picklist is not added to the page layout

**Comment by JasonFitzy** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087v2KQAQ" target="_blank">W-033314</a>

**Comment by JasonFitzy** [comment]
GUS Work Item: - [W-8071945](https://gus.lightning.force.com/a07B0000008d2U0IAI)

**Comment by kporray1** [comment]
This issue was partially delivered with Chosen Full Name field and with the Decline to state picklist option for Gender attribute on Contact, and will be closed.
