### ISSUE TITLE
MCMP Prevent Nested Plan Reqs from linking to Parent Plan

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/EDA#812]
Update 5/29/2019:
MCMP wants to ensure the Plan Requirements that descend from a given Program Plan can't be associated with a different Program Plan from its parent/grandparent(s). 

Analysis

RE: MCMP ticket -- off the top of my head:

1. Create Program Plan (via the UI)
2. Create Program Plan Requirement (via the UI)
3. Select Program Plan for the requirement (via the UI) *(Optional)*
4. CODE: Since this is the first plan requirement, its Plan_Requirement__c field should be blank, so exit, there's nothing for us to enforce.
5. Now create a CHILD requirement from the first plan requirement. (via the UI)
6.  This is a CHILD of the first Plan Requirement (its Plan_Requirement__c field is not blank)
7. 5/21 Update: CODE: Since this is a CHILD of the first Plan Requirement, Program Plan must not be populated if the new setting is enabled.

Outdated:

Description: 
Regardless of where a "Plan Requirement" falls (either parent requirement or a child requirement in a thread of requirements), at the end of the day should only roll up to ONE "Program Plan". This creates less confusion in the long-run and makes the use-case of the deep clone more valid. This is cleaner to handle architecturally and makes the Deep Clone feature more useful/efficient. 

This work in this ticket should make sure an Admin cannot affiliate the same Plan Requirement record (ex: Biology 101a) to both the "Bachelors in Biology" program plan and the "Biomedical Engineering" program plan. Each program plan would have it's own. If they attempt to affiliate the same plan requirement with 2 different program plans, it would be nice if they received an error message along the lines of "You cannot affiliate the same plan requirement with 2 different Program Plans, would you like to clone this requirement?" (this latter part is a nice-to-have, not a must-have).

Acceptance Criteria:
1.) As an Admin you attempt to take an existing Plan Requirement and affiliate it with 2 (or more) different Program Plans. Should not be allowed, receive clean error message.
2.) As an Admin you attempt to create a new Plan Requirement and affiliate it with 2 (or more) Program Plans. Should not be allowed, receive clean error message.

**Comment by xinnanlisf** [comment]
**lurch: attach W-026118

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYBgsAAH" target="_blank">W-026118</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.79 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release 1.79
