### ISSUE TITLE
[Tech Debt] Use custom label for the tabs in EDA setting page

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/EDA#815]
We should rework the tab titles in EDA setting page by using custom labels instead of hardcoded strings for the purpose of translation use. This is a tech debt item.

**Comment by xinnanlisf** [comment]
@aligeez just created this github issue for reworking tab titles in EDA setting page. Would you mind taking a quick look before I lurch it? Let me know if need any more info from me!

**Comment by aligeez** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vKTQAY" target="_blank">W-033541</a>

**Comment by MatthewBlanski** [comment]
This was resolved in Summer with Education Cloud Settings!
