### ISSUE TITLE
Account Record Type change to non-mapped record type results in null pointer exception error

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/EDA#820]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
If we update an account record type from a record type that has an affiliation mapping to a record type that does not have an affiliation mapping and this account has a primary affiliation connection with a contact, then the system will throw a null pointer exception when saving.

* **What is the expected behavior?**
A null pointer exception should not be thrown.

* **What is the motivation / use case for changing the behavior?**
Users should be able to change the account record type successfully

* **Acceptance Criteria**
1. Create a Contact
2. Create an Account with Department record type - this record type should exist in the Affiliation Mappings in the EDA Settings
3. Create a Primary Affiliation between Account and Contact
4. Update Account record type to Business Organization - this record type should NOT exist in the Affiliation Mappings in the EDA Settings
5. System should NOT throw an exception

**Comment by robertbwatson** [comment]
**lurch: attach W-021765

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000097QzqAAE" target="_blank">W-021765</a>

**Comment by jstvz** [comment]
Included in beta release 1.79 (Beta 8)

**Comment by mrbelvedere** [comment]
Included in production release 1.79
