### ISSUE TITLE
EDA - List Views - Change "Primary Program Plan" to "Primary Program Plans"

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/EDA#822]
Description : EDA has some list views available. The one called 'Primary Program Plan' is missing an 's' at the end and should be pluralized :  'Primary Program Plans'" 

Note : Update the label to "Primary Program Plans" but NOT the API name -- the API name should stay the same.

Steps & A/C's
1. From EDA App, click the right arrow next to the "Program Plan" tab to see the list views available
2. Confirm that the List View is named "Primary Program Plans"
3. Select the List View "Primary Program Plans"
4. Select "Rename"
5. Confirm the API name is still "Primary_Program_Plan"

~~~~~~
Do you want to request a *feature* or report a *bug*?
--> Bug

What is the current behavior?
--> Improper pluralization for the list view : "Primary Program Plan"

What is the expected behavior?
--> Proper pluralization for the list view : "Primary Program Plans"

What is the motivation / use case for changing the behavior?
--> Quality, reputatation

Acceptance Criteria
Given: I select the drop-down arrow next to the Primary Program Plan tab
When: I read the text
Then: One list name should be "Primary Program Plans"

Given: I select the list called "Primary Program Plans"
When: I click "Rename"
Then: The API name should still be "Primary_Program_Plan"

Keyboard Acceptance Criteria
n/a at this time

Screenreader Acceptance Criteria
n/a at this time

**Comment by dgamboni** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vrcQAA" target="_blank">W-033947</a>
