### ISSUE TITLE
Null Pointer Exception when trying to upsert Addresses. 

### ISSUE THREAD

**Issue by apfalz** [SalesforceFoundation/EDA#825]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
A bug

* **What is the current behavior?**
When upserting addresses via the bulk api,  a null pointer exception occurs in ADDR_Addresses_TDTM.copyAddressToContact: 
```
hed.TDTM_Address: execution of AfterUpdate
caused by: System.NullPointerException: Attempt to de-reference a null object
Class.hed.ADDR_Addresses_TDTM.copyAddressToContact: line 457, column 1
Class.hed.ADDR_Addresses_TDTM.refreshParentAndSiblings: line 352, column 1
Class.hed.ADDR_Addresses_TDTM.run: line 186, column 1
Class.hed.TDTM_TriggerHandler.runClass: line 145, column 1
Class.hed.TDTM_TriggerHandler.run: line 75, column 1
Class.hed.TDTM_Global_API.run: line 61, column 1
Trigger.hed.TDTM_Address: line 33, column 1
```

I can demonstrate that the issue is not related to the data being passed to the Salesforce bulk api.  A batch of records that failed because of the above error can be passed again, and the upsert will complete successfully. I cannot determine why some records are failing, and others are succeeding. 

In the EDA code, a map is created. This map is passed to another method. When the values are retrieved from the map, the null pointer exception occurs. 

* **What is the expected behavior?**
To successfully upsert the record. 

* **What is the motivation / use case for changing the behavior?**
Need to insert data to Salesforce instance. 

* **Acceptance Criteria**

  - **Given**: I extract and prepare data 
  - **When**: I attempt to load it with bulk api
  - **Then**: upserts will not intermittently fail.

**Comment by robertbwatson** [comment]
I've only had a few minutes to look into this so far, but it looks as though it might be failing if there are contacts included in the address update that aren't associated to an Account for some reason. (I could be wrong - need to do more digging here.)

FYI @aligeez @jacebryan

**Comment by apfalz** [comment]
If we insert a contact and then with a few seconds insert an address and relate it to the contact, is it possible that the account isn't finished being processed? And hence cause the null pointer exception.

**Comment by apfalz** [comment]
We opened a ticket with Salesforce and were able to fix the problem. It was related to a setting for Household Account recordtype. We're not using the Household recordtype at all, but somehow something related to how those accounts are handled caused the error.
