### ISSUE TITLE
Clear primary affiliation after account's record type is changed to one with no Affiliation Mapping

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/EDA#827]
Previously when an account's record type (which has a primary affiliation eg-'Primary Department' with a contact) is changed to lets say from "University Department" to the one which doesn't have any affiliation mappings in 'EDA Settings' lets say "Sports Organization" a Null Pointer Exception had been thrown. However, after the fix the "Primary Department" on the contact would still value pointing to the account but now the record type is "Sports organization". This value needs to be cleared.

* **Acceptance Criteria**
If we update an account record type from a record type that has an affiliation mapping to a record type that does not have an affiliation mapping and this account has a primary affiliation connection with a contact, then system shouldn't throw a null pointer exception when saving and the old primary affiliation should be cleared.

Steps:

1. Create a Contact
2. Create an Account with Department record type - this record type should exist in the Affiliation Mappings in the EDA Settings
3. Create a Primary Affiliation between Account and Contact
4. Update Account record type to Business Organization - this record type should NOT exist in the Affiliation Mappings in the EDA Settings
5. System should not throws an exception
6. The primary department field should be cleared

**Comment by ceiroa** [comment]
Remember to lurch-attach this one, @skosgi1!

**Comment by skosgi1** [comment]
**lurch: attach W-033954

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vsBQAQ" target="_blank">W-033954</a>

**Comment by skosgi1** [comment]
Update: The issue is to be fixed with the fix to the issue <a href="https://github.com/SalesforceFoundation/EDA/issues/820#issuecomment-499705630">#820</a>

**Comment by skosgi1** [comment]
closing issue as the fix would be a part of the fix to issue <a href="https://github.com/SalesforceFoundation/EDA/issues/820#issuecomment-499705630">#820</a>
