### ISSUE TITLE
Multiple affiliations to the same Business Organization prevent Primary field on Contact from updating

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#831]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**

As reported in this Hub thread: https://powerofus.force.com/s/question/0D51E00004pvoHqSAI/problem-with-mutliple-affiliations-to-the-same-business-organization

1. Create a Contact
2. Create an Affiliation to a Business Organization, set a Role, and select Primary. Save.
3. Confirm Primary field on Contact is populated
4. Create another Affiliation to the same Business Organization for the same Contact, set a new Role, and select Primary. Save
5. Confirm Primary field on Contact is blank

* **What is the expected behavior?**

1. Create a Contact
2. Create an Affiliation to a Business Organization, set a Role, and select Primary. Save.
3. Confirm Primary field on Contact is populated
4. Create another Affiliation to the same Business Organization for the same Contact, set a new Role, and select Primary. Save
5. Confirm Primary field on Contact is updated with the Primary Business Organization

* **What is the motivation / use case for changing the behavior?**

This is a bug.

* **Acceptance Criteria**

  - **Given**: I am on a certain page
  - **When**: I click a button
  - **Then**: An action should occur

* **Keyboard Acceptance Criteria**

  - **Given**: I am navigating the site using only my keyboard
  - **When**: I tab to the button
  - **Then**: I should see the button highlighted on focus
  - **And When**: I press enter on a highlighted button
  - **Then**: An action should occur

* **Screenreader Acceptance Criteria**

  - **Given**: I am using a screenreader to navigate the site
  - **When**: I tab to the button
  - **Then**: I should hear the label of the button
  - **And When**: I press enter
  - **Then**: I should hear that an action has occurred

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C6lrQAC" target="_blank">W-034024</a>
