### ISSUE TITLE
New Field on Contact "Personal Gender Pronoun"

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#832]
As an educational organization I would like the option to define Personal Gender Pronouns (PGPs) in order to support a Contact's ability to self-identify.

Having this feature will allow for 2 things:

1. Support correct usage of Personal Gender Pronouns (PGPs) when communicating with Students, Guardians, Faculty, Staff and Donors. Gender Identity can be used alongside a PGP to tell a story about the Contact.

For example: Astro Identifies as Non-Binary and goes by the pronouns They/Them/Theirs.

2. Supports the ability for an EDA customer to introduce the correct use of Pronouns (Object, Subject, Possessive, and Reflexive ) when using Merge fields.

**Acceptance Criteria**

There is a "Personal Gender Pronoun" picklist field on Contact

EDA Picklist Values:

- He/Him/His
- She/Her/Hers
- They/Them/Theirs
- Prefer not to answer

The picklist is not added to a page layout
***
### Use Cases for Object, Subject, Possessive, and Reflexive Pronouns

**Pronoun: She/Her/Hers**
Subject Pronoun: She
Object Pronoun: Her
Possessive Pronoun: Hers
Reflexive Pronoun: Herself

**Potential outcome of Merge Fields**

Jamie's efforts have earned **her** the high achievement award!
As long as **she** is unable to attend the ceremony we can mail the certificate home.
Since the award is **hers** **she** can pick it up anytime in Student Services.
**She** should think highly of **Herself** for doing such an amazing job this year.

**Pronoun: He/Him/His**
Subject Pronoun: He
Object Pronoun: Him
Possessive Pronoun: His
Reflexive Pronoun: Himself

**Potential outcome of Merge Fields**

Jamie's efforts have earned **him** the high achievement award!
Since **he** is unable to attend the ceremony we can mail the certificate home.
Since the award is **his** **he** can pick it up anytime in Student Services.
**He** should think highly of **Himself** for doing such an amazing job this year.

**Pronoun: They/Them/Theirs**
Subject Pronoun: They
Object Pronoun: Them
Possessive Pronoun: Theirs
Reflexive Pronoun: Themself

**Potential outcome of Merge Fields**

Jamie's efforts have earned **them** the high achievement award!
As long as **they** are unable to attend the ceremony we can mail the certificate home.
Since the award is **theirs** **they** can pick it up anytime in Student Services.
**They** should think highly of **Themself** for doing such an amazing job this year.
***

### Formulas to populate Object, Subject, Possessive, and Reflexive Pronouns

**Subject Pronoun** 
CASE( hed__Personal_Gender_Pronoun__c , "He/Him/His", "He", "She/Her/Hers", "She", "They/Them/Theirs", "They", "Prefer not to say", "They", "")

**Object Pronoun**
CASE( hed__Subject_Pronoun__c , "He", "Him", "She", "Her", "They", "Them", "Prefer not to answer", "They", "")

**Possessive Pronoun**
CASE( hed__Subject_Pronoun__c , "He", "His", "She", "Hers", "They", "Theirs","Prefer not to answer", "Theirs", "")

**Reflexive Pronoun**
CASE( hed__Subject_Pronoun__c , "She", "Herself", "He", "Himself", "Themself")

**Comment by jacebryan** [comment]
**lurch: add

**Comment by jacebryan** [comment]
To get a better idea here is an image for reference
![Pronouns](https://user-images.githubusercontent.com/25934611/60137870-e7efe980-976d-11e9-8203-c128bf91e1fb.jpg)

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C6pFQAS" target="_blank">W-034067</a>

**Comment by lifewithryan** [comment]
@jacebryan I notice this is flagged as the "Equality Pack" -- is there any reason we wouldn't want to just add this to EDA directly? I think this is important enough to be part of EDA rather than an add on. Thoughts?

**Comment by kporray1** [comment]
This issue was partially delivered with Chosen Full Name field and with the Decline to state picklist option for Gender attribute on Contact, and will be closed.
