### ISSUE TITLE
Fix Null Pointer Exception caused when an affiliation with no contact is deleted

### ISSUE THREAD

**Issue by skosgi1** [SalesforceFoundation/EDA#834]
* **What is the current behavior?**
Currently when an affiliation is deleted with no contact there is a Null pointer Exception and a message is displayed to the user - "There's a problem saving this record. You might not have permission to edit it, or it might have been deleted or archived. Contact your administrator for help." The error can replicated by following the below steps:

1) Create an account
2) Create a Contact
3) Create a primary affiliation between the account and the contact
4) Update the Affiliation Page layout by making the field 'Contact' not required
5) Clear the value in 'Contact' field
6) Delete the affiliation
The record is not deleted and an error message like "There's a problem saving this record. You might not have permission to edit it, or it might have been deleted or archived. Contact your administrator for help." is seen.

* **Acceptance Criteria**
The user should not see the error message when the following steps are done:

1) Create an account
2) Create a Contact
3) Create a primary affiliation between the account and the contact
4)Update the Affiliation Page layout by making the field 'Contact' not required
5) Clear the value in 'Contact' field
6) Delete the affiliation
The record should be deleted and no error messages like "There's a problem saving this record. You might not have permission to edit it, or it might have been deleted or archived. Contact your administrator for help." should be seen.

**Comment by skosgi1** [comment]
**lurch: attach W-033715

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vZ4QAI" target="_blank">W-033715</a>

**Comment by jstvz** [comment]
Included in beta release 1.79 (Beta 8)

**Comment by mrbelvedere** [comment]
Included in production release 1.79
