### ISSUE TITLE
When the last Contact of a Household is marked as Deceased, their name is removed from the Household Account

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#839]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
INVESTIGATION (originally reported in the Hub): https://powerofus.force.com/s/idea/a1W1E000004FQSkUAO/deceased-household

* **What is the current behavior?**
The following conditions have to be met in order to recreate the issue: 

Default Account Model = Household
Automatic Household Naming is checked (true) 

1. Create a Contact. You now have a single Contact for that Household (ex: Jane Doe Household). 
1. Update the Contact and set Deceased = true. Save.
1. Their name is now removed from the Household (ex: "Jane Doe Household" updates to "Household". Jane Does is now associated with "Household".

* **What is the expected behavior?**

EDA should enforce that, unless there are multiple Contacts associated to the Household, the Household name not be renamed to "Household".

* **What is the motivation / use case for changing the behavior?**

When you have a bunch of single Contact household, you end up with a bunch of Account records that are now just named "Household".

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C76BQAS" target="_blank">W-034159</a>
