### ISSUE TITLE
Additional picklist values needed for Attribute object

### ISSUE THREAD

**Issue by lifewithryan** [SalesforceFoundation/EDA#845]
The Attribute object currently contains a small list of attributes that are available by default. K12 use cases have several more that need to be added:

    1. Asylee
    2. Economically Disadvantaged
    3. English Learners
    4. Foster Care 
    5. Free Lunch
    6. Homeless 
    7. Immigrant 
    8. Parent in Military 
    9. Pregnant 
    10. Reduced Price Lunch
    11. Refugee 
    12. Section 504 Handicapped

**Comment by lifewithryan** [comment]
**lurch: attach W-033228

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087uvJQAQ" target="_blank">W-033228</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.79 (Beta 10)

**Comment by mrbelvedere** [comment]
Included in production release 1.79
