### ISSUE TITLE
Attendance needs two additional picklist values

### ISSUE THREAD

**Issue by lifewithryan** [SalesforceFoundation/EDA#846]
Attendance as it currently is implemented only has two picklist values to choose from "Class Absence" and "Class Tardy" which apply mainly to higher education institutions. K12 however needs to represent the concept of missing the entire day of instruction or being late to the start of the school day. We will add the following:

Day Absence
Day Tardy

**Comment by lifewithryan** [comment]
**lurch:attach W-033927

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vq0QAA" target="_blank">W-033927</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.79 (Beta 7)

**Comment by mrbelvedere** [comment]
Included in production release 1.79
