### ISSUE TITLE
EDA - For Self-Referential Lookups, Replace Platform Error Message with Friendly Error Message 

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/EDA#849]
Do you want to request a *feature* or report a *bug*?
--> Enhancement

What is the current behavior?
--> If a user creates a self-referential lookup (such as Plan Requirement that has the same Parent Program Requirement) the user sees a platform error message ("attempt to violate hierarchy constraints"). 

What is the expected behavior?
--> The user sees a friendly, explanatory error message.

What is the motivation / use case for changing the behavior?
--> A friendly error message will clearly explain the problem and/or the solution, so that the user can clearly understand what to change in order to resolve the error, resulting in improved user experience, higher quality, and more satisfied customers. 

Acceptance Criteria

Given - A user enters a Parent Plan Requirement that is the same as the Plan Requirement  
When - The User clicks "Save"
Then - A friendly error message is given. (Example : "The Parent Plan Requirement can not be the same as the Plan Requirement.)

Given - A user enters a Parent Term that is the same as the Term  
When - The User clicks "Save"
Then - A friendly error message is given. (Example : "The Parent Term can not be the same as the Term.)

Notes to Consider
* Where else in EDA are there self-referential lookups that would need this functionality? 
* Can we test for that condition and throw the error before the platform does?
*  Look for the CIRCULAR_DEPENDENCY exception and handle it in the ERR_ExceptionHandler class
* See line 41 of the ExceptionHandler - we just create a better label. This works if EDA Error Handling is on.
* Doc writers should approve the error messages.

![image](https://user-images.githubusercontent.com/3886084/60624488-433b6080-9d9a-11e9-9f91-ba84ba04c978.png)

![image](https://user-images.githubusercontent.com/3886084/60624499-49c9d800-9d9a-11e9-925e-d0d23307fc9a.png)

**Comment by dgamboni** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C7GQQA0" target="_blank">W-034258</a>

**Comment by kporray1** [comment]
This issue is technically unfeasible and is no longer being considered by the product team.
