### ISSUE TITLE
Relationships: If you change the contact field on the relationship the proper reciprocal relationship record doesn't get updated

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#859]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Steps to duplicate:

1. I created two contacts in a household, Contact A and Contact B. I also created a contact C in another household.
2. I created a relationship on Contact A that was Contact= Contact A and Related Contact = Contact B. Fill in required fields and save.
3. Relationship record gets created successfully and so does a reciprocal relationship record. Everything looks good.
4. Now, in the relationship from step 2- edit it. The system will not allow you to change the related contact field (see screenshot of message) so change the Contact field. Click the X and then change the contact field to Contact C. Keep all other required field values and save.
5. The system allows you to do this, however, there is an outdated reciprocal relationship record that is still linking Contact A to Contact B when it should be linking Contact C to Contact B. 

* **What is the expected behavior?**

Prevent the user from being able to change the Contact field

Display an error message like the one displayed when attempting to change the Related Contact field: _"Rather than change the contacts in an existing relationship, delete this relationship and create a new on between the new contacts"_

* **What is the motivation / use case for changing the behavior?**
Avoid outdated reciprocal relationship records

**Comment by jacebryan** [comment]
**lurch: attach W-034259

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C7GVQA0" target="_blank">W-034259</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.81 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release 1.81
