### ISSUE TITLE
EDA : Fix typos in error message when attempting to edit the Related Contact in a Relationship 

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/EDA#865]
**Do you want to request a *feature* or report a *bug*?**
-BUG

**What is the current behavior?**
-There are two typos in the error message given when the user attempts to change the Related Contact in a Relationship. (The word "on" should be "one" and the sentence is missing a period at the end of the sentence)

**What is the expected behavior?**
-No typos in the error message. (change "on" to "one" and add a period at the end of the sentence.)

**Steps to Reproduce:**
1. Create 3 Contacts : Giovanna Gamberini, Louisa Gamberini, and Diana Gamberini
2. Go to Giovanna Gamberini's Contact Record. 
3. From Giovanna Gamberini's Relationship Related List, click "New". 
-- In "Related Contact" add "Diana Gamberini"
-- In "Type" choose "Daughter"
-- Click Save
4. Ensure you're still on Giovanna's Gamberini's Contact Record.
5. From Giovanna Gamberini's Relationship Related List, click on the Relationship # just created (It will look similar to "R-000000")
-- In "Related Contact", click the Pencil to enable edit mode
-- Click the "X" to remove "Diana Gamberini" from the "Related Contact" field
-- Add "Louisa Gamberini" to the "Related Contact" field
-- Click Save
**Actual Result** : Error message is: *Rather than change the contacts in an existing relationship, delete this relationship and create a new on between the new contacts*
**Expected Result** : Error message should be: *Rather than change the contacts in an existing relationship, delete this relationship and create a new one between the new contacts.*

What is the motivation / use case for changing the behavior?
Quality!

**Comment by dgamboni** [comment]
**lurch: add

**Comment by dgamboni** [comment]
![Screen Shot 2019-07-12 at 12 29 23 PM](https://user-images.githubusercontent.com/3886084/61154006-d151ce00-a4a1-11e9-92ab-315be72319a4.jpg)

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C7YmQAK" target="_blank">W-034430</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.81 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release 1.81
