### ISSUE TITLE
EDA :  On Course Connection, Block Changes to Contact & Course Offering Lookup if the Course Connection has Associated Attendance Events

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/EDA#867]
**Do you want to request a *feature* or report a *bug*?**
BUG (?)

**What is the current behavior?**
If a Course Connection’s Contact Field is updated to someone else than the Attendance Event, the Attendance Event can have a mismatched Contact to the Course Connection. 

**What is the expected behavior?**
The Course Connection should always have the same Contact as the associated Attendance Events and Term Grades.

**What is the motivation / use case for changing the behavior?**
Data integrity

**Acceptance Criteria**

-**Given** I have a Course Connection
-**When** I have a related Attendance Event and/or a related Term Grade
-**Then** the contact on the Course Connection and Related Attendance Events and Term Grades are the same

-**Given** I have a Course Connection
-**When** I have a related Attendance Event and/or a related Term Grade
-**And** I try to change the Course Connection Contact
-**Then** I am prevented from changing the Course Connection Contact

**Steps to Reproduce**
- Create 2 Contacts, ex: "Phil Collins" and "Fela Kuti"
- Create a Department Account, ex: "Music Dept."
- Create a Term, ex: "Spring Term" (associated to "Music Dept.")
- Create a Course, ex: "Rhythm & Blues 101" (associated to "Music Dept.")
- Create a Course Offering, ex: "R&B101-Spring" with Course = Rhythm & Blues 101" & Term = "Spring"
- Create a Student Course Connection , ex: Student = "Phil Collins" & Course Offering ID = "R&B101-Spring"
- From that Course Connection Related List, create an Attendance Event
   - Contact = Blank, Attendance Type = Class Tardy, Date = Today's Date
- From that Term Grades Related List, create a Term Grade
- Go to the Course Connections "Details" List & Edit the Contact from "Phil Collins" to "Fela Kuti"
   - **Expected Behavior** : User is prevented from changing the Contact b/c Course Connection has related Attendance Event & Term Grades
   - **Actual Behavior** : User can change the Course Connection, and the Course Connection Contact is now "Fela Kuti"
- Go to the Course Connections "Related" List and click on the Attendance Event to see the details & Note Contact is Phil Collins
- Go back "Reports" and create a Report for Term Grades with Course Connection; add the "Course Connection Contact" column & Note the Contact is Fela Kuti
   - **Expected Behavior** --> Course Connection, Attendance Events, and Term Grades should all have the same / original Contact from the Course Connection
   - **Actual Behavior**--> Course Connection, Attendance Events, and Term Grades have mismatched contacts

**Comment by dgamboni** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C7dXQAS" target="_blank">W-034477</a>
