### ISSUE TITLE
Hybrid - Behavior Mgmt - Creation of Behavior Involvement and Behavior Response to handle light behavior management

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/EDA#875]
Spec: https://salesforce.quip.com/QLeJAxYpxBWE
Spike: https://salesforce.quip.com/h7L7AxaR3jXM

Purpose:

Keep track of an behavior case, who was involved (handle multiple people), when it happened, what happened, where it happened, and what actions were taken by the educational institution in response to the event. 

Keep track of a student's disciplinary marks through a school year, term, or their entire duration attending that education institution. An behavior case can involve multiple parties, multiple cases, and stay with the 'Contact' for the entire duration of the term or school year or time at the educational institution. 

The "Behavior Involvement" will the the junction object between a 'Contact' and a 'Case', which allows an organization to record a case for one incident and associate multiple people and their role played in said incident.

The "Behavior Response" will be an object linked to Behavior Involvement object through look up relationship, which allows an organization to record an action/response on a behavior involvement.

**Comment by xinnanlisf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C8RaQAK" target="_blank">W-034849</a>
