### ISSUE TITLE
Investigation: Ensure Simple Address Change Treated as Update

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#888]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Investigation

* **What is the current behavior?**
When Ensure Simple Address Change Treated as Update is enabled and an update is made to a single Address field along with a change to Primary Address Type on Contact a second Address record is created.

**Steps to reproduce:**
Note: Ensure Simple Address Change Treated as Update is enabled.

Step 1: Create a Contact with Address and set Primary Address Type = Home
Step 2: Edit Contact Address (i.e. not the Address record) as follows:
Step 2a: Update Mailing City
Step 2b: Change Primary Address Type from Home to Work
Step 3: Save

A 2nd Address record is created.

If you edit the same Contact again and only change Primary Address Type (i.e. from Work to Other) and save no new Address record is created.

* **What is the expected behavior?**

Per [EDA Documentation](https://powerofus.force.com/s/article/EDA-Add-or-Update-Addresses#simple) it doesn't seem to indicate that the Primary Address Type field is part of the Address fields on Contact. If that is the case then including a change to Primary Address Type, along with a single change to an Address field, should not trigger a new Address record to be created.

* **What is the motivation / use case for changing the behavior?**
Hub post: https://powerofus.force.com/s/feed/0D51E00004wlsL7SAI

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C96KQAS" target="_blank">W-035165</a>

**Comment by aligeez** [comment]
**lurch: attach W-038489

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HqT2QAK" target="_blank">W-038489</a>

**Comment by MatthewBlanski** [comment]
@xinnanlisf FYI

**Comment by kporray1** [comment]
This enhancement was delivered in January 2020.
