### ISSUE TITLE
Block Deletion of Contact, Course Offering, or the Course Connection when Term Grades & Attendance Event records exist

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/EDA#904]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Course Connections, Contacts, and Course Offerings can all be deleted even if they are associated with Attendance Events and Term Grades. This leads to data integrity issues.

**What is the expected behavior?**
Course Connections, Contacts, and Course Offerings should not be able to be deleted if there are associated Attendance Events and/or Term Grades.

**What is the motivation / use case for changing the behavior?**
Data integrity

**Comment by robertbwatson** [comment]
**lurch: attach W-035285

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C9NhQAK" target="_blank">W-035285</a>
