### ISSUE TITLE
Block Deletion of Terms when Term Grades Exist

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/EDA#905]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature 

* **What is the current behavior?**
Terms can be deleted even if there are Term Grade records associated with that Term.

* **What is the expected behavior?**
Terms should not be able to be deleted if Term Grade records exist.

* **What is the motivation / use case for changing the behavior?**
Data integrity

**Comment by robertbwatson** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CACiQAO" target="_blank">W-035719</a>

**Comment by MatthewBlanski** [comment]
Closed by #1025
