### ISSUE TITLE
Encrypted Contact Name Causing Errors in CON_PreferredPhone_TEST

### ISSUE THREAD

**Issue by kschaefges** [SalesforceFoundation/EDA#908]
When the Contact Name is encrypted via Shield Platform Encryption, the CON_PreferredPhone_TEST class throws the following error:

`_PreferredPhone__c FROM Contact where LastName = 'JohnnyTest' ^ ERROR at Row:1:Column:110 field 'LastName' can not be filtered in a query call_`

Orgs with this enabled on Contact Name are unable to get EDA upgraded.

**Steps to Repeat**
1. Create Permission Set with the "Manage Encryption Keys" System Permission.
2. Assign the Permission Set to your User record.
3. Go to Setup --> Key Management and click the Generate Tenant Secret button.
4. Go to Setup --> Encryption Policy and click the Encrypt Fields link.
5. Click Edit and check off the Contact Name.
6. Save.

Attempting to install, or push upgrade, the current EDA release will fail with that error.

**Comment by kschaefges** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAOFQA4" target="_blank">W-035844</a>

**Comment by lifewithryan** [comment]
Good catch @kschaefges -- I will bring this up in our next standup. I forget that we have to be shield compliant now as well so we can't have potentially encrypted fields in where clauses. Thank you!
