### ISSUE TITLE
EDA: Disabled Preferred Phone enforcement: Fails on test

### ISSUE THREAD

**Issue by SupportIECISA** [SalesforceFoundation/EDA#910]
When a Contact is Inseted on a Test Class throws the folloing exception:
`
System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, The phone selected for Preferred Phone can't be blank.: []
`
**Preconditions:**
· Disable Preferred Phone enforcement: True on EDA Settings
· CON_PreferredPhone_TDTM Trigger Handler as Inactive.

**Steps to repeat:**
· Create a Contact on a Class Test
· Insert the new Contact

**Comment by jacebryan** [comment]
Hi @SupportIECISA - please post this in the EDA Hub group so our team can engage with you further. I'll be closing this issue now. Thank you!
