### ISSUE TITLE
Prevent Deletion of a Behavior Involvement Record when there is a Related Behavior Response Record

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/EDA#913]
Request : Enhancement to Current Behavior

Current Behavior : If a Behavior Involvement record that has one or more Behavior Response records is deleted, the Behavior Response records become "orphaned" -- ie, the Behavior Response records have no associated Behavior Involvement or Contact records (which are required fields).

Expected Behavior : Behavior Response Records should not become orphaned

Acceptance Criteria : Given a Behavior Involvement record with one to many Behavior Response records; When I attempt to delete the Case record; I am not left with any orphaned Behavior Response records.

Notes :
-- "We can prevent the user from deleting the Behavior Involvement if it has a Behavior Response. They could then delete the Behavior Response themselves and then delete the Behavior Intervention (assuming that's an option)."
-- "We could also warn them that if the Behavior Intervention is deleted, we will also delete the related Behavior Responses."
-- "Use TDTM to enforce so that customers can turn on/off those triggers."
-- Do we want to prevent deletion of Contact if there are related Behavior Involvement records?

- Steps to Reproduce :
1. Create a Case
2. From the Case Related List, create a Behavior Involvement Record
3. From the Behavior Involvement Related List, create a Behavior Response record
4. From the Behavior Involvement Record, delete the Beh. Involvement. Then, go find the Behavior Response you just created (Behavior Responses > All list)
--> Actual Result : Behavior Response records no longer have a Behavior Involvement or Contact assigned to them.
--> Expected Result : User is prevented from having a Behavior Response record that does not have a Behavior Involvement or Contact assigned to it.

**Comment by dgamboni** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAX3QAO" target="_blank">W-035912</a>

**Comment by robertbwatson** [comment]
Duplicate of #1102 , Closing

**Comment by kdy618** [comment]
@robertbwatson , oops! Thank you so much
