### ISSUE TITLE
UX : "Sanity Check" on EDA/K12 Picklists to ensure “Other” is at the end of the lists.

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/EDA#914]
Request Type : Enhancement

Current Behavior : For some picklists in EDA, the "Other" option appears alphabetically. For other picklists, it appears at the end.

Expected Behavior : The "Other" option should appear at the end.

Motivation for Changing the Behavior : Consistency is a key principle of UX design. Consistency helps to reduce the learning time for a product as it's easier for the user to get familiar with the given experience. 

Acceptance Criteria : Given that I have a list of all picklist fields with "Other" as an option; when I review the list of options in those fields; "Other" will appear at the end.

**Comment by dgamboni** [comment]
**lurch: Add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAXCQA4" target="_blank">W-035914</a>

**Comment by MatthewBlanski** [comment]
This is an alpha sorting issue and an odd behavior in areas of EDA if alpha sorting is checked. Closing.
