### ISSUE TITLE
Deleting an administrative contact should also delete the administrative account

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/EDA#915]
* **Do you want to request a *feature* or report a *bug*?**
Enhancement

* **What is the current behavior?**
1. Create a new contact when the default mode is set to Administrative.
2. Delete the contact.
3. Notice that the account that was created to hold the contact still exists.

* **What is the expected behavior?**
If there are no other contacts associated to the account, the account should also be deleted. (This should be the case for administrative accounts.) *Note*: This may cause some additional thought, as there could be other records associated to the account that we don't want to lose.

* **What is the motivation / use case for changing the behavior?**
We could end up with contactless administrative accounts.

**Comment by robertbwatson** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAXRQA4" target="_blank">W-035916</a>

**Comment by MatthewBlanski** [comment]
Account deletion with no contacts captures this behavior and can be enabled, meeting this need. This does not resolve whether or not we want to enable this behavior by default with new customers.
