### ISSUE TITLE
Deleting an account should also delete any addresses

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/EDA#916]
* **Do you want to request a *feature* or report a *bug*?**
Enhancement

* **What is the current behavior?**
1. Create a new account.
2. Create a new address for that account.
3. Delete the account.
4. The address record is now "orphaned" and does not belong to any account.

* **What is the expected behavior?**
When the account is deleted, the address record should also be deleted. (Up for discussion: alternatively, we could prevent the account from being deleted if there are address records associated to it.)

* **What is the motivation / use case for changing the behavior?**
We could end up with address records that aren't tied to anything.

**Comment by robertbwatson** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAXSQA4" target="_blank">W-035917</a>

**Comment by MatthewBlanski** [comment]
This is addressed with prevent deletion logic.
