### ISSUE TITLE
Deleting a contact should also delete any addresses

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/EDA#917]
* **Do you want to request a *feature* or report a *bug*?**
Enhancement

* **What is the current behavior?**
1. Create a new contact.
2. Create a new address for that contact.
3. Delete the contact.
4. The address record is now "orphaned" and does not belong to any contact.

* **What is the expected behavior?**
When the contact is deleted, the address record should also be deleted. (Up for discussion: alternatively, we could prevent the contact from being deleted if there are address records associated to it.)

* **What is the motivation / use case for changing the behavior?**
We could end up with address records that aren't tied to anything.

**Comment by robertbwatson** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAXWQA4" target="_blank">W-035918</a>

**Comment by MatthewBlanski** [comment]
This is addressed with prevent deletion logic.
