### ISSUE TITLE
Prevent deleting contacts that have attribute records

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/EDA#918]
* **Do you want to request a *feature* or report a *bug*?**
Enhancement

* **What is the current behavior?**
1. Create a new contact.
2. Create a new attribute for that contact.
3. Delete the contact.
4. The attribute record is now "orphaned" and does not belong to any contact.

* **What is the expected behavior?**
When the contact is deleted and there are attribute records associated to it, an error should prevent the deletion. (Up for discussion: alternatively, we could also delete the attribute records.)

* **What is the motivation / use case for changing the behavior?**
We could end up with attribute records that aren't tied to any individual.

**Comment by robertbwatson** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAXXQA4" target="_blank">W-035919</a>

**Comment by kdy618** [comment]
**lurch: detach

**Comment by LurchTheButler** [comment]
Detached <a href="https://foundation.my.salesforce.com/a2x1E000001CAXXQA4" target="_blank">W-035919</a>

**Comment by kdy618** [comment]
**lurch: attach W-035285

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C9NhQAK" target="_blank">W-035285</a>
