### ISSUE TITLE
Properly handle course offering deletion when it has course connections

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/EDA#919]
* **Do you want to request a *feature* or report a *bug*?**
Enhancement

* **What is the current behavior?**
1. Create an account, term, course, and course offering related to that term & course.
2. Create a course connection for the course offering.
3. Delete the course offering.
4. The course connection is not deleted when the course offering is deleted.
*Note:* If the course connection is a primary faculty course connection, it *is* deleted. The affiliation record of the contact to the department is also deleted, if that affiliation is not tied to any other course connections. So, primary faculty course connections are handled differently than all other course connections.

* **What is the expected behavior?**
We should delete all course connection records to be consistent with how we delete primary faculty course connection records *or* we should prevent course offering records from being deleted if there are student course connections.

It will take some extra thought and design on what we should actually do here.

* **What is the motivation / use case for changing the behavior?**
Consistency and data integrity.

**Comment by robertbwatson** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAXbQAO" target="_blank">W-035920</a>

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.  W-7930233
