### ISSUE TITLE
Properly handle facility deletion when it is used by course offering schedules

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/EDA#920]
* **Do you want to request a *feature* or report a *bug*?**
Enhancement

* **What is the current behavior?**
1. Create a new facility record.
2. Create a new account, term, course, and course offering for that term and course.
3. Create a new course offering schedule for the course offering, specifying the facility record that you created in step #1.
4. Delete the facility.
5. You cannot delete the facility because it is tied to course offering schedule(s).

* **What is the expected behavior?**
We should not prevent users from deleting facility records that are tied to course offering schedules. Or, if we do want to restrict this, it should be moved to TDTM so that the customer can turn off this restriction if they wish. It is currently enforced via the platform and cannot be disabled.

* **What is the motivation / use case for changing the behavior?**
We should only prevent the deletion of records via the platform in use cases where we would never want to allow the customer to turn off that restriction.

**Comment by robertbwatson** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAXgQAO" target="_blank">W-035921</a>

**Comment by kporray1** [comment]
This issue is no longer being considered by the product team.  W-7930234
