### ISSUE TITLE
Prevent Deleting Contacts that have Behavior Involvement Records

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/EDA#921]
Request Type : Enhancement

What is the current behavior?
1. Create a new Contact.
2. Create a Case (assign a different contact) 
3. Create a Behavior Involvement for the Contact
4. Delete the Contact.
The Behavior Involvement record is now "orphaned" and does not belong to any contact.

What is the expected behavior?
When the contact is deleted and there are Behavior Involvement records associated to it, an error should prevent the deletion OR - an error message could warn users that if the Contact is deleted, we will also delete the related BI records.

What is the motivation / use case for changing the behavior?
We could end up with Behavior Involvement records that aren't tied to any individual.

**Comment by dgamboni** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAZIQA4" target="_blank">W-035934</a>

**Comment by kdy618** [comment]
**lurch: detach

**Comment by LurchTheButler** [comment]
Detached <a href="https://foundation.my.salesforce.com/a2x1E000001CAZIQA4" target="_blank">W-035934</a>

**Comment by kdy618** [comment]
**lurch: attach W-035285

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C9NhQAK" target="_blank">W-035285</a>
