### ISSUE TITLE
Update the Time Block lookup on the Course Offering related list and change the related list label to "Course Offerings"

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/EDA#922]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
The Time Block lookup on the Course Offering related list shows Time Block

* **What is the expected behavior?**
The Time Block lookup on the Course Offering related list shows Course Offerings

* **What is the motivation / use case for changing the behavior?**
Jace came across this while populating his GEM org with EDA data and called it out to the EDA Team.

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAdPQAW" target="_blank">W-035966</a>
