### ISSUE TITLE
Deleting Child Records for Program Plans & Program Requirements Gives Improper Error Toast

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/EDA#938]
Deleting child records gives improper error toast. 
 
This was noted Program Plans and Program Requirements -- I suggest we check if it happens elsewhere where there are Parent-Child Relationships, and ensure 1) What is happening in terms of deletion of parent records is as desired; 2) Any error messages are proper. See additional ticket :
 
Sample Steps to Reproduce :
* Program Plan > New     
     - Program Plan Name     
     - Tied to an Account     
     - "Is Primary" Checkbox = True     
     - Save
*Related Tab > Plan Requirements > New     
     - Program Requirement Name     
     - Add a New Parent Program Requirement     
     - Save / Save
* Try to Delete the Parent Program Requirement and/or Program Plan
 
Expected Result : Standard error message with proper grammar 
Actual Result : Slightly creepy message with incorrect grammar: "Record cannot be deleted because children records exist. Delete children first."

**Comment by xinnanlisf** [comment]
**lurch: attach W-[031498]

**Comment by xinnanlisf** [comment]
**lurch: attach W-031498

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008Ll69QAC" target="_blank">W-031498</a>
