### ISSUE TITLE
Trigger Handler record for CON_PreferredPhone_TDTM auto enabled with release 1.83

### ISSUE THREAD

**Issue by kschaefges** [SalesforceFoundation/EDA#941]
In EDA 1.82, a new trigger handler record was created to support preferred phone number enforcement.  This was shipped to existing customers as inactive.

In EDA 1.83, the standard push scripts auto-activated all Trigger handler records that are not marked as user managed.

Users may get errors when creating and updating contacts where a preferred phone is either not selected and multiple phone numbers are provided or where a preferred phone is selected and that phone number field is not populated.  This could affect external system integrations that are creating or updating contact records.

Workaround - Uncheck the "Active" checkbox field.  Also, ensure the User Managed field is not checked, unless other changes to the Trigger Handler record have been made (usernames to exclude, filters, trigger action ....).

**Comment by kschaefges** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CBCBQA4" target="_blank">W-036300</a>
