### ISSUE TITLE
Preferred Phone functionality does not work in languages other than English

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/EDA#946]
**Summary**

EDA 1.82 added a trigger handler for Preferred Phone which will automatically update the standard Phone based on the selection in the Preferred Phone picklist, and will ensure that a preferred phone is selected if more than one phone field is populated.

This functionality does not work as expected when the language is not English. 

**Workaround**

In EDA Settings (as of EDA 1.84), make sure Enable Enhanced Preferred Phone Functionality is unchecked. Or, remove translations on Preferred Phone picklist and work with this functionality using the English selections only.

**Steps to Repeat**

In English:

1. Create a Contact. Set Preferred Phone to Home and populate Home Phone and Other Phone. Save.
2. Confirm that the value in the Home Phone is now in the Phone standard field.
3. Change Preferred Phone to Other. Save.
4. Confirm that the value in the Other Phone is now in the Phone standard field.

Confirm that Translations are enabled for the organization in Translation Workbench. Make sure French is an active language. Switch User to use French Language (User record > Change Language to French - no other changes)

1. Go to the same Contact as used in the English example above.
2. Change Preferred Phone to Domicle (Home)

![image](https://user-images.githubusercontent.com/4614343/65770135-69f00580-e103-11e9-9d3c-12df0b5107f2.png)

**Expected Behavior**

Record should save and update Phone with the value in the Téléphone (domicile) field.

**Actual Behavior**

Error on Save.

![image](https://user-images.githubusercontent.com/4614343/65770250-b20f2800-e103-11e9-9c1b-8aa3c6cb83c9.png)

Translates to: The phone specified in Preferred Phone was not found. Be sure to type the label of an existing custom phone field.

It appears that we are hard-coding the English values [here](https://github.com/SalesforceFoundation/EDA/blob/master/src/classes/CON_Preferred_TDTM.cls#L61).

**Comment by judisohn** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CBGNQA4" target="_blank">W-036338</a>
