### ISSUE TITLE
Preferred Phone saving invalid setting

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#947]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
User is allowed to save incorrect state: 
Enable Enhanced Preferred Phone Functionality - unchecked
Disable Preferred Phone enforcement - checked

![save_invalid](https://user-images.githubusercontent.com/1894238/65778426-809a5a80-e10b-11e9-9614-145f85343401.gif)

* **What is the expected behavior?**
If "Enable Enhanced Preferred Phone Functionality" is unchecked, user cannot save "Disable Preferred Phone enforcement" checked.

There are multiple possible ways to prevent this, including:
- automatically unchecking second checkbox when first checkbox is checked
- preventing save by giving an error message
- ...

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CBGXQA4" target="_blank">W-036340</a>
