### ISSUE TITLE
Add Attendance Event related list to Contact Page Layout

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/EDA#953]
We want to add attendance event related list to contact page layout. This won't reach to existing customers and will only appear for new customers. Existing customers have to add this related list to contact page layout by themselves.

**Comment by xinnanlisf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CBM1QAO" target="_blank">W-036399</a>

**Comment by aligeez** [comment]
Not every Higher Ed institution is going to use Attendance tracking, so we shouldn't include it out of the box. If they want it, they can add it.
