### ISSUE TITLE
Add triggers for recently added objects

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/EDA#959]
We need triggers for:

- Behavior Involvement
- Behavior Response
- Case
- Attribute
- Language (seems like one already exists for ContactLanguage)
- Facility

The goal is that all orgs with EDA follow the best practice of a single trigger per object. We want to provide them so customers use ours instead of theirs if the write TDTM classes.

We need to consider that some customers may have already created their own triggers for some of these objects. I *think* (fairly certain) this should be fine, but we need to think it through.

**Comment by ceiroa** [comment]
**lurch: attach W-036678

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CBoFQAW" target="_blank">W-036678</a>
