### ISSUE TITLE
Ensure that Account Naming for HouseHold is in Alphabetical Order

### ISSUE THREAD

**Issue by kdy618** [SalesforceFoundation/EDA#966]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Bug 

* **What is the current behavior?**
When the Account name format of the org contains either {!LastName} ({!FirstName}), 
{!{!FirstName} {!LastName}, {!LastName} ({!{!FirstName}}), the Account renaming isn't correctly renaming the Account name in the correct alphabetical order. 

* **What is the expected behavior?**
The Account Name process should update the Account Name in the correct alphabetical order regardless of which format is set in the org. 

* **What is the motivation / use case for changing the behavior?**
This helps ensure that user experience is consistent regardless of the Account name format selected.

**Comment by kdy618** [comment]
**lurch: add W-036799

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CC2lQAG" target="_blank">W-036799</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CC5pQAG" target="_blank">W-036820</a>
