### ISSUE TITLE
Incorrect Course Connection Tooltips

### ISSUE THREAD

**Issue by kdy618** [SalesforceFoundation/EDA#974]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Bug 

* **What is the current behavior?**
The description and help texts for the following fields are inaccurate. 
- Contact's Academic Program
- Course Offering
- Affiliation
- Contact

* **What is the expected behavior?**
The description and help texts for the fields listed above should be inclusive of Student and Faculty Course Connection. 

* **What is the motivation / use case for changing the behavior?**
Accurate documentation

**Comment by kdy618** [comment]
**lurch: attach W-036779

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CC0GQAW" target="_blank">W-036779</a>

**Comment by kdy618** [comment]
**lurch: detach

**Comment by kdy618** [comment]
**lurch: attach W-037065

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HnqQQAS" target="_blank">W-037065</a>
