### ISSUE TITLE
When deleting an address, the filter field and usernames to exclude filters are not working in the trigger handler for the address trigger ADDR_Addresses_TDTM.

### ISSUE THREAD

**Issue by jcaglarcan** [SalesforceFoundation/EDA#988]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
bug
* **What is the current behavior?**
When deleting an address, the filter field and usernames to exclude filters are not working in the trigger handler for the address trigger ADDR_Addresses_TDTM.  Delete an address with a parent contact that meets filter field criteria, and the mailing address fields on the associated contact are cleared out.  The filters do work when editing an address, but not deleting.

To reproduce, setup a filter field and usernames to exclude in the trigger handler.  Delete an address with a parent contact that meets filter field criteria, and the mailing address fields on the associated contact will be cleared out.

* **What is the expected behavior?**
If the record meets filter criteria, the parent address fields should not be edited.
* **What is the motivation / use case for changing the behavior?**
Trigger is firing and updating records unexpectedly.
* **Acceptance Criteria**

  - **Given**: I am on a certain page
  - **When**: I click a button
  - **Then**: An action should occur

* **Keyboard Acceptance Criteria**

  - **Given**: I am navigating the site using only my keyboard
  - **When**: I tab to the button
  - **Then**: I should see the button highlighted on focus
  - **And When**: I press enter on a highlighted button
  - **Then**: An action should occur

* **Screenreader Acceptance Criteria**

  - **Given**: I am using a screenreader to navigate the site
  - **When**: I tab to the button
  - **Then**: I should hear the label of the button
  - **And When**: I press enter
  - **Then**: I should hear that an action has occurred

**Comment by aligeez** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HoUCQA0" target="_blank">W-037444</a>
